In [9]:
import pandas as pd
import os

# file1 = pd.read_csv("caltrans/meta/2017/d11/d11_text_meta_2016_12_07.txt", sep="\t")
# file2 = pd.read_csv("caltrans/meta/2017/d11/d11_text_meta_2017_03_08.txt", sep="\t")
# file3 = pd.read_csv("caltrans/meta/2017/d11/d11_text_meta_2017_02_22.txt", sep="\t")

In [41]:
df_sensors = pd.read_csv("graph_sensor_locations_bay.csv", names = ["ID", "lat", "long"])
df_sensors

         ID        lat        long
0    400001  37.364085 -121.901149
1    400017  37.253303 -121.945440
2    400030  37.359087 -121.906538
3    400040  37.294949 -121.873109
4    400045  37.363402 -121.902233
..      ...        ...         ...
320  413845  37.422887 -121.925747
321  413877  37.321613 -121.899642
322  413878  37.324641 -121.888603
323  414284  37.323066 -121.896538
324  414694  37.315051 -121.913497

[325 rows x 3 columns]

In [42]:
df_sensors = df_sensors[df_sensors.ID != 402368]
df_sensors = df_sensors[df_sensors.ID != 402369]
df_sensors = df_sensors[df_sensors.ID != 404554]
df_sensors = df_sensors[df_sensors.ID != 402288]
df_sensors = df_sensors[df_sensors.ID != 402289]

In [45]:
sensors = df_sensors.iloc[:, 0].values 
len(sensors), sensors

(320,
 array([400001, 400017, 400030, 400040, 400045, 400052, 400057, 400059,
        400065, 400069, 400073, 400084, 400085, 400088, 400096, 400097,
        400100, 400104, 400109, 400122, 400147, 400148, 400149, 400158,
        400160, 400168, 400172, 400174, 400178, 400185, 400201, 400206,
        400209, 400213, 400221, 400222, 400227, 400236, 400238, 400240,
        400246, 400253, 400257, 400258, 400268, 400274, 400278, 400280,
        400292, 400296, 400298, 400330, 400336, 400343, 400353, 400372,
        400394, 400400, 400414, 400418, 400429, 400435, 400436, 400440,
        400449, 400457, 400461, 400464, 400479, 400485, 400499, 400507,
        400508, 400514, 400519, 400528, 400545, 400560, 400563, 400567,
        400581, 400582, 400586, 400637, 400643, 400648, 400649, 400654,
        400664, 400665, 400668, 400673, 400677, 400687, 400688, 400690,
        400700, 400709, 400713, 400714, 400715, 400717, 400723, 400743,
        400750, 400760, 400772, 400790, 400792, 400794, 400799, 400804,
        400822, 400823, 400828, 400832, 400837, 400842, 400863, 400869,
        400873, 400895, 400904, 400907, 400911, 400916, 400922, 400934,
        400951, 400952, 400953, 400964, 400965, 400970, 400971, 400973,
        400995, 400996, 401014, 401129, 401154, 401163, 401167, 401210,
        401224, 401327, 401351, 401388, 401391, 401400, 401403, 401440,
        401457, 401464, 401489, 401495, 401507, 401534, 401541, 401555,
        401560, 401567, 401597, 401606, 401611, 401655, 401808, 401809,
        401810, 401811, 401816, 401817, 401845, 401846, 401890, 401891,
        401906, 401908, 401926, 401936, 401937, 401942, 401943, 401948,
        401957, 401958, 401994, 401996, 401997, 401998, 402056, 402057,
        402058, 402059, 402060, 402061, 402067, 402117, 402118, 402119,
        402120, 402121, 402281, 402282, 402283, 402284, 402285, 402286,
        402287, 402359, 402360, 402361, 402362, 402363, 402364, 402365,
        402366, 402367, 402370, 402371, 402372, 402373, 403225, 403265,
        403329, 403401, 403402, 403404, 403406, 403409, 403412, 403414,
        403419, 404370, 404434, 404435, 404444, 404451, 404452, 404453,
        404461, 404462, 404521, 404522, 404553, 404585, 404586, 404640,
        404753, 404759, 405613, 405619, 405701, 407150, 407151, 407152,
        407153, 407155, 407157, 407161, 407165, 407172, 407173, 407174,
        407176, 407177, 407179, 407180, 407181, 407184, 407185, 407186,
        407187, 407190, 407191, 407194, 407200, 407202, 407204, 407206,
        407207, 407321, 407323, 407325, 407328, 407331, 407332, 407335,
        407336, 407337, 407339, 407341, 407342, 407344, 407348, 407352,
        407359, 407360, 407361, 407364, 407367, 407370, 407372, 407373,
        407374, 407710, 407711, 408907, 408911, 409524, 409525, 409526,
        409528, 409529, 413026, 413845, 413877, 413878, 414284, 414694],
       dtype=int64))

In [2]:
# for 2017 data with multiple meta files

import os

# count = 0
# filelist = []
# for filename in os.listdir("caltrans/meta/2017/d11/"):     
#     if count < 10: 
#         print(filename)
#         file = pd.read_csv("caltrans/meta/2017/d11/" + filename, sep="\t")
#         filelist.append(file)
#         count += 1

In [ ]:
test_sensors = torch.tensor([3, 11, 13, 14, 15, 16, 19, 24, 27, 29, 31, 36, 38, 41, 50, 62,
       73, 75, 76])

In [4]:
file = pd.read_csv("caltrans/meta/2021/d4/d04_text_meta_2021_01_29.txt", sep="\t")
# file = pd.read_csv("caltrans/meta/2017/d11/d11_text_meta_2017_05_19.txt", sep='delimiter')

In [10]:
file

,ID,Fwy,Dir,District,County,City,State_PM,Abs_PM,Latitude,Longitude,Length,Type,Lanes,Name,User_ID_1,User_ID_2,User_ID_3,User_ID_4
0,400000,101,S,4,41,52582.0,19.23,459.835,38.081498,-122.547963,0.415,ML,4,SR-37 conn-s-diag,DT5A2,L4-S-27-101-01923,101482.0,424150
1,400001,101,N,4,85,68000.0,38.26,387.897,37.364085,-121.901149,0.265,ML,5,NB 880 rm-n-loop,DT697,L5-N-37-101-03826,998145.0,426518
2,400002,101,S,4,81,68252.0,14.67,416.893,37.584097,-122.328465,0.310,ML,5,Peninsula Ave OC,DT243,L5-S-35-101-01467,106296.0,426945
3,400006,880,S,4,1,81204.0,13.54,23.767,37.605003,-122.065542,0.340,ML,4,Whipple Rd rm-s-diag,DTA20,L4-S-33-880-01354,998415.0,421858
4,400007,101,N,4,81,68252.0,15.25,417.437,37.586936,-122.337721,0.365,ML,5,2000' N of Pennisula Ave,DT275,L5-N-35-101-01525,999325.0,426427
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3924,425694,101,N,4,85,55282.0,51.88,401.517,37.445738,-122.119527,NaN,FR,1,Embarcadero Rd off,DT2F0,z1-N-37-101-05188,755658.0,447901
3925,425696,101,N,4,85,55282.0,52.05,401.687,37.447630,-122.121513,NaN,FR,2,Embarcadero Rd off,DT2F0,z2-N-37-101-05205,755659.0,447904
3926,425697,101,N,4,85,55282.0,52.29,401.927,37.450295,-122.124287,0.250,ML,4,Embarcadero Rd rm-n-coll,DT2F0,L4-N-37-101-05229,107290.0,447907
3927,425699,101,N,4,85,49670.0,50.16,399.797,37.426603,-122.099455,NaN,FR,1,San Antonio Rd off,DT832,NaN,755660.0,447900
3928,425734,101,S,4,85,55282.0,52.29,401.963,37.450145,-122.124496,0.225,ML,4,oppo Embarcadero Rd rm-n-coll,DT2F0,L4-S-37-101-05229,107300.0,447912

In [11]:
ids = file["ID"].tolist() 
for x in sample: 
    print(x in ids)

True
True
True
True

In [5]:
ids = file[(file["Fwy"] == 5) & (file["Dir"] == "S") & (file["Type"] == "ML")]["ID"]

In [6]:
ids

173     1108417
186     1108434
202     1108452
205     1108459
207     1108461
         ...
1125    1122583
1162    1123134
1303    1126426
1359    1126864
1371    1127123
Name: ID, Length: 85, dtype: int64

In [7]:
sensors = ids.values.tolist()

In [3]:
# filter out common sensor ids (for 2017 data)

# a = []
# for i in range(len(filelist)): 
#     file = filelist[i][(filelist[i]["Fwy"] == 5) & (filelist[i]["Dir"] == "S") & (filelist[i]["Type"] == "ML")]["ID"]
#     if i == 0: 
#         a = file
#     else: 
#         a = list(set(a).intersection(file))

In [8]:
indexs = []
for index in sensors: 
    indexs.append(file[file["ID"] == index].index.values[0])

In [9]:
df_sensors = file.iloc[indexs] 

# sort sensors Abs_pm from N to S
df_sensors = df_sensors.sort_values(by=["Abs_PM"], ascending=True)
# df_sensors

In [10]:
df_sensors = df_sensors[df_sensors.ID != 1126864]
df_sensors = df_sensors[df_sensors.ID != 1121715]
df_sensors = df_sensors[df_sensors.ID != 1122560]
df_sensors = df_sensors[df_sensors.ID != 1119877]
df_sensors = df_sensors[df_sensors.ID != 1119997]
df_sensors = df_sensors[df_sensors.ID != 1123134]
df_sensors = df_sensors[df_sensors.ID != 1118702]

In [11]:
df_sensors["Lanes"].min()

3

In [13]:
len(df_sensors)

78

In [14]:
df_sensors = df_sensors.iloc[::-1]

In [18]:
df_sensors.reset_index(drop=True, inplace=True)

In [19]:
df_sensors

,ID,Fwy,Dir,District,County,City,State_PM,Abs_PM,Latitude,Longitude,Length,Type,Lanes,Name,User_ID_1,User_ID_2,User_ID_3,User_ID_4
0,1121734,5,S,11,73,NaN,71.050,70.878,33.383349,-117.578043,3.822,ML,4,5 SB Basilone Rd,1,NaN,NaN,NaN
1,1121712,5,S,11,73,NaN,62.591,62.419,33.303834,-117.470867,2.509,ML,4,5 SB Las Pulgas Rd,1,NaN,NaN,NaN
2,1121702,5,S,11,73,NaN,60.601,60.429,33.281440,-117.449446,2.045,ML,4,5 SB N/O Rest Area,1,NaN,NaN,NaN
3,1119978,5,S,11,73,NaN,57.000,56.858,33.240152,-117.413376,1.235,ML,4,.5 N/O STA MARGRITA,1,NaN,NaN,NaN
4,1119966,5,S,11,73,NaN,56.000,55.858,33.230196,-117.400904,1.000,ML,4,S/O SANTA MARGARITA,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,1118365,5,S,11,73,66000.0,3.426,3.336,32.568952,-117.076731,0.722,ML,4,5 SB N/0 905,1,NaN,NaN,NaN
74,1114721,5,S,11,73,66000.0,2.649,2.559,32.561106,-117.067228,0.574,ML,4,N/O DAIRY MART RD,1,NaN,NaN,NaN
75,1118341,5,S,11,73,66000.0,2.276,2.186,32.558188,-117.061806,0.710,ML,4,5 SB @ Dairy Mart,1,NaN,NaN,NaN
76,1118326,5,S,11,73,66000.0,1.230,1.140,32.551447,-117.045806,0.982,ML,4,5 SB @ Via de Ysidro,1,NaN,NaN,NaN
77,1114228,5,S,11,73,66000.0,0.311,0.221,32.544296,-117.032738,0.681,ML,6,N/O CMNO DE LA PLAZA,1,NaN,NaN,NaN

In [52]:
max_dis = (70.878 - 0.221) * 1609 
max_dis

113687.113

In [64]:
import csv 
import math 

with open('sensor.csv', 'w') as csvfile: 
    csvwriter = csv.writer(csvfile) 
    csvwriter.writerow(["from", "to", "distance"]) 
    for index, row in df_sensors.iterrows(): 
        for index2, row2 in df_sensors.iterrows(): 
            distance = 0  
            if index <= index2: 
                distance = abs(row["Abs_PM"] - row2["Abs_PM"]) * 1609
#             else: 
#                 distance = 2 * max_dis - abs(row["Abs_PM"] - row2["Abs_PM"]) * 1609
#                 distance = 0 
#             context.append([row["ID"], row2["ID"], distance]) 
    
                csvwriter.writerow([row["ID"], row2["ID"], distance]) 
#     csvwriter.writerow(context)

In [65]:
file = pd.read_csv("sensor.csv") 
file

         from       to   distance
0     1121734  1121734      0.000
1     1121734  1121712  13610.531
2     1121734  1121702  16812.441
3     1121734  1119978  22558.180
4     1121734  1119966  24167.180
...       ...      ...        ...
3076  1118341  1118326   1683.014
3077  1118341  1114228   3161.685
3078  1118326  1118326      0.000
3079  1118326  1114228   1478.671
3080  1114228  1114228      0.000

[3081 rows x 3 columns]

In [47]:
file1 = open("id.txt","w") 
# ids = [] 
for index, row in df_sensors.iterrows(): 
    file1.write(str(row["ID"]) + ",") 
file1.close()

In [13]:
df_sensors.tail(40)

,ID,Fwy,Dir,District,County,City,State_PM,Abs_PM,Latitude,Longitude,Length,Type,Lanes,Name,User_ID_1,User_ID_2,User_ID_3,User_ID_4
399,1108669,5,S,11,73,66000.0,26.730,26.621,32.848532,-117.235725,0.796,ML,4,Gilman Dr,1,NaN,NaN,NaN
202,1108452,5,S,11,73,66000.0,27.903,27.794,32.864527,-117.230028,0.867,ML,4,Nobel Dr,1,NaN,NaN,NaN
241,1108498,5,S,11,73,66000.0,28.464,28.355,32.872590,-117.229295,1.548,ML,4,WB LA JOLLA VILLAGE,1,NaN,NaN,NaN
1371,1127123,5,S,11,73,66000.0,31.000,30.891,32.908625,-117.226840,1.391,ML,3,5SB @ JCT 5/805,1,NaN,NaN,NaN
1117,1122544,5,S,11,73,66000.0,31.278,31.136,32.911761,-117.228812,0.312,ML,6,5 SB N/O 5/805,1,NaN,NaN,NaN
1031,1120754,5,S,11,73,66000.0,31.659,31.517,32.916250,-117.232541,0.318,ML,4,Carmel Mt. To SB 5,1,NaN,NaN,NaN
1122,1122567,5,S,11,73,66000.0,31.917,31.775,32.918817,-117.235742,0.275,ML,4,5 SB Bypass,1,NaN,NaN,NaN
1125,1122583,5,S,11,73,66000.0,32.466,32.324,32.925907,-117.239661,0.443,ML,5,5 SB S/O 56,1,NaN,NaN,NaN
186,1108434,5,S,11,73,66000.0,32.805,32.663,32.930855,-117.241058,0.607,ML,4,CARMEL VALLEY RD,1,NaN,NaN,NaN
968,1119834,5,S,11,73,66000.0,33.681,33.539,32.943442,-117.242594,0.753,ML,4,SB 5 S/O DEL MAR,1,NaN,NaN,NaN
940,1119528,5,S,11,73,66000.0,34.311,34.169,32.952468,-117.244298,0.784,ML,5,WB Del Mar Heights,1,NaN,NaN,NaN
969,1119842,5,S,11,73,66000.0,35.250,35.108,32.965730,-117.247857,0.983,ML,5,SB 5 SAN DIEGUITO,1,NaN,NaN,NaN
214,1108468,5,S,11,73,66000.0,36.278,36.136,32.979936,-117.253246,1.074,ML,4,WB VIA DE LA VALLE,1,NaN,NaN,NaN
216,1108471,5,S,11,73,66000.0,37.397,37.255,32.995868,-117.256708,1.151,ML,4,LOMAS SANTA FE DR,1,NaN,NaN,NaN
218,1108473,5,S,11,73,22678.0,38.582,38.440,33.010653,-117.265240,0.901,ML,4,MANCHESTER AVE,1,NaN,NaN,NaN
945,1119666,5,S,11,73,22678.0,39.201,39.059,33.017512,-117.272059,0.622,ML,4,5 S N/O VISTA VIEW,1,NaN,NaN,NaN
220,1108475,5,S,11,73,22678.0,39.827,39.685,33.026250,-117.274915,0.712,ML,4,BIRMINGHAM DR,1,NaN,NaN,NaN
222,1108477,5,S,11,73,22678.0,40.625,40.483,33.036347,-117.281649,0.850,ML,4,SANTA FE DR,1,NaN,NaN,NaN
224,1108479,5,S,11,73,22678.0,41.527,41.385,33.048438,-117.287351,0.702,ML,4,ENCINITAS BLVD,1,NaN,NaN,NaN
445,1108723,5,S,11,73,22678.0,42.690,42.548,33.064772,-117.292309,0.635,ML,4,Leucadia Blvd,1,NaN,NaN,NaN
974,1119897,5,S,11,73,22678.0,43.301,43.159,33.073371,-117.294873,0.547,ML,4,SB 5 N/O LEUCADIA,1,NaN,NaN,NaN
447,1108725,5,S,11,73,22678.0,43.785,43.643,33.080188,-117.296877,0.700,ML,4,La Costa Ave,1,NaN,NaN,NaN
976,1119909,5,S,11,73,11194.0,44.701,44.559,33.092248,-117.303383,0.825,ML,4,SB 5 N/O BATIQUITOS,1,NaN,NaN,NaN
404,1108680,5,S,11,73,11194.0,45.435,45.293,33.101626,-117.309439,0.799,ML,4,POINSETTIA LN,1,NaN,NaN,NaN
977,1119915,5,S,11,73,11194.0,46.300,46.158,33.112683,-117.316473,0.830,ML,4,SB 5 N/O POINSETTIA,1,NaN,NaN,NaN
409,1108685,5,S,11,73,11194.0,47.097,46.955,33.122973,-117.322702,0.832,ML,4,WB PALOMAR AIRPORT,1,NaN,NaN,NaN
391,1108661,5,S,11,73,11194.0,47.965,47.823,33.134215,-117.329382,1.076,ML,4,CANNON RD,1,NaN,NaN,NaN
297,1108560,5,S,11,73,11194.0,49.250,49.108,33.151704,-117.336331,1.062,ML,4,TAMARACK AVE,1,NaN,NaN,NaN
387,1108657,5,S,11,73,11194.0,50.090,49.948,33.162818,-117.342266,0.730,ML,4,CARLSBAD VILLAGE DR,1,NaN,NaN,NaN
209,1108463,5,S,11,73,11194.0,50.710,50.568,33.170920,-117.346811,0.672,ML,4,LAS FLORES DR,1,NaN,NaN,NaN
207,1108461,5,S,11,73,53322.0,51.435,51.293,33.179734,-117.353651,0.848,ML,4,CASSIDY ST,1,NaN,NaN,NaN
205,1108459,5,S,11,73,53322.0,52.408,52.266,33.191277,-117.363281,0.932,ML,4,Oceanside Blvd,1,NaN,NaN,NaN
401,1108672,5,S,11,73,53322.0,53.300,53.158,33.200618,-117.373434,1.013,ML,4,WB RTE 76/MISSION,1,NaN,NaN,NaN
1090,1122257,5,S,11,73,NaN,54.434,54.292,33.210909,-117.387715,0.850,ML,4,SB 5 @ HARBOR DR,1,NaN,NaN,NaN
983,1119954,5,S,11,73,NaN,55.000,54.858,33.218567,-117.391109,0.783,ML,4,S5 N/O CAMP DEL MAR,1,NaN,NaN,NaN
985,1119966,5,S,11,73,NaN,56.000,55.858,33.230196,-117.400904,1.000,ML,4,S/O SANTA MARGARITA,1,NaN,NaN,NaN
987,1119978,5,S,11,73,NaN,57.000,56.858,33.240152,-117.413376,1.235,ML,4,.5 N/O STA MARGRITA,1,NaN,NaN,NaN
1064,1121702,5,S,11,73,NaN,60.601,60.429,33.281440,-117.449446,2.045,ML,4,5 SB N/O Rest Area,1,NaN,NaN,NaN
1066,1121712,5,S,11,73,NaN,62.591,62.419,33.303834,-117.470867,2.509,ML,4,5 SB Las Pulgas Rd,1,NaN,NaN,NaN
1070,1121734,5,S,11,73,NaN,71.050,70.878,33.383349,-117.578043,3.822,ML,4,5 SB Basilone Rd,1,NaN,NaN,NaN

In [24]:
df_sensors

,ID,Fwy,Dir,District,County,City,State_PM,Abs_PM,Latitude,Longitude,Length,Type,Lanes,Name,User_ID_1,User_ID_2,User_ID_3,User_ID_4
701,1114228,5,S,11,73,66000.0,0.311,0.221,32.544296,-117.032738,0.681,ML,6,N/O CMNO DE LA PLAZA,1,NaN,NaN,NaN
871,1118326,5,S,11,73,66000.0,1.230,1.140,32.551447,-117.045806,0.982,ML,4,5 SB @ Via de Ysidro,1,NaN,NaN,NaN
873,1118341,5,S,11,73,66000.0,2.276,2.186,32.558188,-117.061806,0.710,ML,4,5 SB @ Dairy Mart,1,NaN,NaN,NaN
719,1114721,5,S,11,73,66000.0,2.649,2.559,32.561106,-117.067228,0.574,ML,4,N/O DAIRY MART RD,1,NaN,NaN,NaN
876,1118365,5,S,11,73,66000.0,3.426,3.336,32.568952,-117.076731,0.722,ML,4,5 SB N/0 905,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
985,1119966,5,S,11,73,NaN,56.000,55.858,33.230196,-117.400904,1.000,ML,4,S/O SANTA MARGARITA,1,NaN,NaN,NaN
987,1119978,5,S,11,73,NaN,57.000,56.858,33.240152,-117.413376,1.235,ML,4,.5 N/O STA MARGRITA,1,NaN,NaN,NaN
1064,1121702,5,S,11,73,NaN,60.601,60.429,33.281440,-117.449446,2.045,ML,4,5 SB N/O Rest Area,1,NaN,NaN,NaN
1066,1121712,5,S,11,73,NaN,62.591,62.419,33.303834,-117.470867,2.509,ML,4,5 SB Las Pulgas Rd,1,NaN,NaN,NaN
1070,1121734,5,S,11,73,NaN,71.050,70.878,33.383349,-117.578043,3.822,ML,4,5 SB Basilone Rd,1,NaN,NaN,NaN

In [25]:
df_sensors.to_csv("sensors.csv")

In [26]:
b = pd.read_csv("sensors.csv") 
b

,Unnamed: 0,ID,Fwy,Dir,District,County,City,State_PM,Abs_PM,Latitude,Longitude,Length,Type,Lanes,Name,User_ID_1,User_ID_2,User_ID_3,User_ID_4
0,701,1114228,5,S,11,73,66000.0,0.311,0.221,32.544296,-117.032738,0.681,ML,6,N/O CMNO DE LA PLAZA,1,NaN,NaN,NaN
1,871,1118326,5,S,11,73,66000.0,1.230,1.140,32.551447,-117.045806,0.982,ML,4,5 SB @ Via de Ysidro,1,NaN,NaN,NaN
2,873,1118341,5,S,11,73,66000.0,2.276,2.186,32.558188,-117.061806,0.710,ML,4,5 SB @ Dairy Mart,1,NaN,NaN,NaN
3,719,1114721,5,S,11,73,66000.0,2.649,2.559,32.561106,-117.067228,0.574,ML,4,N/O DAIRY MART RD,1,NaN,NaN,NaN
4,876,1118365,5,S,11,73,66000.0,3.426,3.336,32.568952,-117.076731,0.722,ML,4,5 SB N/0 905,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,985,1119966,5,S,11,73,NaN,56.000,55.858,33.230196,-117.400904,1.000,ML,4,S/O SANTA MARGARITA,1,NaN,NaN,NaN
74,987,1119978,5,S,11,73,NaN,57.000,56.858,33.240152,-117.413376,1.235,ML,4,.5 N/O STA MARGRITA,1,NaN,NaN,NaN
75,1064,1121702,5,S,11,73,NaN,60.601,60.429,33.281440,-117.449446,2.045,ML,4,5 SB N/O Rest Area,1,NaN,NaN,NaN
76,1066,1121712,5,S,11,73,NaN,62.591,62.419,33.303834,-117.470867,2.509,ML,4,5 SB Las Pulgas Rd,1,NaN,NaN,NaN
77,1070,1121734,5,S,11,73,NaN,71.050,70.878,33.383349,-117.578043,3.822,ML,4,5 SB Basilone Rd,1,NaN,NaN,NaN

In [17]:
sorted_sensors.reverse()

In [18]:
sorted_sensors, len(sorted_sensors)

([1121734,
  1121712,
  1121702,
  1119978,
  1119966,
  1119954,
  1122257,
  1108672,
  1108459,
  1108461,
  1108463,
  1108657,
  1108560,
  1108661,
  1108685,
  1119915,
  1108680,
  1119909,
  1108725,
  1119897,
  1108723,
  1108479,
  1108477,
  1108475,
  1119666,
  1108473,
  1108471,
  1108468,
  1119842,
  1119528,
  1119834,
  1108434,
  1122583,
  1122567,
  1120754,
  1122544,
  1127123,
  1108498,
  1108452,
  1108669,
  1119817,
  1108667,
  1118529,
  1119307,
  1108693,
  1108711,
  1114806,
  1126426,
  1117818,
  1108615,
  1117871,
  1108609,
  1117724,
  1108605,
  1117734,
  1108417,
  1117683,
  1117810,
  1117789,
  1117774,
  1114268,
  1117755,
  1118076,
  1114254,
  1118472,
  1118465,
  1114240,
  1118428,
  1118413,
  1120356,
  1118695,
  1118379,
  1118372,
  1118365,
  1114721,
  1118341,
  1118326,
  1114228],
 78)

In [10]:
df_sensors = df_sensors[df_sensors.ID != 1126864]
df_sensors = df_sensors[df_sensors.ID != 1121715]
df_sensors = df_sensors[df_sensors.ID != 1122560]
df_sensors = df_sensors[df_sensors.ID != 1119877]
df_sensors = df_sensors[df_sensors.ID != 1119997]
df_sensors = df_sensors[df_sensors.ID != 1123134]
df_sensors = df_sensors[df_sensors.ID != 1118702]

In [48]:
sorted_abs_pm, len(sorted_abs_pm)

([0.221,
  1.14,
  2.186,
  2.559,
  3.336,
  4.003,
  4.578,
  5.324,
  6.627,
  7.201,
  7.819,
  9.898,
  10.796,
  11.178,
  11.848,
  12.113,
  13.022,
  13.372,
  14.416,
  14.856,
  15.23,
  15.698,
  16.001,
  16.666,
  17.23,
  17.572,
  18.05,
  18.346,
  18.822,
  19.156,
  20.611,
  21.366,
  21.973,
  22.85,
  23.466,
  24.118,
  25.739,
  26.201,
  26.621,
  27.794,
  28.355,
  30.891,
  31.136,
  31.517,
  31.775,
  32.324,
  32.663,
  33.539,
  34.169,
  35.108,
  36.136,
  37.255,
  38.44,
  39.059,
  39.685,
  40.483,
  41.385,
  42.548,
  43.159,
  43.643,
  44.559,
  45.293,
  46.158,
  46.955,
  47.823,
  49.108,
  49.948,
  50.568,
  51.293,
  52.266,
  53.158,
  54.292,
  54.858,
  55.858,
  56.858,
  60.429,
  62.419,
  70.878],
 78)

In [14]:
sorted_sensors = df_sensors["ID"].tolist()
sorted_abs_pm = df_sensors["Abs_PM"].tolist()
sorted_name = df_sensors["Name"].tolist()

In [16]:
sorted_sensors, sorted_abs_pm, sorted_name

([1114228,
  1118326,
  1118341,
  1114721,
  1118365,
  1118372,
  1118379,
  1118695,
  1120356,
  1118413,
  1118428,
  1114240,
  1118465,
  1118472,
  1114254,
  1118076,
  1117755,
  1114268,
  1117774,
  1117789,
  1117810,
  1117683,
  1108417,
  1117734,
  1108605,
  1117724,
  1108609,
  1117871,
  1108615,
  1117818,
  1126426,
  1114806,
  1108711,
  1108693,
  1119307,
  1118529,
  1108667,
  1119817,
  1108669,
  1108452,
  1108498,
  1127123,
  1122544,
  1120754,
  1122567,
  1122583,
  1108434,
  1119834,
  1119528,
  1119842,
  1108468,
  1108471,
  1108473,
  1119666,
  1108475,
  1108477,
  1108479,
  1108723,
  1119897,
  1108725,
  1119909,
  1108680,
  1119915,
  1108685,
  1108661,
  1108560,
  1108657,
  1108463,
  1108461,
  1108459,
  1108672,
  1122257,
  1119954,
  1119966,
  1119978,
  1121702,
  1121712,
  1121734],
 [0.221,
  1.14,
  2.186,
  2.559,
  3.336,
  4.003,
  4.578,
  5.324,
  6.627,
  7.201,
  7.819,
  9.898,
  10.796,
  11.178,
  11.848,
  12.113,
  13.022,
  13.372,
  14.416,
  14.856,
  15.23,
  15.698,
  16.001,
  16.666,
  17.23,
  17.572,
  18.05,
  18.346,
  18.822,
  19.156,
  20.611,
  21.366,
  21.973,
  22.85,
  23.466,
  24.118,
  25.739,
  26.201,
  26.621,
  27.794,
  28.355,
  30.891,
  31.136,
  31.517,
  31.775,
  32.324,
  32.663,
  33.539,
  34.169,
  35.108,
  36.136,
  37.255,
  38.44,
  39.059,
  39.685,
  40.483,
  41.385,
  42.548,
  43.159,
  43.643,
  44.559,
  45.293,
  46.158,
  46.955,
  47.823,
  49.108,
  49.948,
  50.568,
  51.293,
  52.266,
  53.158,
  54.292,
  54.858,
  55.858,
  56.858,
  60.429,
  62.419,
  70.878],
 ['N/O CMNO DE LA PLAZA',
  '5 SB @ Via de Ysidro',
  '5 SB @ Dairy Mart',
  'N/O DAIRY MART RD',
  '5 SB N/0 905',
  '5 SB @ Coronado Ave',
  '5 SB @ Palm Ave',
  '5 SB @ Main St',
  'SB 5 S/O L St',
  '5 SB @ J St',
  '5 SB N/O H St',
  'Bay Marina Dr',
  '5 SB  Civic Center',
  '5 SB N/O 8th St',
  ' N/O DIVISION',
  'SB I5 S/O I15',
  'SB 5 S/O 29th',
  ' N/O 28TH ST',
  'SB5 @ Imperial',
  'SB 5 @ SR 94',
  'SB 5 @ B ST',
  'SB5 @PARK BLVD',
  '5th Ave',
  'SB 5 @ Grape St',
  'KETTNER BLVD',
  'SB 5 N/O Pacific HWY',
  'HANCOCK ST',
  'SB5 N/O WASHINGTON',
  'OLD TOWN AVE',
  'SB 5 N/O OLD TOWN',
  'Seawrold Dr to 5SB',
  'S/O CLAIRMONT DR',
  'EB CLAIREMONT DR',
  'Mission Bay Dr',
  'SB5 @BALBOA AVE',
  '5 SB Mission Bay Dr',
  'La Jolla Pkwy to 5SB',
  'SB 5 N/O 52',
  'Gilman Dr',
  'Nobel Dr',
  'WB LA JOLLA VILLAGE',
  '5SB @ JCT 5/805',
  '5 SB N/O 5/805',
  'Carmel Mt. To SB 5',
  '5 SB Bypass',
  '5 SB S/O 56',
  'CARMEL VALLEY RD',
  'SB 5 S/O DEL MAR',
  'WB Del Mar Heights',
  'SB 5 SAN DIEGUITO',
  'WB VIA DE LA VALLE',
  'LOMAS SANTA FE DR',
  'MANCHESTER AVE',
  '5 S N/O VISTA VIEW',
  'BIRMINGHAM DR',
  'SANTA FE DR',
  'ENCINITAS BLVD',
  'Leucadia Blvd',
  'SB 5 N/O LEUCADIA',
  'La Costa Ave',
  'SB 5 N/O BATIQUITOS',
  'POINSETTIA LN',
  'SB 5 N/O POINSETTIA',
  'WB PALOMAR AIRPORT',
  'CANNON RD',
  'TAMARACK AVE',
  'CARLSBAD VILLAGE DR',
  'LAS FLORES DR',
  'CASSIDY ST',
  'Oceanside Blvd',
  'WB RTE 76/MISSION',
  'SB 5 @ HARBOR DR',
  'S5 N/O CAMP DEL MAR',
  'S/O SANTA MARGARITA',
  '.5 N/O STA MARGRITA',
  '5 SB N/O Rest Area',
  '5 SB  Las Pulgas Rd',
  '5 SB Basilone Rd'])

In [19]:
sorted_sensors.remove(1126864)
sorted_sensors.remove(1121715)
sorted_sensors.remove(1122560)
sorted_sensors.remove(1119877)
sorted_sensors.remove(1119997)

In [18]:
sidx_ref=df_sensors.index[df_sensors["Abs_PM"].argmax()]
print("Reference sensor:", sidx_ref)
ref_pm=df_sensors.loc[sidx_ref,'Abs_PM']
print("abs_pm of reference sensor:", ref_pm)

Reference sensor: 1070
abs_pm of reference sensor: 70.878

In [19]:
rel_sensor_pos = ref_pm - df_sensors["Abs_PM"]
rel_sensor_pos

701     70.657
871     69.738
873     68.692
719     68.319
876     67.542
         ...
985     15.020
987     14.020
1064    10.449
1066     8.459
1070     0.000
Name: Abs_PM, Length: 78, dtype: float64

In [20]:
rel_sensor_pos.sort_values()

1070     0.000
1066     8.459
1064    10.449
987     14.020
985     15.020
         ...
876     67.542
719     68.319
873     68.692
871     69.738
701     70.657
Name: Abs_PM, Length: 78, dtype: float64

In [21]:
import numpy as np 

rel_sensor_pos2 = rel_sensor_pos * 1609

In [26]:
import numpy as np
idx_sensor_pos = (rel_sensor_pos2 / 50).apply(np.round).astype(np.int)

C:\Users\STEPHE~1\AppData\Local\Temp/ipykernel_157612/3180229421.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  idx_sensor_pos = (rel_sensor_pos2 / 50).apply(np.round).astype(np.int)

In [27]:
idx_sensor_pos.values[::-1]

array([   0,  272,  336,  451,  483,  516,  534,  570,  599,  630,  654,
        674,  701,  742,  770,  795,  823,  847,  876,  892,  912,  949,
        978, 1004, 1024, 1044, 1082, 1118, 1151, 1181, 1202, 1230, 1241,
       1258, 1267, 1279, 1287, 1368, 1386, 1424, 1438, 1453, 1505, 1526,
       1546, 1574, 1593, 1618, 1664, 1675, 1690, 1700, 1715, 1726, 1745,
       1766, 1776, 1791, 1803, 1817, 1851, 1862, 1891, 1900, 1921, 1933,
       1962, 2029, 2049, 2068, 2110, 2134, 2152, 2174, 2199, 2211, 2244,
       2274])

In [37]:
idx_sensor_pos.to_json("5S_station_pos_idx_dx=%04dm.json" % int(0.3*1.e3))

In [31]:
rel_sensor_pos.sort_values().diff()

1070      NaN
1066    8.459
1064    1.990
987     3.571
985     1.000
        ...
876     0.667
719     0.777
873     0.373
871     1.046
701     0.919
Name: Abs_PM, Length: 80, dtype: float64

In [63]:
file = np.stack((sorted_name[::-1], idx_sensor_pos.values[::-1]))

In [67]:
import pandas as pd 

pd.DataFrame(file).to_csv("station_pos.csv")

In [27]:
1121740 in sorted_sensors

False

In [20]:
xi = sorted_abs_pm

In [21]:
xi0=xi[0]
for p in range(len(xi)):
    xi[p] = xi[p] - xi0

In [22]:
xi

[0.0,
 0.9189999999999999,
 1.9649999999999999,
 2.338,
 3.1149999999999998,
 3.782,
 4.357,
 5.103,
 5.103,
 6.406,
 6.9799999999999995,
 7.598,
 9.677,
 10.575,
 10.957,
 11.627,
 11.892,
 12.801,
 13.151,
 14.195,
 14.635,
 15.009,
 15.477,
 15.780000000000001,
 16.445,
 17.009,
 17.011,
 17.351,
 17.829,
 18.125,
 18.601,
 18.935,
 20.39,
 21.145,
 21.752,
 22.629,
 23.245,
 23.897,
 25.518,
 25.98,
 26.4,
 27.573,
 28.134,
 30.669999999999998,
 30.915,
 31.296,
 31.554,
 32.103,
 32.442,
 33.318000000000005,
 33.948,
 34.887,
 35.915000000000006,
 37.034000000000006,
 38.219,
 38.838,
 39.464000000000006,
 40.262,
 41.164,
 42.327000000000005,
 42.938,
 43.422000000000004,
 44.338,
 45.072,
 45.937000000000005,
 46.734,
 47.602000000000004,
 48.887,
 49.727000000000004,
 50.347,
 51.072,
 52.045,
 52.937000000000005,
 54.071000000000005,
 54.637,
 55.637,
 56.637,
 60.208000000000006,
 62.198,
 70.657]

In [17]:
sorted_abs_pm

[0.221,
 1.14,
 2.186,
 2.559,
 3.336,
 4.003,
 4.578,
 5.324,
 5.324,
 6.627,
 7.201,
 7.819,
 9.898,
 10.796,
 11.178,
 11.848,
 12.113,
 13.022,
 13.372,
 14.416,
 14.856,
 15.23,
 15.698,
 16.001,
 16.666,
 17.23,
 17.232,
 17.572,
 18.05,
 18.346,
 18.822,
 19.156,
 20.611,
 21.366,
 21.973,
 22.85,
 23.466,
 24.118,
 25.739,
 26.201,
 26.621,
 27.794,
 28.355,
 30.891,
 31.136,
 31.517,
 31.775,
 32.324,
 32.663,
 33.539,
 34.169,
 35.108,
 36.136,
 37.255,
 38.44,
 39.059,
 39.685,
 40.483,
 41.385,
 42.548,
 43.159,
 43.643,
 44.559,
 45.293,
 46.158,
 46.955,
 47.823,
 49.108,
 49.948,
 50.568,
 51.293,
 52.266,
 53.158,
 54.292,
 54.858,
 55.858,
 56.858,
 60.429,
 62.419,
 70.878]

In [9]:
sorted_sensors

[1114228,
 1118326,
 1118341,
 1114721,
 1118365,
 1118372,
 1118379,
 1123134,
 1118695,
 1120356,
 1118413,
 1118428,
 1114240,
 1118465,
 1118472,
 1114254,
 1118076,
 1126864,
 1117755,
 1114268,
 1117774,
 1117789,
 1117810,
 1117683,
 1108417,
 1117734,
 1108605,
 1118702,
 1117724,
 1108609,
 1117871,
 1108615,
 1117818,
 1126426,
 1114806,
 1108711,
 1108693,
 1119307,
 1118529,
 1108667,
 1119817,
 1108669,
 1108452,
 1108498,
 1127123,
 1122544,
 1120754,
 1122560,
 1122567,
 1122583,
 1108434,
 1119834,
 1119528,
 1119842,
 1108468,
 1108471,
 1108473,
 1119666,
 1108475,
 1108477,
 1108479,
 1119877,
 1108723,
 1119897,
 1108725,
 1119909,
 1108680,
 1119915,
 1108685,
 1108661,
 1108560,
 1108657,
 1108463,
 1108461,
 1108459,
 1108672,
 1122257,
 1119954,
 1119966,
 1119978,
 1119997,
 1121702,
 1121712,
 1121715,
 1121734]

In [10]:
sorted_sensors.remove(1126864)
sorted_sensors.remove(1121715)
sorted_sensors.remove(1122560)
sorted_sensors.remove(1119877)
sorted_sensors.remove(1119997)

In [10]:
sensors.remove(1126864)
sensors.remove(1121715)
sensors.remove(1122560)
sensors.remove(1119877)
sensors.remove(1119997)

In [ ]:
1122560, 1119877, 1119997, 1126864, 1121715

In [96]:
sorted_sensors

[1121734,
 1121712,
 1121702,
 1119978,
 1119966,
 1119954,
 1122257,
 1108672,
 1108459,
 1108461,
 1108463,
 1108657,
 1108560,
 1108661,
 1108685,
 1119915,
 1108680,
 1119909,
 1108725,
 1119897,
 1108723,
 1108479,
 1108477,
 1108475,
 1119666,
 1108473,
 1108471,
 1108468,
 1119842,
 1119528,
 1119834,
 1108434,
 1122583,
 1122567,
 1120754,
 1122544,
 1127123,
 1108498,
 1108452,
 1108669,
 1119817,
 1108667,
 1118529,
 1119307,
 1108693,
 1108711,
 1114806,
 1126426,
 1117818,
 1108615,
 1117871,
 1108609,
 1117724,
 1108605,
 1117734,
 1108417,
 1117683,
 1117810,
 1117789,
 1117774,
 1114268,
 1117755,
 1118076,
 1114254,
 1118472,
 1118465,
 1114240,
 1118428,
 1118413,
 1120356,
 1118695,
 1118379,
 1118372,
 1118365,
 1114721,
 1118341,
 1118326,
 1114228]

In [46]:
len(sensors)

320

In [47]:
sorted_sensors = sensors 
len(sorted_sensors), sorted_sensors

(320,
 array([400001, 400017, 400030, 400040, 400045, 400052, 400057, 400059,
        400065, 400069, 400073, 400084, 400085, 400088, 400096, 400097,
        400100, 400104, 400109, 400122, 400147, 400148, 400149, 400158,
        400160, 400168, 400172, 400174, 400178, 400185, 400201, 400206,
        400209, 400213, 400221, 400222, 400227, 400236, 400238, 400240,
        400246, 400253, 400257, 400258, 400268, 400274, 400278, 400280,
        400292, 400296, 400298, 400330, 400336, 400343, 400353, 400372,
        400394, 400400, 400414, 400418, 400429, 400435, 400436, 400440,
        400449, 400457, 400461, 400464, 400479, 400485, 400499, 400507,
        400508, 400514, 400519, 400528, 400545, 400560, 400563, 400567,
        400581, 400582, 400586, 400637, 400643, 400648, 400649, 400654,
        400664, 400665, 400668, 400673, 400677, 400687, 400688, 400690,
        400700, 400709, 400713, 400714, 400715, 400717, 400723, 400743,
        400750, 400760, 400772, 400790, 400792, 400794, 400799, 400804,
        400822, 400823, 400828, 400832, 400837, 400842, 400863, 400869,
        400873, 400895, 400904, 400907, 400911, 400916, 400922, 400934,
        400951, 400952, 400953, 400964, 400965, 400970, 400971, 400973,
        400995, 400996, 401014, 401129, 401154, 401163, 401167, 401210,
        401224, 401327, 401351, 401388, 401391, 401400, 401403, 401440,
        401457, 401464, 401489, 401495, 401507, 401534, 401541, 401555,
        401560, 401567, 401597, 401606, 401611, 401655, 401808, 401809,
        401810, 401811, 401816, 401817, 401845, 401846, 401890, 401891,
        401906, 401908, 401926, 401936, 401937, 401942, 401943, 401948,
        401957, 401958, 401994, 401996, 401997, 401998, 402056, 402057,
        402058, 402059, 402060, 402061, 402067, 402117, 402118, 402119,
        402120, 402121, 402281, 402282, 402283, 402284, 402285, 402286,
        402287, 402359, 402360, 402361, 402362, 402363, 402364, 402365,
        402366, 402367, 402370, 402371, 402372, 402373, 403225, 403265,
        403329, 403401, 403402, 403404, 403406, 403409, 403412, 403414,
        403419, 404370, 404434, 404435, 404444, 404451, 404452, 404453,
        404461, 404462, 404521, 404522, 404553, 404585, 404586, 404640,
        404753, 404759, 405613, 405619, 405701, 407150, 407151, 407152,
        407153, 407155, 407157, 407161, 407165, 407172, 407173, 407174,
        407176, 407177, 407179, 407180, 407181, 407184, 407185, 407186,
        407187, 407190, 407191, 407194, 407200, 407202, 407204, 407206,
        407207, 407321, 407323, 407325, 407328, 407331, 407332, 407335,
        407336, 407337, 407339, 407341, 407342, 407344, 407348, 407352,
        407359, 407360, 407361, 407364, 407367, 407370, 407372, 407373,
        407374, 407710, 407711, 408907, 408911, 409524, 409525, 409526,
        409528, 409529, 413026, 413845, 413877, 413878, 414284, 414694],
       dtype=int64))

In [48]:
col = ["Timestamp", "Station", "District", "Freeway", "Direction", 
       "Type", "Length", "Sample", "Observed Percentage", "Flow", "Avg Occupancy", "Avg Speed"]

### Data Processing

In [268]:
time_dict

{'00:00:00': 0,
 '00:05:00': 1,
 '00:10:00': 2,
 '00:15:00': 3,
 '00:20:00': 4,
 '00:25:00': 5,
 '00:30:00': 6,
 '00:35:00': 7,
 '00:40:00': 8,
 '00:45:00': 9,
 '00:50:00': 10,
 '00:55:00': 11,
 '01:00:00': 12,
 '01:05:00': 13,
 '01:10:00': 14,
 '01:15:00': 15,
 '01:20:00': 16,
 '01:25:00': 17,
 '01:30:00': 18,
 '01:35:00': 19,
 '01:40:00': 20,
 '01:45:00': 21,
 '01:50:00': 22,
 '01:55:00': 23,
 '02:00:00': 24,
 '02:05:00': 25,
 '02:10:00': 26,
 '02:15:00': 27,
 '02:20:00': 28,
 '02:25:00': 29,
 '02:30:00': 30,
 '02:35:00': 31,
 '02:40:00': 32,
 '02:45:00': 33,
 '02:50:00': 34,
 '02:55:00': 35,
 '03:00:00': 36,
 '03:05:00': 37,
 '03:10:00': 38,
 '03:15:00': 39,
 '03:20:00': 40,
 '03:25:00': 41,
 '03:30:00': 42,
 '03:35:00': 43,
 '03:40:00': 44,
 '03:45:00': 45,
 '03:50:00': 46,
 '03:55:00': 47,
 '04:00:00': 48,
 '04:05:00': 49,
 '04:10:00': 50,
 '04:15:00': 51,
 '04:20:00': 52,
 '04:25:00': 53,
 '04:30:00': 54,
 '04:35:00': 55,
 '04:40:00': 56,
 '04:45:00': 57,
 '04:50:00': 58,
 '04:55:00': 59,
 '05:00:00': 60,
 '05:05:00': 61,
 '05:10:00': 62,
 '05:15:00': 63,
 '05:20:00': 64,
 '05:25:00': 65,
 '05:30:00': 66,
 '05:35:00': 67,
 '05:40:00': 68,
 '05:45:00': 69,
 '05:50:00': 70,
 '05:55:00': 71,
 '06:00:00': 72,
 '06:05:00': 73,
 '06:10:00': 74,
 '06:15:00': 75,
 '06:20:00': 76,
 '06:25:00': 77,
 '06:30:00': 78,
 '06:35:00': 79,
 '06:40:00': 80,
 '06:45:00': 81,
 '06:50:00': 82,
 '06:55:00': 83,
 '07:00:00': 84,
 '07:05:00': 85,
 '07:10:00': 86,
 '07:15:00': 87,
 '07:20:00': 88,
 '07:25:00': 89,
 '07:30:00': 90,
 '07:35:00': 91,
 '07:40:00': 92,
 '07:45:00': 93,
 '07:50:00': 94,
 '07:55:00': 95,
 '08:00:00': 96,
 '08:05:00': 97,
 '08:10:00': 98,
 '08:15:00': 99,
 '08:20:00': 100,
 '08:25:00': 101,
 '08:30:00': 102,
 '08:35:00': 103,
 '08:40:00': 104,
 '08:45:00': 105,
 '08:50:00': 106,
 '08:55:00': 107,
 '09:00:00': 108,
 '09:05:00': 109,
 '09:10:00': 110,
 '09:15:00': 111,
 '09:20:00': 112,
 '09:25:00': 113,
 '09:30:00': 114,
 '09:35:00': 115,
 '09:40:00': 116,
 '09:45:00': 117,
 '09:50:00': 118,
 '09:55:00': 119,
 '10:00:00': 120,
 '10:05:00': 121,
 '10:10:00': 122,
 '10:15:00': 123,
 '10:20:00': 124,
 '10:25:00': 125,
 '10:30:00': 126,
 '10:35:00': 127,
 '10:40:00': 128,
 '10:45:00': 129,
 '10:50:00': 130,
 '10:55:00': 131,
 '11:00:00': 132,
 '11:05:00': 133,
 '11:10:00': 134,
 '11:15:00': 135,
 '11:20:00': 136,
 '11:25:00': 137,
 '11:30:00': 138,
 '11:35:00': 139,
 '11:40:00': 140,
 '11:45:00': 141,
 '11:50:00': 142,
 '11:55:00': 143,
 '12:00:00': 144,
 '12:05:00': 145,
 '12:10:00': 146,
 '12:15:00': 147,
 '12:20:00': 148,
 '12:25:00': 149,
 '12:30:00': 150,
 '12:35:00': 151,
 '12:40:00': 152,
 '12:45:00': 153,
 '12:50:00': 154,
 '12:55:00': 155,
 '13:00:00': 156,
 '13:05:00': 157,
 '13:10:00': 158,
 '13:15:00': 159,
 '13:20:00': 160,
 '13:25:00': 161,
 '13:30:00': 162,
 '13:35:00': 163,
 '13:40:00': 164,
 '13:45:00': 165,
 '13:50:00': 166,
 '13:55:00': 167,
 '14:00:00': 168,
 '14:05:00': 169,
 '14:10:00': 170,
 '14:15:00': 171,
 '14:20:00': 172,
 '14:25:00': 173,
 '14:30:00': 174,
 '14:35:00': 175,
 '14:40:00': 176,
 '14:45:00': 177,
 '14:50:00': 178,
 '14:55:00': 179,
 '15:00:00': 180,
 '15:05:00': 181,
 '15:10:00': 182,
 '15:15:00': 183,
 '15:20:00': 184,
 '15:25:00': 185,
 '15:30:00': 186,
 '15:35:00': 187,
 '15:40:00': 188,
 '15:45:00': 189,
 '15:50:00': 190,
 '15:55:00': 191,
 '16:00:00': 192,
 '16:05:00': 193,
 '16:10:00': 194,
 '16:15:00': 195,
 '16:20:00': 196,
 '16:25:00': 197,
 '16:30:00': 198,
 '16:35:00': 199,
 '16:40:00': 200,
 '16:45:00': 201,
 '16:50:00': 202,
 '16:55:00': 203,
 '17:00:00': 204,
 '17:05:00': 205,
 '17:10:00': 206,
 '17:15:00': 207,
 '17:20:00': 208,
 '17:25:00': 209,
 '17:30:00': 210,
 '17:35:00': 211,
 '17:40:00': 212,
 '17:45:00': 213,
 '17:50:00': 214,
 '17:55:00': 215,
 '18:00:00': 216,
 '18:05:00': 217,
 '18:10:00': 218,
 '18:15:00': 219,
 '18:20:00': 220,
 '18:25:00': 221,
 '18:30:00': 222,
 '18:35:00': 223,
 '18:40:00': 224,
 '18:45:00': 225,
 '18:50:00': 226,
 '18:55:00': 227,
 '19:00:00': 228,
 '19:05:00': 229,
 '19:10:00': 230,
 '19:15:00': 231,
 '19:20:00': 232,
 '19:25:00': 233,
 '19:30:00': 234,
 '19:35:00': 235,
 '19:40:00': 236,
 '19:45:00': 237,
 '19:50:00': 238,
 '19:55:00': 239,
 '20:00:00': 240,
 '20:05:00': 241,
 '20:10:00': 242,
 '20:15:00': 243,
 '20:20:00': 244,
 '20:25:00': 245,
 '20:30:00': 246,
 '20:35:00': 247,
 '20:40:00': 248,
 '20:45:00': 249,
 '20:50:00': 250,
 '20:55:00': 251,
 '21:00:00': 252,
 '21:05:00': 253,
 '21:10:00': 254,
 '21:15:00': 255,
 '21:20:00': 256,
 '21:25:00': 257,
 '21:30:00': 258,
 '21:35:00': 259,
 '21:40:00': 260,
 '21:45:00': 261,
 '21:50:00': 262,
 '21:55:00': 263,
 '22:00:00': 264,
 '22:05:00': 265,
 '22:10:00': 266,
 '22:15:00': 267,
 '22:20:00': 268,
 '22:25:00': 269,
 '22:30:00': 270,
 '22:35:00': 271,
 '22:40:00': 272,
 '22:45:00': 273,
 '22:50:00': 274,
 '22:55:00': 275,
 '23:00:00': 276,
 '23:05:00': 277,
 '23:10:00': 278,
 '23:15:00': 279,
 '23:20:00': 280,
 '23:25:00': 281,
 '23:30:00': 282,
 '23:35:00': 283,
 '23:40:00': 284,
 '23:45:00': 285,
 '23:50:00': 286,
 '23:55:00': 287}

In [270]:
def interpolate(var, ti, t): 
    IM_q=interp1d(np.array(ti), var[:, 0], bounds_error=False,
             fill_value=(var[0, 0], var[-1, 0]), kind='linear')
    IM_u=interp1d(np.array(ti), var[:, 1], bounds_error=False,
             fill_value=(var[0, 1], var[-1, 1]), kind='linear')
    u = IM_u(t)
    q = IM_q(t)
    boundary = np.stack((q, u), axis = 1) 
#     print(boundary.shape)
    return torch.tensor(boundary)

In [339]:
# script to extract Total_flow and Avg_speed for each sensor each day 
# PEMS data in 04/01 - 09/30 in 2021 03/16 - 09/16

import itertools 
import torch 

datas = []
for filename in os.listdir("caltrans/station_5min/2021/d4_plaintxt/"): 
    print(filename)
    if int(filename[-9:-7]) < 1 or int(filename[-9:-7]) > 6: 
        continue
#     if "d11_text_station_5min_2021_04_04.txt" in filename: 
#         continue
#     if "d11_text_station_5min_2021_06_17.txt" in filename: 
#         continue
#     if "d11_text_station_5min_2021_06_18.txt" in filename: 
#         continue
    filedata = pd.read_csv("caltrans/station_5min/2021/d4_plaintxt/" + filename, sep=",", usecols=range(12), names = col)       
    
    # filter out selected sensor ids
#     filedata = filedata[(filedata["Freeway"] == 5) & (filedata["Direction"] == "S") & (filedata["Type"] == "ML")]
    filedata = filedata[filedata["Station"].isin(sorted_sensors)]
    
    # sort dataframe given ids and timestamps
    if "d04_text_station_5min_2021_02_10.txt" in filename: 
        time = filedata["Timestamp"].unique().tolist()[:288] 
        filedata = filedata[filedata["Timestamp"].isin(time)]
        filedata["Timestamp"] = filedata["Timestamp"].str[-8:]
        filedata = filedata[filedata['Flow'].notna()]
        time = filedata["Timestamp"].unique().tolist() 
    else: 
        filedata["Timestamp"] = filedata["Timestamp"].str[-8:]
        filedata = filedata[filedata['Flow'].notna()]
        time = filedata["Timestamp"].unique().tolist() 
        
    
#     time = filedata["Timestamp"].unique().tolist() 
    pair = list(itertools.product(time, sorted_sensors))
    filedata["Station"] = filedata["Station"].astype("category")
    filedata["Timestamp"] = filedata["Timestamp"].astype("category")
    filedata["Station"].cat.set_categories(sorted_sensors, inplace=True)
    filedata["Timestamp"].cat.set_categories(time, inplace=True)
    filedata["Timestamp"].replace(time_dict, inplace=True)
    filedata = filedata.sort_values(["Station"])
    
    
    count = 0
    data_per_sample = []
    for i in sorted_sensors: 
        timesteps = (filedata["Station"] == i).sum() 
    #     print(timesteps)
        filedata.iloc[count : count + timesteps] = filedata.iloc[count : count + timesteps].sort_values(["Timestamp"]) 
        if timesteps < 288: 
            ti = filedata.iloc[count : count + timesteps]["Timestamp"].values
    #         print(ti)
            t=np.arange(0, 288, 1) 
    #         print(t)
            data = filedata.iloc[count : count + timesteps][["Flow", "Avg Speed"]].to_numpy()
            data = interpolate(data, ti, t)
    #         print(data.shape)
        else: 
            data = torch.tensor(filedata.iloc[count : count + timesteps][["Flow", "Avg Speed"]].to_numpy())

        data_per_sample.append(data)
    #     break
        count += timesteps 
        
    data = torch.stack(data_per_sample, axis = 1)
#     data = data.reshape(len(sorted_sensors), -1)
#     data = data.reshape(len(sorted_sensors), 288, 2) 
#     data = torch.tensor(data).permute(2, 1, 0)
    print(data.isnan().any())
    datas.append(data)
#     print(data.shape)

d04_text_station_5min_2021_01_01.txt

C:\Users\Stephen Ma\anaconda3\envs\env_pytorch\lib\site-packages\pandas\core\arrays\categorical.py:2631: FutureWarning: The `inplace` parameter in pandas.Categorical.set_categories is deprecated and will be removed in a future version. Removing unused categories will always return a new Categorical object.
  res = method(*args, **kwargs)

tensor(False)
d04_text_station_5min_2021_01_02.txt
tensor(False)
d04_text_station_5min_2021_01_03.txt
tensor(False)
d04_text_station_5min_2021_01_04.txt
tensor(False)
d04_text_station_5min_2021_01_05.txt
tensor(False)
d04_text_station_5min_2021_01_06.txt
tensor(False)
d04_text_station_5min_2021_01_07.txt
tensor(False)
d04_text_station_5min_2021_01_08.txt
tensor(False)
d04_text_station_5min_2021_01_09.txt
tensor(False)
d04_text_station_5min_2021_01_10.txt
tensor(False)
d04_text_station_5min_2021_01_11.txt
tensor(False)
d04_text_station_5min_2021_01_12.txt
tensor(False)
d04_text_station_5min_2021_01_13.txt
tensor(False)
d04_text_station_5min_2021_01_14.txt
tensor(False)
d04_text_station_5min_2021_01_15.txt
tensor(False)
d04_text_station_5min_2021_01_16.txt
tensor(False)
d04_text_station_5min_2021_01_17.txt
tensor(False)
d04_text_station_5min_2021_01_18.txt
tensor(False)
d04_text_station_5min_2021_01_19.txt
tensor(False)
d04_text_station_5min_2021_01_20.txt
tensor(False)
d04_text_station_5min_2021_01_21.txt
tensor(False)
d04_text_station_5min_2021_01_22.txt
tensor(False)
d04_text_station_5min_2021_01_23.txt
tensor(False)
d04_text_station_5min_2021_01_24.txt
tensor(False)
d04_text_station_5min_2021_01_25.txt
tensor(False)
d04_text_station_5min_2021_01_26.txt
tensor(False)
d04_text_station_5min_2021_01_27.txt
tensor(False)
d04_text_station_5min_2021_01_28.txt
tensor(False)
d04_text_station_5min_2021_01_29.txt
tensor(False)
d04_text_station_5min_2021_01_30.txt
tensor(False)
d04_text_station_5min_2021_01_31.txt
tensor(False)
d04_text_station_5min_2021_02_01.txt
tensor(False)
d04_text_station_5min_2021_02_02.txt
tensor(False)
d04_text_station_5min_2021_02_03.txt
tensor(False)
d04_text_station_5min_2021_02_04.txt
tensor(False)
d04_text_station_5min_2021_02_05.txt
tensor(False)
d04_text_station_5min_2021_02_06.txt
tensor(False)
d04_text_station_5min_2021_02_07.txt
tensor(False)
d04_text_station_5min_2021_02_08.txt
tensor(False)
d04_text_station_5min_2021_02_09.txt
tensor(False)
d04_text_station_5min_2021_02_10.txt
tensor(False)
d04_text_station_5min_2021_02_11.txt
tensor(False)
d04_text_station_5min_2021_02_12.txt
tensor(False)
d04_text_station_5min_2021_02_13.txt
tensor(False)
d04_text_station_5min_2021_02_14.txt
tensor(False)
d04_text_station_5min_2021_02_15.txt
tensor(False)
d04_text_station_5min_2021_02_16.txt
tensor(False)
d04_text_station_5min_2021_02_17.txt
tensor(False)
d04_text_station_5min_2021_02_18.txt
tensor(False)
d04_text_station_5min_2021_02_19.txt
tensor(False)
d04_text_station_5min_2021_02_20.txt
tensor(False)
d04_text_station_5min_2021_02_21.txt
tensor(False)
d04_text_station_5min_2021_02_22.txt
tensor(False)
d04_text_station_5min_2021_02_23.txt
tensor(False)
d04_text_station_5min_2021_02_24.txt
tensor(False)
d04_text_station_5min_2021_02_25.txt
tensor(False)
d04_text_station_5min_2021_02_26.txt
tensor(False)
d04_text_station_5min_2021_02_27.txt
tensor(False)
d04_text_station_5min_2021_02_28.txt
tensor(False)
d04_text_station_5min_2021_03_01.txt
tensor(False)
d04_text_station_5min_2021_03_02.txt
tensor(False)
d04_text_station_5min_2021_03_03.txt
tensor(False)
d04_text_station_5min_2021_03_04.txt
tensor(False)
d04_text_station_5min_2021_03_05.txt
tensor(False)
d04_text_station_5min_2021_03_06.txt
tensor(False)
d04_text_station_5min_2021_03_07.txt
tensor(False)
d04_text_station_5min_2021_03_08.txt
tensor(False)
d04_text_station_5min_2021_03_09.txt
tensor(False)
d04_text_station_5min_2021_03_10.txt
tensor(False)
d04_text_station_5min_2021_03_11.txt
tensor(False)
d04_text_station_5min_2021_03_12.txt
tensor(False)
d04_text_station_5min_2021_03_13.txt
tensor(False)
d04_text_station_5min_2021_03_14.txt
tensor(False)
d04_text_station_5min_2021_03_15.txt
tensor(False)
d04_text_station_5min_2021_03_16.txt
tensor(False)
d04_text_station_5min_2021_03_17.txt
tensor(False)
d04_text_station_5min_2021_03_18.txt
tensor(False)
d04_text_station_5min_2021_03_19.txt
tensor(False)
d04_text_station_5min_2021_03_20.txt
tensor(False)
d04_text_station_5min_2021_03_21.txt
tensor(False)
d04_text_station_5min_2021_03_22.txt
tensor(False)
d04_text_station_5min_2021_03_23.txt
tensor(False)
d04_text_station_5min_2021_03_24.txt
tensor(False)
d04_text_station_5min_2021_03_25.txt
tensor(False)
d04_text_station_5min_2021_03_26.txt
tensor(False)
d04_text_station_5min_2021_03_27.txt
tensor(False)
d04_text_station_5min_2021_03_28.txt
tensor(False)
d04_text_station_5min_2021_03_29.txt
tensor(False)
d04_text_station_5min_2021_03_30.txt
tensor(False)
d04_text_station_5min_2021_03_31.txt
tensor(False)
d04_text_station_5min_2021_04_01.txt
tensor(False)
d04_text_station_5min_2021_04_02.txt
tensor(False)
d04_text_station_5min_2021_04_03.txt
tensor(False)
d04_text_station_5min_2021_04_04.txt
tensor(False)
d04_text_station_5min_2021_04_05.txt
tensor(False)
d04_text_station_5min_2021_04_06.txt
tensor(False)
d04_text_station_5min_2021_04_07.txt
tensor(False)
d04_text_station_5min_2021_04_08.txt
tensor(False)
d04_text_station_5min_2021_04_09.txt
tensor(False)
d04_text_station_5min_2021_04_10.txt
tensor(False)
d04_text_station_5min_2021_04_11.txt
tensor(False)
d04_text_station_5min_2021_04_12.txt
tensor(False)
d04_text_station_5min_2021_04_13.txt
tensor(False)
d04_text_station_5min_2021_04_14.txt
tensor(False)
d04_text_station_5min_2021_04_15.txt
tensor(False)
d04_text_station_5min_2021_04_16.txt
tensor(False)
d04_text_station_5min_2021_04_17.txt
tensor(False)
d04_text_station_5min_2021_04_18.txt
tensor(False)
d04_text_station_5min_2021_04_19.txt
tensor(False)
d04_text_station_5min_2021_04_20.txt
tensor(False)
d04_text_station_5min_2021_04_21.txt
tensor(False)
d04_text_station_5min_2021_04_22.txt
tensor(False)
d04_text_station_5min_2021_04_23.txt
tensor(False)
d04_text_station_5min_2021_04_24.txt
tensor(False)
d04_text_station_5min_2021_04_25.txt
tensor(False)
d04_text_station_5min_2021_04_26.txt
tensor(False)
d04_text_station_5min_2021_04_27.txt
tensor(False)
d04_text_station_5min_2021_04_28.txt
tensor(False)
d04_text_station_5min_2021_04_29.txt
tensor(False)
d04_text_station_5min_2021_04_30.txt
tensor(False)
d04_text_station_5min_2021_05_01.txt
tensor(False)
d04_text_station_5min_2021_05_02.txt
tensor(False)
d04_text_station_5min_2021_05_03.txt
tensor(False)
d04_text_station_5min_2021_05_04.txt
tensor(False)
d04_text_station_5min_2021_05_05.txt
tensor(False)
d04_text_station_5min_2021_05_06.txt
tensor(False)
d04_text_station_5min_2021_05_07.txt
tensor(False)
d04_text_station_5min_2021_05_08.txt
tensor(False)
d04_text_station_5min_2021_05_09.txt
tensor(False)
d04_text_station_5min_2021_05_10.txt
tensor(False)
d04_text_station_5min_2021_05_11.txt
tensor(False)
d04_text_station_5min_2021_05_12.txt
tensor(False)
d04_text_station_5min_2021_05_13.txt
tensor(False)
d04_text_station_5min_2021_05_14.txt
tensor(False)
d04_text_station_5min_2021_05_15.txt
tensor(False)
d04_text_station_5min_2021_05_16.txt
tensor(False)
d04_text_station_5min_2021_05_17.txt
tensor(False)
d04_text_station_5min_2021_05_18.txt
tensor(False)
d04_text_station_5min_2021_05_19.txt
tensor(False)
d04_text_station_5min_2021_05_20.txt
tensor(False)
d04_text_station_5min_2021_05_21.txt
tensor(False)
d04_text_station_5min_2021_05_22.txt
tensor(False)
d04_text_station_5min_2021_05_23.txt
tensor(False)
d04_text_station_5min_2021_05_24.txt
tensor(False)
d04_text_station_5min_2021_05_25.txt
tensor(False)
d04_text_station_5min_2021_05_26.txt
tensor(False)
d04_text_station_5min_2021_05_27.txt
tensor(False)
d04_text_station_5min_2021_05_28.txt
tensor(False)
d04_text_station_5min_2021_05_29.txt
tensor(False)
d04_text_station_5min_2021_05_30.txt
tensor(False)
d04_text_station_5min_2021_05_31.txt
tensor(False)
d04_text_station_5min_2021_06_01.txt
tensor(False)
d04_text_station_5min_2021_06_02.txt
tensor(False)
d04_text_station_5min_2021_06_03.txt
tensor(False)
d04_text_station_5min_2021_06_04.txt
tensor(False)
d04_text_station_5min_2021_06_05.txt
tensor(False)
d04_text_station_5min_2021_06_06.txt
tensor(False)
d04_text_station_5min_2021_06_07.txt
tensor(False)
d04_text_station_5min_2021_06_08.txt
tensor(False)
d04_text_station_5min_2021_06_09.txt
tensor(False)
d04_text_station_5min_2021_06_10.txt
tensor(False)
d04_text_station_5min_2021_06_11.txt

tensor(False)
d04_text_station_5min_2021_06_12.txt
tensor(False)
d04_text_station_5min_2021_06_13.txt
tensor(False)
d04_text_station_5min_2021_06_14.txt
tensor(False)
d04_text_station_5min_2021_06_15.txt
tensor(False)
d04_text_station_5min_2021_06_16.txt
tensor(False)
d04_text_station_5min_2021_06_17.txt
tensor(False)
d04_text_station_5min_2021_06_18.txt
tensor(False)
d04_text_station_5min_2021_06_19.txt
tensor(False)
d04_text_station_5min_2021_06_20.txt
tensor(False)
d04_text_station_5min_2021_06_21.txt
tensor(False)
d04_text_station_5min_2021_06_22.txt
tensor(False)
d04_text_station_5min_2021_06_23.txt
tensor(False)
d04_text_station_5min_2021_06_24.txt
tensor(False)
d04_text_station_5min_2021_06_25.txt
tensor(False)
d04_text_station_5min_2021_06_26.txt
tensor(False)
d04_text_station_5min_2021_06_27.txt
tensor(False)
d04_text_station_5min_2021_06_28.txt
tensor(False)
d04_text_station_5min_2021_06_29.txt
tensor(False)
d04_text_station_5min_2021_06_30.txt
tensor(False)
d04_text_station_5min_2021_07_01.txt
d04_text_station_5min_2021_07_02.txt
d04_text_station_5min_2021_07_03.txt
d04_text_station_5min_2021_07_04.txt
d04_text_station_5min_2021_07_05.txt
d04_text_station_5min_2021_07_06.txt
d04_text_station_5min_2021_07_07.txt
d04_text_station_5min_2021_07_08.txt
d04_text_station_5min_2021_07_09.txt
d04_text_station_5min_2021_07_10.txt
d04_text_station_5min_2021_07_11.txt
d04_text_station_5min_2021_07_12.txt
d04_text_station_5min_2021_07_13.txt
d04_text_station_5min_2021_07_14.txt
d04_text_station_5min_2021_07_15.txt
d04_text_station_5min_2021_07_16.txt
d04_text_station_5min_2021_07_17.txt
d04_text_station_5min_2021_07_18.txt
d04_text_station_5min_2021_07_19.txt
d04_text_station_5min_2021_07_20.txt
d04_text_station_5min_2021_07_21.txt
d04_text_station_5min_2021_07_22.txt
d04_text_station_5min_2021_07_23.txt
d04_text_station_5min_2021_07_24.txt
d04_text_station_5min_2021_07_25.txt
d04_text_station_5min_2021_07_26.txt
d04_text_station_5min_2021_07_27.txt
d04_text_station_5min_2021_07_28.txt
d04_text_station_5min_2021_07_29.txt
d04_text_station_5min_2021_07_30.txt
d04_text_station_5min_2021_07_31.txt
d04_text_station_5min_2021_08_01.txt
d04_text_station_5min_2021_08_02.txt
d04_text_station_5min_2021_08_03.txt
d04_text_station_5min_2021_08_04.txt
d04_text_station_5min_2021_08_05.txt
d04_text_station_5min_2021_08_06.txt
d04_text_station_5min_2021_08_07.txt
d04_text_station_5min_2021_08_08.txt
d04_text_station_5min_2021_08_09.txt
d04_text_station_5min_2021_08_10.txt
d04_text_station_5min_2021_08_11.txt
d04_text_station_5min_2021_08_12.txt
d04_text_station_5min_2021_08_13.txt
d04_text_station_5min_2021_08_14.txt
d04_text_station_5min_2021_08_15.txt
d04_text_station_5min_2021_08_16.txt
d04_text_station_5min_2021_08_17.txt
d04_text_station_5min_2021_08_18.txt
d04_text_station_5min_2021_08_19.txt
d04_text_station_5min_2021_08_20.txt
d04_text_station_5min_2021_08_21.txt
d04_text_station_5min_2021_08_22.txt
d04_text_station_5min_2021_08_23.txt
d04_text_station_5min_2021_08_24.txt
d04_text_station_5min_2021_08_25.txt
d04_text_station_5min_2021_08_26.txt
d04_text_station_5min_2021_08_27.txt
d04_text_station_5min_2021_08_28.txt
d04_text_station_5min_2021_08_29.txt
d04_text_station_5min_2021_08_30.txt
d04_text_station_5min_2021_08_31.txt
d04_text_station_5min_2021_09_01.txt
d04_text_station_5min_2021_09_02.txt
d04_text_station_5min_2021_09_03.txt
d04_text_station_5min_2021_09_04.txt
d04_text_station_5min_2021_09_05.txt
d04_text_station_5min_2021_09_06.txt
d04_text_station_5min_2021_09_07.txt
d04_text_station_5min_2021_09_08.txt
d04_text_station_5min_2021_09_09.txt
d04_text_station_5min_2021_09_10.txt
d04_text_station_5min_2021_09_11.txt
d04_text_station_5min_2021_09_12.txt
d04_text_station_5min_2021_09_13.txt
d04_text_station_5min_2021_09_14.txt
d04_text_station_5min_2021_09_15.txt
d04_text_station_5min_2021_09_16.txt
d04_text_station_5min_2021_09_17.txt
d04_text_station_5min_2021_09_18.txt
d04_text_station_5min_2021_09_19.txt
d04_text_station_5min_2021_09_20.txt
d04_text_station_5min_2021_09_21.txt
d04_text_station_5min_2021_09_22.txt
d04_text_station_5min_2021_09_23.txt
d04_text_station_5min_2021_09_24.txt
d04_text_station_5min_2021_09_25.txt
d04_text_station_5min_2021_09_26.txt
d04_text_station_5min_2021_09_27.txt
d04_text_station_5min_2021_09_28.txt
d04_text_station_5min_2021_09_29.txt
d04_text_station_5min_2021_09_30.txt
d04_text_station_5min_2021_10_01.txt
d04_text_station_5min_2021_10_02.txt
d04_text_station_5min_2021_10_03.txt
d04_text_station_5min_2021_10_04.txt
d04_text_station_5min_2021_10_05.txt
d04_text_station_5min_2021_10_06.txt
d04_text_station_5min_2021_10_07.txt
d04_text_station_5min_2021_10_08.txt
d04_text_station_5min_2021_10_09.txt
d04_text_station_5min_2021_10_10.txt
d04_text_station_5min_2021_10_11.txt
d04_text_station_5min_2021_10_12.txt
d04_text_station_5min_2021_10_13.txt
d04_text_station_5min_2021_10_14.txt
d04_text_station_5min_2021_10_15.txt
d04_text_station_5min_2021_10_16.txt
d04_text_station_5min_2021_10_17.txt
d04_text_station_5min_2021_10_18.txt
d04_text_station_5min_2021_10_19.txt
d04_text_station_5min_2021_10_20.txt
d04_text_station_5min_2021_10_21.txt
d04_text_station_5min_2021_10_22.txt
d04_text_station_5min_2021_10_23.txt
d04_text_station_5min_2021_10_24.txt
d04_text_station_5min_2021_10_25.txt
d04_text_station_5min_2021_10_26.txt
d04_text_station_5min_2021_10_27.txt
d04_text_station_5min_2021_10_28.txt
d04_text_station_5min_2021_10_29.txt
d04_text_station_5min_2021_10_30.txt
d04_text_station_5min_2021_10_31.txt
d04_text_station_5min_2021_11_01.txt
d04_text_station_5min_2021_11_02.txt
d04_text_station_5min_2021_11_03.txt
d04_text_station_5min_2021_11_04.txt
d04_text_station_5min_2021_11_05.txt
d04_text_station_5min_2021_11_06.txt
d04_text_station_5min_2021_11_07.txt
d04_text_station_5min_2021_11_08.txt
d04_text_station_5min_2021_11_09.txt
d04_text_station_5min_2021_11_10.txt
d04_text_station_5min_2021_11_11.txt
d04_text_station_5min_2021_11_12.txt
d04_text_station_5min_2021_11_13.txt
d04_text_station_5min_2021_11_14.txt
d04_text_station_5min_2021_11_15.txt
d04_text_station_5min_2021_11_16.txt
d04_text_station_5min_2021_11_17.txt
d04_text_station_5min_2021_11_18.txt
d04_text_station_5min_2021_11_19.txt
d04_text_station_5min_2021_11_20.txt
d04_text_station_5min_2021_11_21.txt
d04_text_station_5min_2021_11_22.txt
d04_text_station_5min_2021_11_23.txt
d04_text_station_5min_2021_11_24.txt
d04_text_station_5min_2021_11_25.txt
d04_text_station_5min_2021_11_26.txt
d04_text_station_5min_2021_11_27.txt
d04_text_station_5min_2021_11_28.txt
d04_text_station_5min_2021_11_29.txt
d04_text_station_5min_2021_11_30.txt
d04_text_station_5min_2021_12_01.txt
d04_text_station_5min_2021_12_02.txt
d04_text_station_5min_2021_12_03.txt
d04_text_station_5min_2021_12_04.txt
d04_text_station_5min_2021_12_05.txt
d04_text_station_5min_2021_12_06.txt
d04_text_station_5min_2021_12_07.txt
d04_text_station_5min_2021_12_08.txt
d04_text_station_5min_2021_12_09.txt
d04_text_station_5min_2021_12_10.txt
d04_text_station_5min_2021_12_11.txt
d04_text_station_5min_2021_12_12.txt
d04_text_station_5min_2021_12_13.txt
d04_text_station_5min_2021_12_14.txt
d04_text_station_5min_2021_12_15.txt
d04_text_station_5min_2021_12_16.txt
d04_text_station_5min_2021_12_17.txt
d04_text_station_5min_2021_12_18.txt
d04_text_station_5min_2021_12_19.txt
d04_text_station_5min_2021_12_20.txt
d04_text_station_5min_2021_12_21.txt
d04_text_station_5min_2021_12_22.txt
d04_text_station_5min_2021_12_23.txt
d04_text_station_5min_2021_12_24.txt
d04_text_station_5min_2021_12_25.txt
d04_text_station_5min_2021_12_26.txt
d04_text_station_5min_2021_12_27.txt
d04_text_station_5min_2021_12_28.txt
d04_text_station_5min_2021_12_29.txt
d04_text_station_5min_2021_12_30.txt
d04_text_station_5min_2021_12_31.txt

In [ ]:
datas

In [156]:
# # script to extract Total_flow and Avg_speed for each sensor each day 
# # PEMS data in 04/01 - 09/30 in 2021 03/16 - 09/16

# import itertools 
# import torch 

# datas = []
# for filename in os.listdir("caltrans/station_5min/2021/d4_plaintxt/"): 
#     print(filename)
#     if int(filename[-9:-7]) < 1 or int(filename[-9:-7]) > 12: 
#         continue
# #     if "d11_text_station_5min_2021_04_04.txt" in filename: 
# #         continue
# #     if "d11_text_station_5min_2021_06_17.txt" in filename: 
# #         continue
# #     if "d11_text_station_5min_2021_06_18.txt" in filename: 
# #         continue
#     filedata = pd.read_csv("caltrans/station_5min/2021/d4_plaintxt/" + filename, sep=",", usecols=range(12), names = col)       
    
#     # filter out selected sensor ids
# #     filedata = filedata[(filedata["Freeway"] == 5) & (filedata["Direction"] == "S") & (filedata["Type"] == "ML")]
#     filedata = filedata[filedata["Station"].isin(sorted_sensors)]
    
#     # sort dataframe given ids and timestamps
#     if "d11_text_station_5min_2021_09_14.txt" in filename: 
#         time = filedata["Timestamp"].unique().tolist()[:288] 
#         filedata = filedata[filedata["Timestamp"].isin(time)]
#     else: 
#         time = filedata["Timestamp"].unique().tolist() 
        
#     pair = list(itertools.product(time, sorted_sensors))
#     filedata["Station"] = filedata["Station"].astype("category")
#     filedata["Timestamp"] = filedata["Timestamp"].astype("category")
#     filedata["Station"].cat.set_categories(sorted_sensors, inplace=True)
#     filedata["Timestamp"].cat.set_categories(time, inplace=True)
#     filedata = filedata.sort_values(["Station"])
#     for i in range(1, len(sorted_sensors) + 1): 
#         filedata.iloc[288 * (i - 1) : 288 * i] = filedata.iloc[288 * (i - 1) : 288 * i].sort_values(["Timestamp"])
# #         print("work")
        
#     data = filedata[["Flow", "Avg Speed"]].to_numpy()
#     data = data.reshape(len(sorted_sensors), -1)
#     data = data.reshape(len(sorted_sensors), 288, 2) 
#     data = torch.tensor(data).permute(2, 1, 0)
#     print(data.isnan().any())
#     datas.append(data)
# #     print(data.shape)

d04_text_station_5min_2021_01_01.txt

C:\Users\Stephen Ma\anaconda3\envs\env_pytorch\lib\site-packages\pandas\core\arrays\categorical.py:2631: FutureWarning: The `inplace` parameter in pandas.Categorical.set_categories is deprecated and will be removed in a future version. Removing unused categories will always return a new Categorical object.
  res = method(*args, **kwargs)

tensor(False)
d04_text_station_5min_2021_01_02.txt
tensor(False)
d04_text_station_5min_2021_01_03.txt
tensor(False)
d04_text_station_5min_2021_01_04.txt
tensor(False)
d04_text_station_5min_2021_01_05.txt
tensor(False)
d04_text_station_5min_2021_01_06.txt
tensor(False)
d04_text_station_5min_2021_01_07.txt
tensor(False)
d04_text_station_5min_2021_01_08.txt
tensor(False)
d04_text_station_5min_2021_01_09.txt
tensor(False)
d04_text_station_5min_2021_01_10.txt
tensor(False)
d04_text_station_5min_2021_01_11.txt
tensor(False)
d04_text_station_5min_2021_01_12.txt
tensor(False)
d04_text_station_5min_2021_01_13.txt
tensor(False)
d04_text_station_5min_2021_01_14.txt

ValueError: cannot set using a slice indexer with a different length than the value

In [340]:
datas = torch.cat(datas, dim = 0)

In [302]:
for d in datas: 
    print(d.isnan().any())

AttributeError: 'int' object has no attribute 'isnan'

In [341]:
# datas[-14][1].isnan().any()
len(datas)

52128

In [342]:
datas = datas.permute(2, 0, 1)
datas.shape

torch.Size([2, 52128, 320])

In [343]:
# flow data (veh/s)

flow = datas[0, :, :] / 300

In [344]:
# speed data (m/s)

speed = datas[1, :, :] * 0.44704

In [345]:
# calculate density data (veh/m) 

density = flow / speed

In [346]:
traffic_data = torch.stack((density, flow, speed))

In [347]:
traffic_data.shape

torch.Size([3, 52128, 320])

In [348]:
torch.save(traffic_data, "pems_bay.pt")

In [44]:
density.mean()

tensor(0.0346, dtype=torch.float64)

In [45]:
density.min()

tensor(0., dtype=torch.float64)

In [46]:
density.max()

tensor(0.5707, dtype=torch.float64)

In [212]:
speed.isnan().any()

tensor(True)

In [31]:
flow[0]

tensor([0.1033, 0.0467, 0.0600, 0.0767, 0.0733, 0.1333, 0.2533, 0.0067, 0.3367,
        0.1200, 0.1967, 0.1667, 0.2067, 0.3200, 0.1833, 0.3767, 0.1633, 0.2000,
        0.2100, 0.1467, 0.2233, 1.5867, 0.2467, 0.2667, 0.1533, 0.1833, 0.2233,
        0.0467, 0.1200, 0.1300, 0.1133, 0.1400, 0.1200, 0.1600, 0.1467, 0.1500,
        0.0967, 0.1233, 0.0700, 0.0800, 0.1267, 0.0833, 0.0667, 0.0467, 0.1700,
        0.0100, 0.0100, 0.1267, 0.1567, 0.1600, 0.1600, 0.1800, 0.3067, 0.2700,
        0.1567, 0.1767, 0.2400, 0.1933, 0.1733, 0.1933, 0.3167, 0.3500, 0.4367,
        0.2267, 0.2400, 0.1167, 0.1133, 0.1000, 0.1000, 0.1100, 0.1467, 0.2267,
        0.1200, 0.1233, 0.1267, 0.1367, 0.1467, 0.1500, 0.1767, 0.2033],
       dtype=torch.float64)

In [34]:
flow[10]

tensor([0.0700, 0.0433, 0.0367, 0.0633, 0.0633, 0.0900, 0.2433, 0.0100, 0.3033,
        0.0933, 0.1633, 0.1367, 0.1900, 0.1767, 0.1633, 0.2333, 0.0800, 0.0933,
        0.1000, 0.0933, 0.1067, 1.3467, 0.1133, 0.1567, 0.0900, 0.0800, 0.0900,
        0.0300, 0.0567, 0.0633, 0.0967, 0.1200, 0.0833, 0.1067, 0.0800, 0.1167,
        0.0600, 0.0933, 0.0867, 0.0600, 0.1333, 0.0733, 0.0567, 0.0233, 0.1167,
        0.0167, 0.0167, 0.0767, 0.1067, 0.1133, 0.1233, 0.1633, 0.2100, 0.2100,
        0.0967, 0.0967, 0.1600, 0.0733, 0.0733, 0.1000, 0.1967, 0.2333, 0.3233,
        0.2067, 0.2567, 0.1333, 0.1067, 0.1033, 0.1000, 0.1167, 0.1100, 0.1200,
        0.1067, 0.1167, 0.1267, 0.1200, 0.1433, 0.0800, 0.1600, 0.1300],
       dtype=torch.float64)

In [41]:
flow.min()

tensor(0., dtype=torch.float64)

In [40]:
speed.max()

tensor(37.9090, dtype=torch.float64)

### Fix missing data

In [333]:
file1 = pd.read_csv("caltrans/station_5min/2021/d4_plaintxt/d04_text_station_5min_2021_03_28.txt", sep=",", usecols=range(12), names = col)
# file2 = pd.read_csv("caltrans/station_5min/2017/d11_plaintxt/d11_text_station_5min_2017_01_02.txt", sep=",", usecols=range(12), header = None)

In [334]:
file1

,Timestamp,Station,District,Freeway,Direction,Type,Length,Sample,Observed Percentage,Flow,Avg Occupancy,Avg Speed
0,03/28/2021 00:00:00,400000,4,101,S,ML,0.415,39,100,65.0,0.0102,68.7
1,03/28/2021 00:00:00,400001,4,101,N,ML,0.265,50,100,74.0,0.0116,70.9
2,03/28/2021 00:00:00,400002,4,101,S,ML,0.310,50,0,187.0,0.0295,69.9
3,03/28/2021 00:00:00,400006,4,880,S,ML,0.340,40,0,145.0,0.0277,66.1
4,03/28/2021 00:00:00,400007,4,101,N,ML,0.365,50,0,278.0,0.0472,54.3
...,...,...,...,...,...,...,...,...,...,...,...,...
1140475,03/28/2021 23:55:00,426315,4,101,N,ML,0.175,40,0,142.0,0.0208,68.9
1140476,03/28/2021 23:55:00,426316,4,101,N,FR,NaN,10,0,NaN,NaN,NaN
1140477,03/28/2021 23:55:00,426317,4,101,N,OR,NaN,10,0,NaN,NaN,NaN
1140478,03/28/2021 23:55:00,426318,4,101,N,OR,NaN,20,0,NaN,NaN,NaN
1140479,03/28/2021 23:55:00,426340,4,101,N,ML,0.300,39,75,36.0,0.0087,68.9

In [335]:
# deal with errnous data on date 02/10/2021 

# file1 = file1[(file1["Freeway"] == 5) & (file1["Direction"] == "S") & (file1["Type"] == "ML")]
file1 = file1[file1["Station"].isin(sorted_sensors)] 
file1 = file1[file1['Flow'].notna()]

In [336]:
file1

,Timestamp,Station,District,Freeway,Direction,Type,Length,Sample,Observed Percentage,Flow,Avg Occupancy,Avg Speed
1,03/28/2021 00:00:00,400001,4,101,N,ML,0.265,50,100,74.0,0.0116,70.9
9,03/28/2021 00:00:00,400017,4,85,S,ML,0.430,40,0,105.0,0.0233,62.4
14,03/28/2021 00:00:00,400030,4,880,S,ML,0.250,40,100,74.0,0.0136,68.6
19,03/28/2021 00:00:00,400040,4,87,S,ML,0.440,30,100,70.0,0.0161,66.8
23,03/28/2021 00:00:00,400045,4,880,N,ML,0.300,40,0,135.0,0.0330,62.5
...,...,...,...,...,...,...,...,...,...,...,...,...
1139936,03/28/2021 23:55:00,413845,4,237,W,ML,2.631,40,75,53.0,0.0120,65.1
1139942,03/28/2021 23:55:00,413877,4,280,N,ML,0.530,50,100,68.0,0.0064,70.2
1139943,03/28/2021 23:55:00,413878,4,280,N,ML,0.360,40,75,62.0,0.0105,68.6
1140007,03/28/2021 23:55:00,414284,4,280,N,ML,0.265,48,100,49.0,0.0062,71.4
1140027,03/28/2021 23:55:00,414694,4,280,N,ML,0.750,40,100,57.0,0.0094,68.0

In [337]:
filedata = file1

In [328]:
for i in range(1, len(sorted_sensors) + 1): 
        filedata.iloc[288 * (i - 1) : 288 * i] = filedata.iloc[288 * (i - 1) : 288 * i].sort_values(["Timestamp"])
        d = filedata.iloc[288 * (i - 1) : 288 * i][["Flow", "Avg Speed"]].to_numpy()
        if np.isnan(d).any(): 
#             print(filedata.iloc[288 * (i - 1) : 288 * i]["Station"].unique())
#             print(np.count_nonzero(np.isnan(d)))
#             print(list(map(tuple, np.where(np.isnan(d)))))
            filedata.iloc[288 * (i - 1) : 288 * i]
#         print("work")

In [332]:
filedata.iloc[288 * (1) : 288 * 2].to_csv("temp1.csv")

In [285]:
import itertools 
import torch

In [232]:
time_dict = {}
count = 0
for t in time: 
    time_dict[t] = count
    count += 1
time_dict

{'00:00:00': 0,
 '00:05:00': 1,
 '00:10:00': 2,
 '00:15:00': 3,
 '00:20:00': 4,
 '00:25:00': 5,
 '00:30:00': 6,
 '00:35:00': 7,
 '00:40:00': 8,
 '00:45:00': 9,
 '00:50:00': 10,
 '00:55:00': 11,
 '01:00:00': 12,
 '01:05:00': 13,
 '01:10:00': 14,
 '01:15:00': 15,
 '01:20:00': 16,
 '01:25:00': 17,
 '01:30:00': 18,
 '01:35:00': 19,
 '01:40:00': 20,
 '01:45:00': 21,
 '01:50:00': 22,
 '01:55:00': 23,
 '02:00:00': 24,
 '02:05:00': 25,
 '02:10:00': 26,
 '02:15:00': 27,
 '02:20:00': 28,
 '02:25:00': 29,
 '02:30:00': 30,
 '02:35:00': 31,
 '02:40:00': 32,
 '02:45:00': 33,
 '02:50:00': 34,
 '02:55:00': 35,
 '03:00:00': 36,
 '03:05:00': 37,
 '03:10:00': 38,
 '03:15:00': 39,
 '03:20:00': 40,
 '03:25:00': 41,
 '03:30:00': 42,
 '03:35:00': 43,
 '03:40:00': 44,
 '03:45:00': 45,
 '03:50:00': 46,
 '03:55:00': 47,
 '04:00:00': 48,
 '04:05:00': 49,
 '04:10:00': 50,
 '04:15:00': 51,
 '04:20:00': 52,
 '04:25:00': 53,
 '04:30:00': 54,
 '04:35:00': 55,
 '04:40:00': 56,
 '04:45:00': 57,
 '04:50:00': 58,
 '04:55:00': 59,
 '05:00:00': 60,
 '05:05:00': 61,
 '05:10:00': 62,
 '05:15:00': 63,
 '05:20:00': 64,
 '05:25:00': 65,
 '05:30:00': 66,
 '05:35:00': 67,
 '05:40:00': 68,
 '05:45:00': 69,
 '05:50:00': 70,
 '05:55:00': 71,
 '06:00:00': 72,
 '06:05:00': 73,
 '06:10:00': 74,
 '06:15:00': 75,
 '06:20:00': 76,
 '06:25:00': 77,
 '06:30:00': 78,
 '06:35:00': 79,
 '06:40:00': 80,
 '06:45:00': 81,
 '06:50:00': 82,
 '06:55:00': 83,
 '07:00:00': 84,
 '07:05:00': 85,
 '07:10:00': 86,
 '07:15:00': 87,
 '07:20:00': 88,
 '07:25:00': 89,
 '07:30:00': 90,
 '07:35:00': 91,
 '07:40:00': 92,
 '07:45:00': 93,
 '07:50:00': 94,
 '07:55:00': 95,
 '08:00:00': 96,
 '08:05:00': 97,
 '08:10:00': 98,
 '08:15:00': 99,
 '08:20:00': 100,
 '08:25:00': 101,
 '08:30:00': 102,
 '08:35:00': 103,
 '08:40:00': 104,
 '08:45:00': 105,
 '08:50:00': 106,
 '08:55:00': 107,
 '09:00:00': 108,
 '09:05:00': 109,
 '09:10:00': 110,
 '09:15:00': 111,
 '09:20:00': 112,
 '09:25:00': 113,
 '09:30:00': 114,
 '09:35:00': 115,
 '09:40:00': 116,
 '09:45:00': 117,
 '09:50:00': 118,
 '09:55:00': 119,
 '10:00:00': 120,
 '10:05:00': 121,
 '10:10:00': 122,
 '10:15:00': 123,
 '10:20:00': 124,
 '10:25:00': 125,
 '10:30:00': 126,
 '10:35:00': 127,
 '10:40:00': 128,
 '10:45:00': 129,
 '10:50:00': 130,
 '10:55:00': 131,
 '11:00:00': 132,
 '11:05:00': 133,
 '11:10:00': 134,
 '11:15:00': 135,
 '11:20:00': 136,
 '11:25:00': 137,
 '11:30:00': 138,
 '11:35:00': 139,
 '11:40:00': 140,
 '11:45:00': 141,
 '11:50:00': 142,
 '11:55:00': 143,
 '12:00:00': 144,
 '12:05:00': 145,
 '12:10:00': 146,
 '12:15:00': 147,
 '12:20:00': 148,
 '12:25:00': 149,
 '12:30:00': 150,
 '12:35:00': 151,
 '12:40:00': 152,
 '12:45:00': 153,
 '12:50:00': 154,
 '12:55:00': 155,
 '13:00:00': 156,
 '13:05:00': 157,
 '13:10:00': 158,
 '13:15:00': 159,
 '13:20:00': 160,
 '13:25:00': 161,
 '13:30:00': 162,
 '13:35:00': 163,
 '13:40:00': 164,
 '13:45:00': 165,
 '13:50:00': 166,
 '13:55:00': 167,
 '14:00:00': 168,
 '14:05:00': 169,
 '14:10:00': 170,
 '14:15:00': 171,
 '14:20:00': 172,
 '14:25:00': 173,
 '14:30:00': 174,
 '14:35:00': 175,
 '14:40:00': 176,
 '14:45:00': 177,
 '14:50:00': 178,
 '14:55:00': 179,
 '15:00:00': 180,
 '15:05:00': 181,
 '15:10:00': 182,
 '15:15:00': 183,
 '15:20:00': 184,
 '15:25:00': 185,
 '15:30:00': 186,
 '15:35:00': 187,
 '15:40:00': 188,
 '15:45:00': 189,
 '15:50:00': 190,
 '15:55:00': 191,
 '16:00:00': 192,
 '16:05:00': 193,
 '16:10:00': 194,
 '16:15:00': 195,
 '16:20:00': 196,
 '16:25:00': 197,
 '16:30:00': 198,
 '16:35:00': 199,
 '16:40:00': 200,
 '16:45:00': 201,
 '16:50:00': 202,
 '16:55:00': 203,
 '17:00:00': 204,
 '17:05:00': 205,
 '17:10:00': 206,
 '17:15:00': 207,
 '17:20:00': 208,
 '17:25:00': 209,
 '17:30:00': 210,
 '17:35:00': 211,
 '17:40:00': 212,
 '17:45:00': 213,
 '17:50:00': 214,
 '17:55:00': 215,
 '18:00:00': 216,
 '18:05:00': 217,
 '18:10:00': 218,
 '18:15:00': 219,
 '18:20:00': 220,
 '18:25:00': 221,
 '18:30:00': 222,
 '18:35:00': 223,
 '18:40:00': 224,
 '18:45:00': 225,
 '18:50:00': 226,
 '18:55:00': 227,
 '19:00:00': 228,
 '19:05:00': 229,
 '19:10:00': 230,
 '19:15:00': 231,
 '19:20:00': 232,
 '19:25:00': 233,
 '19:30:00': 234,
 '19:35:00': 235,
 '19:40:00': 236,
 '19:45:00': 237,
 '19:50:00': 238,
 '19:55:00': 239,
 '20:00:00': 240,
 '20:05:00': 241,
 '20:10:00': 242,
 '20:15:00': 243,
 '20:20:00': 244,
 '20:25:00': 245,
 '20:30:00': 246,
 '20:35:00': 247,
 '20:40:00': 248,
 '20:45:00': 249,
 '20:50:00': 250,
 '20:55:00': 251,
 '21:00:00': 252,
 '21:05:00': 253,
 '21:10:00': 254,
 '21:15:00': 255,
 '21:20:00': 256,
 '21:25:00': 257,
 '21:30:00': 258,
 '21:35:00': 259,
 '21:40:00': 260,
 '21:45:00': 261,
 '21:50:00': 262,
 '21:55:00': 263,
 '22:00:00': 264,
 '22:05:00': 265,
 '22:10:00': 266,
 '22:15:00': 267,
 '22:20:00': 268,
 '22:25:00': 269,
 '22:30:00': 270,
 '22:35:00': 271,
 '22:40:00': 272,
 '22:45:00': 273,
 '22:50:00': 274,
 '22:55:00': 275,
 '23:00:00': 276,
 '23:05:00': 277,
 '23:10:00': 278,
 '23:15:00': 279,
 '23:20:00': 280,
 '23:25:00': 281,
 '23:30:00': 282,
 '23:35:00': 283,
 '23:40:00': 284,
 '23:45:00': 285,
 '23:50:00': 286,
 '23:55:00': 287}

In [233]:
time

['00:00:00',
 '00:05:00',
 '00:10:00',
 '00:15:00',
 '00:20:00',
 '00:25:00',
 '00:30:00',
 '00:35:00',
 '00:40:00',
 '00:45:00',
 '00:50:00',
 '00:55:00',
 '01:00:00',
 '01:05:00',
 '01:10:00',
 '01:15:00',
 '01:20:00',
 '01:25:00',
 '01:30:00',
 '01:35:00',
 '01:40:00',
 '01:45:00',
 '01:50:00',
 '01:55:00',
 '02:00:00',
 '02:05:00',
 '02:10:00',
 '02:15:00',
 '02:20:00',
 '02:25:00',
 '02:30:00',
 '02:35:00',
 '02:40:00',
 '02:45:00',
 '02:50:00',
 '02:55:00',
 '03:00:00',
 '03:05:00',
 '03:10:00',
 '03:15:00',
 '03:20:00',
 '03:25:00',
 '03:30:00',
 '03:35:00',
 '03:40:00',
 '03:45:00',
 '03:50:00',
 '03:55:00',
 '04:00:00',
 '04:05:00',
 '04:10:00',
 '04:15:00',
 '04:20:00',
 '04:25:00',
 '04:30:00',
 '04:35:00',
 '04:40:00',
 '04:45:00',
 '04:50:00',
 '04:55:00',
 '05:00:00',
 '05:05:00',
 '05:10:00',
 '05:15:00',
 '05:20:00',
 '05:25:00',
 '05:30:00',
 '05:35:00',
 '05:40:00',
 '05:45:00',
 '05:50:00',
 '05:55:00',
 '06:00:00',
 '06:05:00',
 '06:10:00',
 '06:15:00',
 '06:20:00',
 '06:25:00',
 '06:30:00',
 '06:35:00',
 '06:40:00',
 '06:45:00',
 '06:50:00',
 '06:55:00',
 '07:00:00',
 '07:05:00',
 '07:10:00',
 '07:15:00',
 '07:20:00',
 '07:25:00',
 '07:30:00',
 '07:35:00',
 '07:40:00',
 '07:45:00',
 '07:50:00',
 '07:55:00',
 '08:00:00',
 '08:05:00',
 '08:10:00',
 '08:15:00',
 '08:20:00',
 '08:25:00',
 '08:30:00',
 '08:35:00',
 '08:40:00',
 '08:45:00',
 '08:50:00',
 '08:55:00',
 '09:00:00',
 '09:05:00',
 '09:10:00',
 '09:15:00',
 '09:20:00',
 '09:25:00',
 '09:30:00',
 '09:35:00',
 '09:40:00',
 '09:45:00',
 '09:50:00',
 '09:55:00',
 '10:00:00',
 '10:05:00',
 '10:10:00',
 '10:15:00',
 '10:20:00',
 '10:25:00',
 '10:30:00',
 '10:35:00',
 '10:40:00',
 '10:45:00',
 '10:50:00',
 '10:55:00',
 '11:00:00',
 '11:05:00',
 '11:10:00',
 '11:15:00',
 '11:20:00',
 '11:25:00',
 '11:30:00',
 '11:35:00',
 '11:40:00',
 '11:45:00',
 '11:50:00',
 '11:55:00',
 '12:00:00',
 '12:05:00',
 '12:10:00',
 '12:15:00',
 '12:20:00',
 '12:25:00',
 '12:30:00',
 '12:35:00',
 '12:40:00',
 '12:45:00',
 '12:50:00',
 '12:55:00',
 '13:00:00',
 '13:05:00',
 '13:10:00',
 '13:15:00',
 '13:20:00',
 '13:25:00',
 '13:30:00',
 '13:35:00',
 '13:40:00',
 '13:45:00',
 '13:50:00',
 '13:55:00',
 '14:00:00',
 '14:05:00',
 '14:10:00',
 '14:15:00',
 '14:20:00',
 '14:25:00',
 '14:30:00',
 '14:35:00',
 '14:40:00',
 '14:45:00',
 '14:50:00',
 '14:55:00',
 '15:00:00',
 '15:05:00',
 '15:10:00',
 '15:15:00',
 '15:20:00',
 '15:25:00',
 '15:30:00',
 '15:35:00',
 '15:40:00',
 '15:45:00',
 '15:50:00',
 '15:55:00',
 '16:00:00',
 '16:05:00',
 '16:10:00',
 '16:15:00',
 '16:20:00',
 '16:25:00',
 '16:30:00',
 '16:35:00',
 '16:40:00',
 '16:45:00',
 '16:50:00',
 '16:55:00',
 '17:00:00',
 '17:05:00',
 '17:10:00',
 '17:15:00',
 '17:20:00',
 '17:25:00',
 '17:30:00',
 '17:35:00',
 '17:40:00',
 '17:45:00',
 '17:50:00',
 '17:55:00',
 '18:00:00',
 '18:05:00',
 '18:10:00',
 '18:15:00',
 '18:20:00',
 '18:25:00',
 '18:30:00',
 '18:35:00',
 '18:40:00',
 '18:45:00',
 '18:50:00',
 '18:55:00',
 '19:00:00',
 '19:05:00',
 '19:10:00',
 '19:15:00',
 '19:20:00',
 '19:25:00',
 '19:30:00',
 '19:35:00',
 '19:40:00',
 '19:45:00',
 '19:50:00',
 '19:55:00',
 '20:00:00',
 '20:05:00',
 '20:10:00',
 '20:15:00',
 '20:20:00',
 '20:25:00',
 '20:30:00',
 '20:35:00',
 '20:40:00',
 '20:45:00',
 '20:50:00',
 '20:55:00',
 '21:00:00',
 '21:05:00',
 '21:10:00',
 '21:15:00',
 '21:20:00',
 '21:25:00',
 '21:30:00',
 '21:35:00',
 '21:40:00',
 '21:45:00',
 '21:50:00',
 '21:55:00',
 '22:00:00',
 '22:05:00',
 '22:10:00',
 '22:15:00',
 '22:20:00',
 '22:25:00',
 '22:30:00',
 '22:35:00',
 '22:40:00',
 '22:45:00',
 '22:50:00',
 '22:55:00',
 '23:00:00',
 '23:05:00',
 '23:10:00',
 '23:15:00',
 '23:20:00',
 '23:25:00',
 '23:30:00',
 '23:35:00',
 '23:40:00',
 '23:45:00',
 '23:50:00',
 '23:55:00']

In [322]:
# filedata["Timestamp"] = filedata["Timestamp"].str[-8:]
time = filedata["Timestamp"].unique().tolist() 

pair = list(itertools.product(time, sorted_sensors))
filedata["Station"] = filedata["Station"].astype("category")
filedata["Timestamp"] = filedata["Timestamp"].astype("category")
filedata["Station"].cat.set_categories(sorted_sensors, inplace=True)
filedata["Timestamp"].cat.set_categories(time, inplace=True)
# filedata["Timestamp"].replace(time_dict, inplace=True)
filedata = filedata.sort_values(["Station"])
filedata

C:\Users\STEPHE~1\AppData\Local\Temp/ipykernel_12716/1918302707.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filedata["Station"] = filedata["Station"].astype("category")
C:\Users\STEPHE~1\AppData\Local\Temp/ipykernel_12716/1918302707.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filedata["Timestamp"] = filedata["Timestamp"].astype("category")
C:\Users\Stephen Ma\anaconda3\envs\env_pytorch\lib\site-packages\pandas\core\arrays\categorical.py:2631: FutureWarning: The `inplace` parameter in pandas.Categorical.set_categories is deprecated and will be removed in a future version. Removing unused categories will always return a new Categorical object.
  res = method(*args, **kwargs)

,Timestamp,Station,District,Freeway,Direction,Type,Length,Sample,Observed Percentage,Flow,Avg Occupancy,Avg Speed
1,03/28/2021 00:00:00,400001,4,101,N,ML,0.265,50,100,74.0,0.0116,70.9
982473,03/28/2021 20:40:00,400001,4,101,N,ML,0.265,50,100,192.0,0.0301,69.9
986203,03/28/2021 20:45:00,400001,4,101,N,ML,0.265,50,100,196.0,0.0293,70.8
811927,03/28/2021 17:05:00,400001,4,101,N,ML,0.265,50,100,238.0,0.0362,71.4
471869,03/28/2021 09:55:00,400001,4,101,N,ML,0.265,50,100,262.0,0.0380,71.5
...,...,...,...,...,...,...,...,...,...,...,...,...
762379,03/28/2021 16:00:00,414694,4,280,N,ML,0.750,40,100,397.0,0.0675,65.7
765548,03/28/2021 16:05:00,414694,4,280,N,ML,0.750,40,100,391.0,0.0666,65.4
769331,03/28/2021 16:10:00,414694,4,280,N,ML,0.750,40,100,391.0,0.0648,66.1
747987,03/28/2021 15:40:00,414694,4,280,N,ML,0.750,40,100,463.0,0.0777,65.9
1140027,03/28/2021 23:55:00,414694,4,280,N,ML,0.750,40,100,57.0,0.0094,68.0

In [290]:
time

['02/10/2021 00:00:00',
 '02/10/2021 00:05:00',
 '02/10/2021 00:10:00',
 '02/10/2021 00:15:00',
 '02/10/2021 00:20:00',
 '02/10/2021 00:25:00',
 '02/10/2021 00:30:00',
 '02/10/2021 00:35:00',
 '02/10/2021 00:40:00',
 '02/10/2021 00:45:00',
 '02/10/2021 00:50:00',
 '02/10/2021 00:55:00',
 '02/10/2021 01:00:00',
 '02/10/2021 01:05:00',
 '02/10/2021 01:10:00',
 '02/10/2021 01:15:00',
 '02/10/2021 01:20:00',
 '02/10/2021 01:25:00',
 '02/10/2021 01:30:00',
 '02/10/2021 01:35:00',
 '02/10/2021 01:40:00',
 '02/10/2021 01:45:00',
 '02/10/2021 01:50:00',
 '02/10/2021 01:55:00',
 '02/10/2021 02:00:00',
 '02/10/2021 02:05:00',
 '02/10/2021 02:10:00',
 '02/10/2021 02:15:00',
 '02/10/2021 02:20:00',
 '02/10/2021 02:25:00',
 '02/10/2021 02:30:00',
 '02/10/2021 02:35:00',
 '02/10/2021 02:40:00',
 '02/10/2021 02:45:00',
 '02/10/2021 02:50:00',
 '02/10/2021 02:55:00',
 '02/10/2021 03:00:00',
 '02/10/2021 03:05:00',
 '02/10/2021 03:10:00',
 '02/10/2021 03:15:00',
 '02/10/2021 03:20:00',
 '02/10/2021 03:25:00',
 '02/10/2021 03:30:00',
 '02/10/2021 03:35:00',
 '02/10/2021 03:40:00',
 '02/10/2021 03:45:00',
 '02/10/2021 03:50:00',
 '02/10/2021 03:55:00',
 '02/10/2021 04:00:00',
 '02/10/2021 04:05:00',
 '02/10/2021 04:10:00',
 '02/10/2021 04:15:00',
 '02/10/2021 04:20:00',
 '02/10/2021 04:25:00',
 '02/10/2021 04:30:00',
 '02/10/2021 04:35:00',
 '02/10/2021 04:40:00',
 '02/10/2021 04:45:00',
 '02/10/2021 04:50:00',
 '02/10/2021 04:55:00',
 '02/10/2021 05:00:00',
 '02/10/2021 05:05:00',
 '02/10/2021 05:10:00',
 '02/10/2021 05:15:00',
 '02/10/2021 05:20:00',
 '02/10/2021 05:25:00',
 '02/10/2021 05:30:00',
 '02/10/2021 05:35:00',
 '02/10/2021 05:40:00',
 '02/10/2021 05:45:00',
 '02/10/2021 05:50:00',
 '02/10/2021 05:55:00',
 '02/10/2021 06:00:00',
 '02/10/2021 06:05:00',
 '02/10/2021 06:10:00',
 '02/10/2021 06:15:00',
 '02/10/2021 06:20:00',
 '02/10/2021 06:25:00',
 '02/10/2021 06:30:00',
 '02/10/2021 06:35:00',
 '02/10/2021 06:40:00',
 '02/10/2021 06:45:00',
 '02/10/2021 06:50:00',
 '02/10/2021 06:55:00',
 '02/10/2021 07:00:00',
 '02/10/2021 07:05:00',
 '02/10/2021 07:10:00',
 '02/10/2021 07:15:00',
 '02/10/2021 07:20:00',
 '02/10/2021 07:25:00',
 '02/10/2021 07:30:00',
 '02/10/2021 07:35:00',
 '02/10/2021 07:40:00',
 '02/10/2021 07:45:00',
 '02/10/2021 07:50:00',
 '02/10/2021 07:55:00',
 '02/10/2021 08:00:00',
 '02/10/2021 08:05:00',
 '02/10/2021 08:10:00',
 '02/10/2021 08:15:00',
 '02/10/2021 08:20:00',
 '02/10/2021 08:25:00',
 '02/10/2021 08:30:00',
 '02/10/2021 08:35:00',
 '02/10/2021 08:40:00',
 '02/10/2021 08:45:00',
 '02/10/2021 08:50:00',
 '02/10/2021 08:55:00',
 '02/10/2021 09:00:00',
 '02/10/2021 09:05:00',
 '02/10/2021 09:10:00',
 '02/10/2021 09:15:00',
 '02/10/2021 09:20:00',
 '02/10/2021 09:25:00',
 '02/10/2021 09:30:00',
 '02/10/2021 09:35:00',
 '02/10/2021 09:40:00',
 '02/10/2021 09:45:00',
 '02/10/2021 09:50:00',
 '02/10/2021 09:55:00',
 '02/10/2021 10:00:00',
 '02/10/2021 10:05:00',
 '02/10/2021 10:10:00',
 '02/10/2021 10:15:00',
 '02/10/2021 10:20:00',
 '02/10/2021 10:25:00',
 '02/10/2021 10:30:00',
 '02/10/2021 10:35:00',
 '02/10/2021 10:40:00',
 '02/10/2021 10:45:00',
 '02/10/2021 10:50:00',
 '02/10/2021 10:55:00',
 '02/10/2021 11:00:00',
 '02/10/2021 11:05:00',
 '02/10/2021 11:10:00',
 '02/10/2021 11:15:00',
 '02/10/2021 11:20:00',
 '02/10/2021 11:25:00',
 '02/10/2021 11:30:00',
 '02/10/2021 11:35:00',
 '02/10/2021 11:40:00',
 '02/10/2021 11:45:00',
 '02/10/2021 11:50:00',
 '02/10/2021 11:55:00',
 '02/10/2021 12:00:00',
 '02/10/2021 12:05:00',
 '02/10/2021 12:10:00',
 '02/10/2021 12:15:00',
 '02/10/2021 12:20:00',
 '02/10/2021 12:25:00',
 '02/10/2021 12:30:00',
 '02/10/2021 12:35:00',
 '02/10/2021 12:40:00',
 '02/10/2021 12:45:00',
 '02/10/2021 12:50:00',
 '02/10/2021 12:55:00',
 '02/10/2021 13:00:00',
 '02/10/2021 13:05:00',
 '02/10/2021 13:10:00',
 '02/10/2021 13:15:00',
 '02/10/2021 13:20:00',
 '02/10/2021 13:25:00',
 '02/10/2021 13:30:00',
 '02/10/2021 13:35:00',
 '02/10/2021 13:40:00',
 '02/10/2021 13:45:00',
 '02/10/2021 13:50:00',
 '02/10/2021 13:55:00',
 '02/10/2021 14:00:00',
 '02/10/2021 14:05:00',
 '02/10/2021 14:10:00',
 '02/10/2021 14:15:00',
 '02/10/2021 14:20:00',
 '02/10/2021 14:25:00',
 '02/10/2021 14:30:00',
 '02/10/2021 14:35:00',
 '02/10/2021 14:40:00',
 '02/10/2021 14:45:00',
 '02/10/2021 14:50:00',
 '02/10/2021 14:55:00',
 '02/10/2021 15:00:00',
 '02/10/2021 15:05:00',
 '02/10/2021 15:10:00',
 '02/10/2021 15:15:00',
 '02/10/2021 15:20:00',
 '02/10/2021 15:25:00',
 '02/10/2021 15:30:00',
 '02/10/2021 15:35:00',
 '02/10/2021 15:40:00',
 '02/10/2021 15:45:00',
 '02/10/2021 15:50:00',
 '02/10/2021 15:55:00',
 '02/10/2021 16:00:00',
 '02/10/2021 16:05:00',
 '02/10/2021 16:10:00',
 '02/10/2021 16:15:00',
 '02/10/2021 16:20:00',
 '02/10/2021 16:25:00',
 '02/10/2021 16:30:00',
 '02/10/2021 16:35:00',
 '02/10/2021 16:40:00',
 '02/10/2021 16:45:00',
 '02/10/2021 16:50:00',
 '02/10/2021 16:55:00',
 '02/10/2021 17:00:00',
 '02/10/2021 17:05:00',
 '02/10/2021 17:10:00',
 '02/10/2021 17:15:00',
 '02/10/2021 17:20:00',
 '02/10/2021 17:25:00',
 '02/10/2021 17:30:00',
 '02/10/2021 17:35:00',
 '02/10/2021 17:40:00',
 '02/10/2021 17:45:00',
 '02/10/2021 17:50:00',
 '02/10/2021 17:55:00',
 '02/10/2021 18:00:00',
 '02/10/2021 18:05:00',
 '02/10/2021 18:10:00',
 '02/10/2021 18:15:00',
 '02/10/2021 18:20:00',
 '02/10/2021 18:25:00',
 '02/10/2021 18:30:00',
 '02/10/2021 18:35:00',
 '02/10/2021 18:40:00',
 '02/10/2021 18:45:00',
 '02/10/2021 18:50:00',
 '02/10/2021 18:55:00',
 '02/10/2021 19:00:00',
 '02/10/2021 19:05:00',
 '02/10/2021 19:10:00',
 '02/10/2021 19:15:00',
 '02/10/2021 19:20:00',
 '02/10/2021 19:25:00',
 '02/10/2021 19:30:00',
 '02/10/2021 19:35:00',
 '02/10/2021 19:40:00',
 '02/10/2021 19:45:00',
 '02/10/2021 19:50:00',
 '02/10/2021 19:55:00',
 '02/10/2021 20:00:00',
 '02/10/2021 20:05:00',
 '02/10/2021 20:10:00',
 '02/10/2021 20:15:00',
 '02/10/2021 20:20:00',
 '02/10/2021 20:25:00',
 '02/10/2021 20:30:00',
 '02/10/2021 20:35:00',
 '02/10/2021 20:40:00',
 '02/10/2021 20:45:00',
 '02/10/2021 20:50:00',
 '02/10/2021 20:55:00',
 '02/10/2021 21:00:00',
 '02/10/2021 21:05:00',
 '02/10/2021 21:10:00',
 '02/10/2021 21:15:00',
 '02/10/2021 21:20:00',
 '02/10/2021 21:25:00',
 '02/10/2021 21:30:00',
 '02/10/2021 21:35:00',
 '02/10/2021 21:40:00',
 '02/10/2021 21:45:00',
 '02/10/2021 21:50:00',
 '02/10/2021 21:55:00',
 '02/10/2021 22:00:00',
 '02/10/2021 22:05:00',
 '02/10/2021 22:10:00',
 '02/10/2021 22:15:00',
 '02/10/2021 22:20:00',
 '02/10/2021 22:25:00',
 '02/10/2021 22:30:00',
 '02/10/2021 22:35:00',
 '02/10/2021 22:40:00',
 '02/10/2021 22:45:00',
 '02/10/2021 22:50:00',
 '02/10/2021 22:55:00',
 '02/10/2021 23:00:00',
 '02/10/2021 23:05:00',
 '02/10/2021 23:10:00',
 '02/10/2021 23:15:00',
 '02/10/2021 23:20:00',
 '02/10/2021 23:25:00',
 '02/10/2021 23:30:00',
 '02/10/2021 23:35:00',
 '02/10/2021 23:40:00',
 '02/10/2021 23:45:00',
 '02/10/2021 23:50:00',
 '02/10/2021 23:55:00',
 '02/11/2021 00:00:00',
 '02/11/2021 00:05:00',
 '02/11/2021 00:10:00',
 '02/11/2021 00:15:00',
 '02/11/2021 00:20:00',
 '02/11/2021 00:25:00',
 '02/11/2021 00:30:00',
 '02/11/2021 00:35:00',
 '02/11/2021 00:40:00',
 '02/11/2021 00:45:00',
 '02/11/2021 00:50:00',
 '02/11/2021 00:55:00',
 '02/11/2021 01:00:00',
 '02/11/2021 01:05:00',
 '02/11/2021 01:10:00',
 '02/11/2021 01:15:00',
 '02/11/2021 01:20:00',
 '02/11/2021 01:25:00',
 '02/11/2021 01:30:00',
 '02/11/2021 01:35:00',
 '02/11/2021 01:40:00',
 '02/11/2021 01:45:00',
 '02/11/2021 01:50:00',
 '02/11/2021 01:55:00',
 '02/11/2021 02:00:00',
 '02/11/2021 02:05:00',
 '02/11/2021 02:10:00',
 '02/11/2021 02:15:00',
 '02/11/2021 02:20:00',
 '02/11/2021 02:25:00',
 '02/11/2021 02:30:00',
 '02/11/2021 02:35:00',
 '02/11/2021 02:40:00',
 '02/11/2021 02:45:00',
 '02/11/2021 02:50:00',
 '02/11/2021 02:55:00',
 '02/11/2021 03:00:00',
 '02/11/2021 03:05:00',
 '02/11/2021 03:10:00',
 '02/11/2021 03:15:00',
 '02/11/2021 03:20:00',
 '02/11/2021 03:25:00',
 '02/11/2021 03:30:00',
 '02/11/2021 03:35:00',
 '02/11/2021 03:40:00',
 '02/11/2021 03:45:00',
 '02/11/2021 03:50:00',
 '02/11/2021 03:55:00',
 '02/11/2021 04:00:00']

In [265]:
from scipy.interpolate import interp1d
import numpy as np 

# ti=np.arange(0, (nt-1)*dt, tskip*dt )
# t=np.linspace(0, (nt-1)*dt, nt) 
# ti_test=np.arange(0, (nt_test-1)*dt, tskip*dt )
# t_test = np.linspace(0, (nt_test-1)*dt, nt_test)

def interpolate(var, ti, t): 
    IM_q=interp1d(np.array(ti), var[:, 0], bounds_error=False,
             fill_value=(var[0, 0], var[-1, 0]), kind='linear')
    IM_u=interp1d(np.array(ti), var[:, 1], bounds_error=False,
             fill_value=(var[0, 1], var[-1, 1]), kind='linear')
    u = IM_u(t)
    q = IM_q(t)
    boundary = np.stack((q, u), axis = 1) 
#     print(boundary.shape)
    return torch.tensor(boundary)

# for i in range(1, len(sorted_sensors) + 1): 
#     filedata.iloc[288 * (i - 1) : 288 * i] = filedata.iloc[288 * (i - 1) : 288 * i].sort_values(["Timestamp"])
# filedata
count = 0
data_per_sample = []
for i in sorted_sensors: 
    timesteps = (filedata["Station"] == i).sum() 
#     print(timesteps)
    filedata.iloc[count : count + timesteps] = filedata.iloc[count : count + timesteps].sort_values(["Timestamp"]) 
    if timesteps < 288: 
        ti = filedata.iloc[count : count + timesteps]["Timestamp"].values
#         print(ti)
        t=np.arange(0, 288, 1) 
#         print(t)
        data = filedata.iloc[count : count + timesteps][["Flow", "Avg Speed"]].to_numpy()
        data = interpolate(data, ti, t)
#         print(data.shape)
    else: 
        data = torch.tensor(filedata.iloc[count : count + timesteps][["Flow", "Avg Speed"]].to_numpy())
    
    data_per_sample.append(data)
#     break
    count += timesteps 
filedata
# data = filedata[["Flow", "Avg Speed"]].to_numpy()
# data = data.reshape(len(sorted_sensors), -1)
# data = data.reshape(len(sorted_sensors), 288, 2) 
# data = torch.tensor(data).permute(2, 1, 0)

287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
288
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
288
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
288
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
288
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
288
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
288
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)
287
(288, 2)

,Timestamp,Station,District,Freeway,Direction,Type,Length,Sample,Observed Percentage,Flow,Avg Occupancy,Avg Speed
1,0,400001,4,101,N,ML,0.265,50,100,22.0,0.0034,72.2
922141,1,400001,4,101,N,ML,0.265,50,100,19.0,0.0029,69.9
207973,2,400001,4,101,N,ML,0.265,50,100,24.0,0.0044,71.2
926065,3,400001,4,101,N,ML,0.265,50,100,25.0,0.0036,71.2
204049,4,400001,4,101,N,ML,0.265,50,100,31.0,0.0062,70.3
...,...,...,...,...,...,...,...,...,...,...,...,...
34899,283,414694,4,280,N,ML,0.750,40,100,47.0,0.0078,67.5
1118048,284,414694,4,280,N,ML,0.750,40,100,54.0,0.0096,67.9
81987,285,414694,4,280,N,ML,0.750,40,100,40.0,0.0065,66.7
1047291,286,414694,4,280,N,ML,0.750,40,100,31.0,0.0057,67.3
1125896,287,414694,4,280,N,ML,0.750,40,100,33.0,0.0052,67.0

In [267]:
torch.stack(data_per_sample, axis = 1).shape

torch.Size([288, 320, 2])

In [181]:
data = filedata[["Flow", "Avg Speed"]].to_numpy()
data.shape
# data = data.reshape(len(sorted_sensors), -1)
# data = data.reshape(len(sorted_sensors), 288, 2) 
# data = torch.tensor(data).permute(2, 1, 0)

(91846, 2)

In [289]:
filedata[filedata["Station"] == 400001]

,Timestamp,Station,District,Freeway,Direction,Type,Length,Sample,Observed Percentage,Flow,Avg Occupancy,Avg Speed
1,02/10/2021 00:00:00,400001,4,101,N,ML,0.265,50,100,26.0,0.0038,69.4
455765,02/10/2021 09:40:00,400001,4,101,N,ML,0.265,50,100,377.0,0.0639,67.9
1217991,02/11/2021 01:50:00,400001,4,101,N,ML,0.265,50,100,16.0,0.0027,72.1
1266796,02/11/2021 02:55:00,400001,4,101,N,ML,0.265,50,100,23.0,0.0041,70.0
314321,02/10/2021 06:40:00,400001,4,101,N,ML,0.265,50,100,506.0,0.0868,61.0
...,...,...,...,...,...,...,...,...,...,...,...,...
408617,02/10/2021 08:40:00,400001,4,101,N,ML,0.265,50,100,398.0,0.0628,66.9
1139411,02/11/2021 00:10:00,400001,4,101,N,ML,0.265,50,100,38.0,0.0078,70.3
1001896,02/10/2021 21:15:00,400001,4,101,N,ML,0.265,50,100,117.0,0.0171,71.5
404688,02/10/2021 08:35:00,400001,4,101,N,ML,0.265,50,100,431.0,0.0735,64.6
671860,02/10/2021 14:15:00,400001,4,101,N,ML,0.265,50,100,195.0,0.0304,70.6

In [288]:
# filedata.iloc[288 * (2) : 288 * 3]
# temp[temp["Station"] == 400040]
temp = filedata[filedata["Station"] == 400001]
temp_time = temp["Timestamp"].unique().tolist() 
list(set(time) - set(temp_time))

['02/11/2021 02:50:00']

In [318]:
for i in range(1, len(sorted_sensors) + 1): 
    sens = filedata.iloc[288 * (i - 1) : 288 * i]["Station"].values.unique() 
    if len(sens) > 1: 
        print(sens, i)

In [178]:
time, len(time)

(['01/14/2021 00:00:00',
  '01/14/2021 00:05:00',
  '01/14/2021 00:10:00',
  '01/14/2021 00:15:00',
  '01/14/2021 00:20:00',
  '01/14/2021 00:25:00',
  '01/14/2021 00:30:00',
  '01/14/2021 00:35:00',
  '01/14/2021 00:40:00',
  '01/14/2021 00:45:00',
  '01/14/2021 00:50:00',
  '01/14/2021 00:55:00',
  '01/14/2021 01:00:00',
  '01/14/2021 01:05:00',
  '01/14/2021 01:10:00',
  '01/14/2021 01:15:00',
  '01/14/2021 01:20:00',
  '01/14/2021 01:25:00',
  '01/14/2021 01:30:00',
  '01/14/2021 01:35:00',
  '01/14/2021 01:40:00',
  '01/14/2021 01:45:00',
  '01/14/2021 01:50:00',
  '01/14/2021 01:55:00',
  '01/14/2021 02:00:00',
  '01/14/2021 02:05:00',
  '01/14/2021 02:10:00',
  '01/14/2021 02:15:00',
  '01/14/2021 02:20:00',
  '01/14/2021 02:25:00',
  '01/14/2021 02:30:00',
  '01/14/2021 02:35:00',
  '01/14/2021 02:40:00',
  '01/14/2021 02:45:00',
  '01/14/2021 02:50:00',
  '01/14/2021 02:55:00',
  '01/14/2021 03:00:00',
  '01/14/2021 03:05:00',
  '01/14/2021 03:10:00',
  '01/14/2021 03:15:00',
  '01/14/2021 03:20:00',
  '01/14/2021 03:25:00',
  '01/14/2021 03:30:00',
  '01/14/2021 03:35:00',
  '01/14/2021 03:40:00',
  '01/14/2021 03:45:00',
  '01/14/2021 03:50:00',
  '01/14/2021 03:55:00',
  '01/14/2021 04:00:00',
  '01/14/2021 04:05:00',
  '01/14/2021 04:10:00',
  '01/14/2021 04:15:00',
  '01/14/2021 04:20:00',
  '01/14/2021 04:25:00',
  '01/14/2021 04:30:00',
  '01/14/2021 04:35:00',
  '01/14/2021 04:40:00',
  '01/14/2021 04:45:00',
  '01/14/2021 04:50:00',
  '01/14/2021 04:55:00',
  '01/14/2021 05:00:00',
  '01/14/2021 05:05:00',
  '01/14/2021 05:10:00',
  '01/14/2021 05:15:00',
  '01/14/2021 05:20:00',
  '01/14/2021 05:25:00',
  '01/14/2021 05:30:00',
  '01/14/2021 05:35:00',
  '01/14/2021 05:40:00',
  '01/14/2021 05:45:00',
  '01/14/2021 05:50:00',
  '01/14/2021 05:55:00',
  '01/14/2021 06:00:00',
  '01/14/2021 06:05:00',
  '01/14/2021 06:10:00',
  '01/14/2021 06:15:00',
  '01/14/2021 06:20:00',
  '01/14/2021 06:25:00',
  '01/14/2021 06:30:00',
  '01/14/2021 06:35:00',
  '01/14/2021 06:40:00',
  '01/14/2021 06:45:00',
  '01/14/2021 06:50:00',
  '01/14/2021 06:55:00',
  '01/14/2021 07:00:00',
  '01/14/2021 07:05:00',
  '01/14/2021 07:10:00',
  '01/14/2021 07:15:00',
  '01/14/2021 07:20:00',
  '01/14/2021 07:25:00',
  '01/14/2021 07:30:00',
  '01/14/2021 07:35:00',
  '01/14/2021 07:40:00',
  '01/14/2021 07:45:00',
  '01/14/2021 07:50:00',
  '01/14/2021 07:55:00',
  '01/14/2021 08:00:00',
  '01/14/2021 08:05:00',
  '01/14/2021 08:10:00',
  '01/14/2021 08:15:00',
  '01/14/2021 08:20:00',
  '01/14/2021 08:25:00',
  '01/14/2021 08:30:00',
  '01/14/2021 08:35:00',
  '01/14/2021 08:40:00',
  '01/14/2021 08:45:00',
  '01/14/2021 08:50:00',
  '01/14/2021 08:55:00',
  '01/14/2021 09:00:00',
  '01/14/2021 09:05:00',
  '01/14/2021 09:10:00',
  '01/14/2021 09:15:00',
  '01/14/2021 09:20:00',
  '01/14/2021 09:25:00',
  '01/14/2021 09:30:00',
  '01/14/2021 09:35:00',
  '01/14/2021 09:40:00',
  '01/14/2021 09:45:00',
  '01/14/2021 09:50:00',
  '01/14/2021 09:55:00',
  '01/14/2021 10:00:00',
  '01/14/2021 10:05:00',
  '01/14/2021 10:10:00',
  '01/14/2021 10:15:00',
  '01/14/2021 10:20:00',
  '01/14/2021 10:25:00',
  '01/14/2021 10:30:00',
  '01/14/2021 10:35:00',
  '01/14/2021 10:40:00',
  '01/14/2021 10:45:00',
  '01/14/2021 10:50:00',
  '01/14/2021 10:55:00',
  '01/14/2021 11:00:00',
  '01/14/2021 11:05:00',
  '01/14/2021 11:10:00',
  '01/14/2021 11:15:00',
  '01/14/2021 11:20:00',
  '01/14/2021 11:25:00',
  '01/14/2021 11:30:00',
  '01/14/2021 11:35:00',
  '01/14/2021 11:40:00',
  '01/14/2021 11:45:00',
  '01/14/2021 11:50:00',
  '01/14/2021 11:55:00',
  '01/14/2021 12:00:00',
  '01/14/2021 12:05:00',
  '01/14/2021 12:10:00',
  '01/14/2021 12:15:00',
  '01/14/2021 12:20:00',
  '01/14/2021 12:25:00',
  '01/14/2021 12:30:00',
  '01/14/2021 12:35:00',
  '01/14/2021 12:40:00',
  '01/14/2021 12:45:00',
  '01/14/2021 12:50:00',
  '01/14/2021 12:55:00',
  '01/14/2021 13:00:00',
  '01/14/2021 13:05:00',
  '01/14/2021 13:10:00',
  '01/14/2021 13:15:00',
  '01/14/2021 13:20:00',
  '01/14/2021 13:25:00',
  '01/14/2021 13:30:00',
  '01/14/2021 13:35:00',
  '01/14/2021 13:40:00',
  '01/14/2021 13:45:00',
  '01/14/2021 13:50:00',
  '01/14/2021 13:55:00',
  '01/14/2021 14:00:00',
  '01/14/2021 14:05:00',
  '01/14/2021 14:10:00',
  '01/14/2021 14:15:00',
  '01/14/2021 14:20:00',
  '01/14/2021 14:25:00',
  '01/14/2021 14:30:00',
  '01/14/2021 14:35:00',
  '01/14/2021 14:40:00',
  '01/14/2021 14:45:00',
  '01/14/2021 14:50:00',
  '01/14/2021 14:55:00',
  '01/14/2021 15:00:00',
  '01/14/2021 15:05:00',
  '01/14/2021 15:10:00',
  '01/14/2021 15:15:00',
  '01/14/2021 15:20:00',
  '01/14/2021 15:25:00',
  '01/14/2021 15:30:00',
  '01/14/2021 15:35:00',
  '01/14/2021 15:40:00',
  '01/14/2021 15:45:00',
  '01/14/2021 15:50:00',
  '01/14/2021 15:55:00',
  '01/14/2021 16:00:00',
  '01/14/2021 16:05:00',
  '01/14/2021 16:10:00',
  '01/14/2021 16:15:00',
  '01/14/2021 16:20:00',
  '01/14/2021 16:25:00',
  '01/14/2021 16:30:00',
  '01/14/2021 16:35:00',
  '01/14/2021 16:40:00',
  '01/14/2021 16:45:00',
  '01/14/2021 16:50:00',
  '01/14/2021 16:55:00',
  '01/14/2021 17:00:00',
  '01/14/2021 17:05:00',
  '01/14/2021 17:10:00',
  '01/14/2021 17:15:00',
  '01/14/2021 17:20:00',
  '01/14/2021 17:25:00',
  '01/14/2021 17:30:00',
  '01/14/2021 17:35:00',
  '01/14/2021 17:40:00',
  '01/14/2021 17:45:00',
  '01/14/2021 17:50:00',
  '01/14/2021 17:55:00',
  '01/14/2021 18:00:00',
  '01/14/2021 18:05:00',
  '01/14/2021 18:10:00',
  '01/14/2021 18:15:00',
  '01/14/2021 18:20:00',
  '01/14/2021 18:25:00',
  '01/14/2021 18:30:00',
  '01/14/2021 18:35:00',
  '01/14/2021 18:40:00',
  '01/14/2021 18:45:00',
  '01/14/2021 18:50:00',
  '01/14/2021 18:55:00',
  '01/14/2021 19:00:00',
  '01/14/2021 19:05:00',
  '01/14/2021 19:10:00',
  '01/14/2021 19:15:00',
  '01/14/2021 19:20:00',
  '01/14/2021 19:25:00',
  '01/14/2021 19:30:00',
  '01/14/2021 19:35:00',
  '01/14/2021 19:40:00',
  '01/14/2021 19:45:00',
  '01/14/2021 19:50:00',
  '01/14/2021 19:55:00',
  '01/14/2021 20:00:00',
  '01/14/2021 20:05:00',
  '01/14/2021 20:10:00',
  '01/14/2021 20:15:00',
  '01/14/2021 20:20:00',
  '01/14/2021 20:25:00',
  '01/14/2021 20:30:00',
  '01/14/2021 20:35:00',
  '01/14/2021 20:40:00',
  '01/14/2021 20:45:00',
  '01/14/2021 20:50:00',
  '01/14/2021 20:55:00',
  '01/14/2021 21:00:00',
  '01/14/2021 21:05:00',
  '01/14/2021 21:10:00',
  '01/14/2021 21:15:00',
  '01/14/2021 21:20:00',
  '01/14/2021 21:25:00',
  '01/14/2021 21:30:00',
  '01/14/2021 21:35:00',
  '01/14/2021 21:40:00',
  '01/14/2021 21:45:00',
  '01/14/2021 21:50:00',
  '01/14/2021 21:55:00',
  '01/14/2021 22:00:00',
  '01/14/2021 22:05:00',
  '01/14/2021 22:10:00',
  '01/14/2021 22:15:00',
  '01/14/2021 22:20:00',
  '01/14/2021 22:25:00',
  '01/14/2021 22:30:00',
  '01/14/2021 22:35:00',
  '01/14/2021 22:40:00',
  '01/14/2021 22:45:00',
  '01/14/2021 22:50:00',
  '01/14/2021 22:55:00',
  '01/14/2021 23:00:00',
  '01/14/2021 23:10:00',
  '01/14/2021 23:15:00',
  '01/14/2021 23:20:00',
  '01/14/2021 23:25:00',
  '01/14/2021 23:30:00',
  '01/14/2021 23:35:00',
  '01/14/2021 23:40:00',
  '01/14/2021 23:45:00',
  '01/14/2021 23:50:00',
  '01/14/2021 23:55:00',
  '01/14/2021 23:05:00'],
 288)

In [149]:
sen = filedata["Station"].unique() 
print(len(sen))
for i in sen: 
    if i in sorted_sensors:
        print("true")

320
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true

In [150]:
list(set(sorted_sensors) - set(sen)), list(set(sen) - set(sorted_sensors))

([], [])

In [88]:
data = filedata[["Flow", "Avg Speed"]].to_numpy()
data = data.reshape(len(sorted_sensors), -1)
data = data.reshape(len(sorted_sensors), 288, 2) 
data = torch.tensor(data).permute(2, 1, 0)

In [95]:
data[1, :, -1]

tensor([68.8000, 68.3000, 67.7000, 67.2000, 66.2000, 67.2000, 67.8000, 67.8000,
        67.8000, 68.0000, 67.1000, 67.4000, 66.8000, 67.9000, 68.0000, 67.1000,
        66.2000, 67.7000, 67.9000, 67.4000, 67.5000, 67.7000, 67.8000, 67.5000,
        66.4000, 68.7000, 67.6000, 68.4000, 67.6000, 67.3000, 68.6000, 66.5000,
        67.6000, 67.8000, 67.2000, 66.9000, 66.8000, 66.6000, 67.1000, 67.0000,
        68.6000, 68.4000, 67.8000, 67.3000, 67.5000, 66.2000, 67.6000, 67.5000,
        66.7000, 67.3000, 67.3000, 67.0000, 67.4000, 67.0000, 62.9000, 69.0000,
        65.6000, 67.9000, 66.9000, 67.7000, 66.8000, 66.9000, 67.5000, 66.6000,
        67.6000, 66.7000, 66.1000, 69.0000, 66.5000, 66.4000, 68.0000, 67.1000,
        68.6000, 66.6000, 68.2000, 68.5000, 67.6000, 70.7000, 67.8000, 70.4000,
        68.9000, 68.4000, 68.1000, 70.2000, 69.1000, 70.2000, 67.6000, 67.7000,
        67.0000, 69.5000, 67.8000, 67.9000, 69.6000, 67.6000, 67.3000, 68.0000,
        67.1000, 69.1000, 65.1000, 66.3000, 66.2000, 68.1000, 69.5000, 70.8000,
        70.4000, 70.2000, 69.8000, 69.5000, 69.7000, 68.6000, 70.2000, 70.1000,
        70.5000, 68.2000, 67.0000, 67.2000, 67.7000, 68.4000, 68.5000, 67.3000,
        70.3000, 69.3000, 68.3000, 68.6000, 67.1000, 66.9000, 66.4000, 67.1000,
        67.6000, 67.1000, 67.0000, 65.7000, 68.4000, 69.2000, 70.2000, 67.6000,
        67.3000, 66.4000, 66.3000, 66.9000, 67.6000, 66.4000, 68.4000, 70.2000,
        69.9000, 68.1000, 67.2000, 67.1000, 68.3000, 68.3000, 67.9000, 68.3000,
        67.2000, 67.7000, 67.1000, 66.6000, 66.0000, 65.6000, 66.8000, 65.6000,
        66.4000, 65.7000, 66.6000, 65.6000, 66.0000, 64.5000, 65.8000, 67.0000,
        67.3000, 67.4000, 66.2000, 66.5000, 65.4000, 66.9000, 65.6000, 66.1000,
        66.0000, 66.4000, 66.0000, 65.0000, 64.2000, 61.0000, 61.9000, 61.3000,
        57.6000, 48.7000, 41.0000, 29.5000, 23.1000, 17.8000, 17.1000, 16.0000,
        15.9000, 14.6000, 14.4000, 14.6000, 14.5000, 16.5000, 15.1000, 14.7000,
        15.0000, 13.9000, 14.1000, 14.3000, 15.5000, 15.7000, 15.5000, 15.1000,
        15.4000, 15.5000, 16.1000, 16.1000, 15.2000, 16.1000, 16.5000, 15.8000,
        16.2000, 15.0000, 16.5000, 16.2000, 18.2000, 14.6000, 14.5000, 15.7000,
        19.7000, 34.6000, 45.4000, 52.0000, 56.5000, 59.8000, 60.8000, 62.7000,
        62.6000, 64.0000, 63.1000, 63.6000, 61.6000, 61.1000, 61.6000, 62.6000,
        62.9000, 63.2000, 63.4000, 63.6000, 64.1000, 64.2000, 65.5000, 67.1000,
        64.6000, 65.3000, 63.5000, 62.4000, 64.2000, 63.4000, 68.9000, 68.3000,
        70.9000, 68.8000, 67.1000, 68.7000, 68.4000, 68.3000, 68.5000, 71.1000,
        71.7000, 72.3000, 70.9000, 70.4000, 69.4000, 69.0000, 69.4000, 68.4000,
        68.3000, 71.0000, 69.8000, 71.4000, 69.6000, 68.4000, 68.1000, 69.7000,
        67.9000, 67.8000, 68.3000, 68.2000, 68.4000, 69.4000, 69.3000, 68.2000],
       dtype=torch.float64)

In [15]:
filedata = file1[(file1["Freeway"] == 5) & (file1["Direction"] == "S") & (file1["Type"] == "ML")]
filedata

,Timestamp,Station,District,Freeway,Direction,Type,Length,Sample,Observed Percentage,Flow,Avg Occupancy,Avg Speed
173,09/17/2021 00:00:00,1108417,11,5,S,ML,0.484,50,80,125.0,0.0263,68.0
186,09/17/2021 00:00:00,1108434,11,5,S,ML,0.607,40,100,99.0,0.0210,70.0
202,09/17/2021 00:00:00,1108452,11,5,S,ML,0.867,40,100,50.0,0.0108,68.4
205,09/17/2021 00:00:00,1108459,11,5,S,ML,0.932,0,0,117.0,0.0283,63.8
207,09/17/2021 00:00:00,1108461,11,5,S,ML,0.848,40,100,105.0,0.0231,68.6
...,...,...,...,...,...,...,...,...,...,...,...,...
396611,09/17/2021 23:55:00,1122583,11,5,S,ML,0.443,40,100,145.0,0.0259,72.8
396647,09/17/2021 23:55:00,1123133,11,5,S,ML,0.971,40,100,99.0,0.0232,66.8
396648,09/17/2021 23:55:00,1123134,11,5,S,ML,0.652,10,100,3.0,0.0058,65.1
396789,09/17/2021 23:55:00,1126426,11,5,S,ML,1.105,50,100,142.0,0.0236,70.9
396857,09/17/2021 23:55:00,1127123,11,5,S,ML,1.391,30,100,57.0,0.0139,69.3

In [16]:
len(filedata)

24192

array(['02/10/2021 00:00:00', '02/10/2021 00:05:00',
       '02/10/2021 00:10:00', '02/10/2021 00:15:00',
       '02/10/2021 00:20:00', '02/10/2021 00:25:00',
       '02/10/2021 00:30:00', '02/10/2021 00:35:00',
       '02/10/2021 00:40:00', '02/10/2021 00:45:00',
       '02/10/2021 00:50:00', '02/10/2021 00:55:00',
       '02/10/2021 01:00:00', '02/10/2021 01:05:00',
       '02/10/2021 01:10:00', '02/10/2021 01:15:00',
       '02/10/2021 01:20:00', '02/10/2021 01:25:00',
       '02/10/2021 01:30:00', '02/10/2021 01:35:00',
       '02/10/2021 01:40:00', '02/10/2021 01:45:00',
       '02/10/2021 01:50:00', '02/10/2021 01:55:00',
       '02/10/2021 02:00:00', '02/10/2021 02:05:00',
       '02/10/2021 02:10:00', '02/10/2021 02:15:00',
       '02/10/2021 02:20:00', '02/10/2021 02:25:00',
       '02/10/2021 02:30:00', '02/10/2021 02:35:00',
       '02/10/2021 02:40:00', '02/10/2021 02:45:00',
       '02/10/2021 02:50:00', '02/10/2021 02:55:00',
       '02/10/2021 03:00:00', '02/10/2021 03:05:00',
       '02/10/2021 03:10:00', '02/10/2021 03:15:00',
       '02/10/2021 03:20:00', '02/10/2021 03:25:00',
       '02/10/2021 03:30:00', '02/10/2021 03:35:00',
       '02/10/2021 03:40:00', '02/10/2021 03:45:00',
       '02/10/2021 03:50:00', '02/10/2021 03:55:00',
       '02/10/2021 04:00:00', '02/10/2021 04:05:00',
       '02/10/2021 04:10:00', '02/10/2021 04:15:00',
       '02/10/2021 04:20:00', '02/10/2021 04:25:00',
       '02/10/2021 04:30:00', '02/10/2021 04:35:00',
       '02/10/2021 04:40:00', '02/10/2021 04:45:00',
       '02/10/2021 04:50:00', '02/10/2021 04:55:00',
       '02/10/2021 05:00:00', '02/10/2021 05:05:00',
       '02/10/2021 05:10:00', '02/10/2021 05:15:00',
       '02/10/2021 05:20:00', '02/10/2021 05:25:00',
       '02/10/2021 05:30:00', '02/10/2021 05:35:00',
       '02/10/2021 05:40:00', '02/10/2021 05:45:00',
       '02/10/2021 05:50:00', '02/10/2021 05:55:00',
       '02/10/2021 06:00:00', '02/10/2021 06:05:00',
       '02/10/2021 06:10:00', '02/10/2021 06:15:00',
       '02/10/2021 06:20:00', '02/10/2021 06:25:00',
       '02/10/2021 06:30:00', '02/10/2021 06:35:00',
       '02/10/2021 06:40:00', '02/10/2021 06:45:00',
       '02/10/2021 06:50:00', '02/10/2021 06:55:00',
       '02/10/2021 07:00:00', '02/10/2021 07:05:00',
       '02/10/2021 07:10:00', '02/10/2021 07:15:00',
       '02/10/2021 07:20:00', '02/10/2021 07:25:00',
       '02/10/2021 07:30:00', '02/10/2021 07:35:00',
       '02/10/2021 07:40:00', '02/10/2021 07:45:00',
       '02/10/2021 07:50:00', '02/10/2021 07:55:00',
       '02/10/2021 08:00:00', '02/10/2021 08:05:00',
       '02/10/2021 08:10:00', '02/10/2021 08:15:00',
       '02/10/2021 08:20:00', '02/10/2021 08:25:00',
       '02/10/2021 08:30:00', '02/10/2021 08:35:00',
       '02/10/2021 08:40:00', '02/10/2021 08:45:00',
       '02/10/2021 08:50:00', '02/10/2021 08:55:00',
       '02/10/2021 09:00:00', '02/10/2021 09:05:00',
       '02/10/2021 09:10:00', '02/10/2021 09:15:00',
       '02/10/2021 09:20:00', '02/10/2021 09:25:00',
       '02/10/2021 09:30:00', '02/10/2021 09:35:00',
       '02/10/2021 09:40:00', '02/10/2021 09:45:00',
       '02/10/2021 09:50:00', '02/10/2021 09:55:00',
       '02/10/2021 10:00:00', '02/10/2021 10:05:00',
       '02/10/2021 10:10:00', '02/10/2021 10:15:00',
       '02/10/2021 10:20:00', '02/10/2021 10:25:00',
       '02/10/2021 10:30:00', '02/10/2021 10:35:00',
       '02/10/2021 10:40:00', '02/10/2021 10:45:00',
       '02/10/2021 10:50:00', '02/10/2021 10:55:00',
       '02/10/2021 11:00:00', '02/10/2021 11:05:00',
       '02/10/2021 11:10:00', '02/10/2021 11:15:00',
       '02/10/2021 11:20:00', '02/10/2021 11:25:00',
       '02/10/2021 11:30:00', '02/10/2021 11:35:00',
       '02/10/2021 11:40:00', '02/10/2021 11:45:00',
       '02/10/2021 11:50:00', '02/10/2021 11:55:00',
       '02/10/2021 12:00:00', '02/10/2021 12:05:00',
       '02/10/2021 12:10:00', '02/10/2021 12:15:00',
       '02/10/2021 12:20:00', '02/10/2021 12:25:00',
       '02/10/2021 12:30:00', '02/10/2021 12:35:00',
       '02/10/2021 12:40:00', '02/10/2021 12:45:00',
       '02/10/2021 12:50:00', '02/10/2021 12:55:00',
       '02/10/2021 13:00:00', '02/10/2021 13:05:00',
       '02/10/2021 13:10:00', '02/10/2021 13:15:00',
       '02/10/2021 13:20:00', '02/10/2021 13:25:00',
       '02/10/2021 13:30:00', '02/10/2021 13:35:00',
       '02/10/2021 13:40:00', '02/10/2021 13:45:00',
       '02/10/2021 13:50:00', '02/10/2021 13:55:00',
       '02/10/2021 14:00:00', '02/10/2021 14:05:00',
       '02/10/2021 14:10:00', '02/10/2021 14:15:00',
       '02/10/2021 14:20:00', '02/10/2021 14:25:00',
       '02/10/2021 14:30:00', '02/10/2021 14:35:00',
       '02/10/2021 14:40:00', '02/10/2021 14:45:00',
       '02/10/2021 14:50:00', '02/10/2021 14:55:00',
       '02/10/2021 15:00:00', '02/10/2021 15:05:00',
       '02/10/2021 15:10:00', '02/10/2021 15:15:00',
       '02/10/2021 15:20:00', '02/10/2021 15:25:00',
       '02/10/2021 15:30:00', '02/10/2021 15:35:00',
       '02/10/2021 15:40:00', '02/10/2021 15:45:00',
       '02/10/2021 15:50:00', '02/10/2021 15:55:00',
       '02/10/2021 16:00:00', '02/10/2021 16:05:00',
       '02/10/2021 16:10:00', '02/10/2021 16:15:00',
       '02/10/2021 16:20:00', '02/10/2021 16:25:00',
       '02/10/2021 16:30:00', '02/10/2021 16:35:00',
       '02/10/2021 16:40:00', '02/10/2021 16:45:00',
       '02/10/2021 16:50:00', '02/10/2021 16:55:00',
       '02/10/2021 17:00:00', '02/10/2021 17:05:00',
       '02/10/2021 17:10:00', '02/10/2021 17:15:00',
       '02/10/2021 17:20:00', '02/10/2021 17:25:00',
       '02/10/2021 17:30:00', '02/10/2021 17:35:00',
       '02/10/2021 17:40:00', '02/10/2021 17:45:00',
       '02/10/2021 17:50:00', '02/10/2021 17:55:00',
       '02/10/2021 18:00:00', '02/10/2021 18:05:00',
       '02/10/2021 18:10:00', '02/10/2021 18:15:00',
       '02/10/2021 18:20:00', '02/10/2021 18:25:00',
       '02/10/2021 18:30:00', '02/10/2021 18:35:00',
       '02/10/2021 18:40:00', '02/10/2021 18:45:00',
       '02/10/2021 18:50:00', '02/10/2021 18:55:00',
       '02/10/2021 19:00:00', '02/10/2021 19:05:00',
       '02/10/2021 19:10:00', '02/10/2021 19:15:00',
       '02/10/2021 19:20:00', '02/10/2021 19:25:00',
       '02/10/2021 19:30:00', '02/10/2021 19:35:00',
       '02/10/2021 19:40:00', '02/10/2021 19:45:00',
       '02/10/2021 19:50:00', '02/10/2021 19:55:00',
       '02/10/2021 20:00:00', '02/10/2021 20:05:00',
       '02/10/2021 20:10:00', '02/10/2021 20:15:00',
       '02/10/2021 20:20:00', '02/10/2021 20:25:00',
       '02/10/2021 20:30:00', '02/10/2021 20:35:00',
       '02/10/2021 20:40:00', '02/10/2021 20:45:00',
       '02/10/2021 20:50:00', '02/10/2021 20:55:00',
       '02/10/2021 21:00:00', '02/10/2021 21:05:00',
       '02/10/2021 21:10:00', '02/10/2021 21:15:00',
       '02/10/2021 21:20:00', '02/10/2021 21:25:00',
       '02/10/2021 21:30:00', '02/10/2021 21:35:00',
       '02/10/2021 21:40:00', '02/10/2021 21:45:00',
       '02/10/2021 21:50:00', '02/10/2021 21:55:00',
       '02/10/2021 22:00:00', '02/10/2021 22:05:00',
       '02/10/2021 22:10:00', '02/10/2021 22:15:00',
       '02/10/2021 22:20:00', '02/10/2021 22:25:00',
       '02/10/2021 22:30:00', '02/10/2021 22:35:00',
       '02/10/2021 22:40:00', '02/10/2021 22:45:00',
       '02/10/2021 22:50:00', '02/10/2021 22:55:00',
       '02/10/2021 23:00:00', '02/10/2021 23:05:00',
       '02/10/2021 23:10:00', '02/10/2021 23:15:00',
       '02/10/2021 23:20:00', '02/10/2021 23:25:00',
       '02/10/2021 23:30:00', '02/10/2021 23:35:00',
       '02/10/2021 23:40:00', '02/10/2021 23:45:00',
       '02/10/2021 23:50:00', '02/10/2021 23:55:00',
       '02/11/2021 00:00:00', '02/11/2021 00:05:00',
       '02/11/2021 00:10:00', '02/11/2021 00:15:00',
       '02/11/2021 00:20:00', '02/11/2021 00:25:00',
       '02/11/2021 00:30:00', '02/11/2021 00:35:00',
       '02/11/2021 00:40:00', '02/11/2021 00:45:00',
       '02/11/2021 00:50:00', '02/11/2021 00:55:00',
       '02/11/2021 01:00:00', '02/11/2021 01:05:00',
       '02/11/2021 01:10:00', '02/11/2021 01:15:00',
       '02/11/2021 01:20:00', '02/11/2021 01:25:00',
       '02/11/2021 01:30:00', '02/11/2021 01:35:00',
       '02/11/2021 01:40:00', '02/11/2021 01:45:00',
       '02/11/2021 01:50:00', '02/11/2021 01:55:00',
       '02/11/2021 02:00:00', '02/11/2021 02:05:00',
       '02/11/2021 02:10:00', '02/11/2021 02:15:00',
       '02/11/2021 02:20:00', '02/11/2021 02:25:00',
       '02/11/2021 02:30:00', '02/11/2021 02:35:00',
       '02/11/2021 02:40:00', '02/11/2021 02:45:00',
       '02/11/2021 02:50:00', '02/11/2021 02:55:00',
       '02/11/2021 03:00:00', '02/11/2021 03:05:00',
       '02/11/2021 03:10:00', '02/11/2021 03:15:00',
       '02/11/2021 03:20:00', '02/11/2021 03:25:00',
       '02/11/2021 03:30:00', '02/11/2021 03:35:00',
       '02/11/2021 03:40:00', '02/11/2021 03:45:00',
       '02/11/2021 03:50:00', '02/11/2021 03:55:00',
       '02/11/2021 04:00:00', '02/11/2021 04:05:00',
       '02/11/2021 04:10:00', '02/11/2021 04:15:00',
       '02/11/2021 04:20:00', '02/11/2021 04:25:00',
       '02/11/2021 04:30:00', '02/11/2021 04:35:00',
       '02/11/2021 04:40:00', '02/11/2021 04:45:00',
       '02/11/2021 04:50:00'], dtype=object)

In [17]:
filedata = filedata[filedata["Station"].isin(sorted_sensors)]
filedata

,Timestamp,Station,District,Freeway,Direction,Type,Length,Sample,Observed Percentage,Flow,Avg Occupancy,Avg Speed
173,09/17/2021 00:00:00,1108417,11,5,S,ML,0.484,50,80,125.0,0.0263,68.0
186,09/17/2021 00:00:00,1108434,11,5,S,ML,0.607,40,100,99.0,0.0210,70.0
202,09/17/2021 00:00:00,1108452,11,5,S,ML,0.867,40,100,50.0,0.0108,68.4
205,09/17/2021 00:00:00,1108459,11,5,S,ML,0.932,0,0,117.0,0.0283,63.8
207,09/17/2021 00:00:00,1108461,11,5,S,ML,0.848,40,100,105.0,0.0231,68.6
...,...,...,...,...,...,...,...,...,...,...,...,...
396608,09/17/2021 23:55:00,1122567,11,5,S,ML,0.275,40,100,23.0,0.0061,70.2
396611,09/17/2021 23:55:00,1122583,11,5,S,ML,0.443,40,100,145.0,0.0259,72.8
396648,09/17/2021 23:55:00,1123134,11,5,S,ML,0.652,10,100,3.0,0.0058,65.1
396789,09/17/2021 23:55:00,1126426,11,5,S,ML,1.105,50,100,142.0,0.0236,70.9
396857,09/17/2021 23:55:00,1127123,11,5,S,ML,1.391,30,100,57.0,0.0139,69.3

In [224]:
for index in sorted_sensors: 
    print(len(filedata[filedata["Station"] == index]), index)

Flow         True
Avg Speed    True
dtype: bool 1114228
Flow         True
Avg Speed    True
dtype: bool 1118326
Flow         True
Avg Speed    True
dtype: bool 1118341
Flow         True
Avg Speed    True
dtype: bool 1114721
Flow         True
Avg Speed    True
dtype: bool 1118365
Flow         True
Avg Speed    True
dtype: bool 1118372
Flow         True
Avg Speed    True
dtype: bool 1118379
Flow         True
Avg Speed    True
dtype: bool 1123134
Flow         True
Avg Speed    True
dtype: bool 1118695
Flow         True
Avg Speed    True
dtype: bool 1120356
Flow         True
Avg Speed    True
dtype: bool 1118413
Flow         True
Avg Speed    True
dtype: bool 1118428
Flow         True
Avg Speed    True
dtype: bool 1114240
Flow         True
Avg Speed    True
dtype: bool 1118465
Flow         True
Avg Speed    True
dtype: bool 1118472
Flow         True
Avg Speed    True
dtype: bool 1114254
Flow         True
Avg Speed    True
dtype: bool 1118076
Flow         True
Avg Speed    True
dtype: bool 1117755
Flow         True
Avg Speed    True
dtype: bool 1114268
Flow         True
Avg Speed    True
dtype: bool 1117774
Flow         True
Avg Speed    True
dtype: bool 1117789
Flow         True
Avg Speed    True
dtype: bool 1117810
Flow         True
Avg Speed    True
dtype: bool 1117683
Flow         True
Avg Speed    True
dtype: bool 1108417
Flow         True
Avg Speed    True
dtype: bool 1117734
Flow         True
Avg Speed    True
dtype: bool 1108605
Flow         True
Avg Speed    True
dtype: bool 1118702
Flow         True
Avg Speed    True
dtype: bool 1117724
Flow         True
Avg Speed    True
dtype: bool 1108609
Flow         True
Avg Speed    True
dtype: bool 1117871
Flow         True
Avg Speed    True
dtype: bool 1108615
Flow         True
Avg Speed    True
dtype: bool 1117818
Flow         True
Avg Speed    True
dtype: bool 1126426
Flow         True
Avg Speed    True
dtype: bool 1114806
Flow         True
Avg Speed    True
dtype: bool 1108711
Flow         True
Avg Speed    True
dtype: bool 1108693
Flow         True
Avg Speed    True
dtype: bool 1119307
Flow         True
Avg Speed    True
dtype: bool 1118529
Flow         True
Avg Speed    True
dtype: bool 1108667
Flow         True
Avg Speed    True
dtype: bool 1119817
Flow         True
Avg Speed    True
dtype: bool 1108669
Flow         True
Avg Speed    True
dtype: bool 1108452
Flow         True
Avg Speed    True
dtype: bool 1108498
Flow         True
Avg Speed    True
dtype: bool 1127123
Flow         True
Avg Speed    True
dtype: bool 1122544
Flow         True
Avg Speed    True
dtype: bool 1120754
Flow         True
Avg Speed    True
dtype: bool 1122567
Flow         True
Avg Speed    True
dtype: bool 1122583
Flow         True
Avg Speed    True
dtype: bool 1108434
Flow         True
Avg Speed    True
dtype: bool 1119834
Flow         True
Avg Speed    True
dtype: bool 1119528
Flow         True
Avg Speed    True
dtype: bool 1119842
Flow         True
Avg Speed    True
dtype: bool 1108468
Flow         True
Avg Speed    True
dtype: bool 1108471
Flow         True
Avg Speed    True
dtype: bool 1108473
Flow         True
Avg Speed    True
dtype: bool 1119666
Flow         True
Avg Speed    True
dtype: bool 1108475
Flow         True
Avg Speed    True
dtype: bool 1108477
Flow         True
Avg Speed    True
dtype: bool 1108479
Flow         True
Avg Speed    True
dtype: bool 1108723
Flow         True
Avg Speed    True
dtype: bool 1119897
Flow         True
Avg Speed    True
dtype: bool 1108725
Flow         True
Avg Speed    True
dtype: bool 1119909
Flow         True
Avg Speed    True
dtype: bool 1108680
Flow         True
Avg Speed    True
dtype: bool 1119915
Flow         True
Avg Speed    True
dtype: bool 1108685
Flow         True
Avg Speed    True
dtype: bool 1108661
Flow         True
Avg Speed    True
dtype: bool 1108560
Flow         True
Avg Speed    True
dtype: bool 1108657
Flow         True
Avg Speed    True
dtype: bool 1108463
Flow         True
Avg Speed    True
dtype: bool 1108461
Flow         True
Avg Speed    True
dtype: bool 1108459
Flow         True
Avg Speed    True
dtype: bool 1108672
Flow         True
Avg Speed    True
dtype: bool 1122257
Flow         True
Avg Speed    True
dtype: bool 1119954
Flow         True
Avg Speed    True
dtype: bool 1119966
Flow         True
Avg Speed    True
dtype: bool 1119978
Flow         True
Avg Speed    True
dtype: bool 1121702
Flow         True
Avg Speed    True
dtype: bool 1121712
Flow         True
Avg Speed    True
dtype: bool 1121734

In [239]:
filedata[filedata["Station"] == sorted_sensors[3]]["Avg Speed"].unique()

array([70.2, 70.3, 70.9, 71.2, 70.8, 71.5, 71.3, 71.1, 71.8, 71.6, 72.9,
       69.4, 72.8, 72.3, 72.6, 73.3, 72.7, 72. , 71.9, 71.4, 72.2, 73.2,
       72.5, 73.5, 70.4, 73.4, 71.7, 73. , 72.1, 72.4, 70. , 70.7, 73.7,
       73.1, 70.1, 68.7,  nan, 69.3, 69.8, 70.5, 69. , 68.1, 66.8, 68.6,
       68.8, 68.4, 68.3, 68. , 67.8, 67.9, 67.2, 69.2, 69.5, 68.2, 66.6,
       67.7, 67.4, 66.9, 67.3, 67. , 67.5, 67.6, 66.4, 66.5, 66.2, 64.6,
       64.7, 63.4, 62.5, 61.8, 63.1, 60.8, 60.6, 56.6, 61.5, 64.8, 63.9,
       64.3, 65.7, 69.1, 69.7, 66.1, 68.5, 68.9, 66.7, 69.9, 70.6, 71. ])

In [20]:
filedata[filedata["Avg Speed"].isna()]

,Timestamp,Station,District,Freeway,Direction,Type,Length,Sample,Observed Percentage,Flow,Avg Occupancy,Avg Speed
132461,09/17/2021 08:00:00,1108417,11,5,S,ML,0.484,0,0,NaN,NaN,NaN
132474,09/17/2021 08:00:00,1108434,11,5,S,ML,0.607,0,0,NaN,NaN,NaN
132490,09/17/2021 08:00:00,1108452,11,5,S,ML,0.867,0,0,NaN,NaN,NaN
132493,09/17/2021 08:00:00,1108459,11,5,S,ML,0.932,0,0,NaN,NaN,NaN
132495,09/17/2021 08:00:00,1108461,11,5,S,ML,0.848,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
133410,09/17/2021 08:00:00,1122567,11,5,S,ML,0.275,0,0,NaN,NaN,NaN
133413,09/17/2021 08:00:00,1122583,11,5,S,ML,0.443,0,0,NaN,NaN,NaN
133450,09/17/2021 08:00:00,1123134,11,5,S,ML,0.652,0,0,NaN,NaN,NaN
133591,09/17/2021 08:00:00,1126426,11,5,S,ML,1.105,0,0,NaN,NaN,NaN
133659,09/17/2021 08:00:00,1127123,11,5,S,ML,1.391,0,0,NaN,NaN,NaN

In [19]:
filedata["Flow"].isna().sum()

80

In [179]:
len(sorted_sensors)

80

In [185]:
filedata["Timestamp"].unique()

array(['09/14/2021 00:00:00', '09/14/2021 00:05:00',
       '09/14/2021 00:10:00', '09/14/2021 00:15:00',
       '09/14/2021 00:20:00', '09/14/2021 00:25:00',
       '09/14/2021 00:30:00', '09/14/2021 00:35:00',
       '09/14/2021 00:40:00', '09/14/2021 00:45:00',
       '09/14/2021 00:50:00', '09/14/2021 00:55:00',
       '09/14/2021 01:00:00', '09/14/2021 01:05:00',
       '09/14/2021 01:10:00', '09/14/2021 01:15:00',
       '09/14/2021 01:20:00', '09/14/2021 01:25:00',
       '09/14/2021 01:30:00', '09/14/2021 01:35:00',
       '09/14/2021 01:40:00', '09/14/2021 01:45:00',
       '09/14/2021 01:50:00', '09/14/2021 01:55:00',
       '09/14/2021 02:00:00', '09/14/2021 02:05:00',
       '09/14/2021 02:10:00', '09/14/2021 02:15:00',
       '09/14/2021 02:20:00', '09/14/2021 02:25:00',
       '09/14/2021 02:30:00', '09/14/2021 02:35:00',
       '09/14/2021 02:40:00', '09/14/2021 02:45:00',
       '09/14/2021 02:50:00', '09/14/2021 02:55:00',
       '09/14/2021 03:00:00', '09/14/2021 03:05:00',
       '09/14/2021 03:10:00', '09/14/2021 03:15:00',
       '09/14/2021 03:20:00', '09/14/2021 03:25:00',
       '09/14/2021 03:30:00', '09/14/2021 03:35:00',
       '09/14/2021 03:40:00', '09/14/2021 03:45:00',
       '09/14/2021 03:50:00', '09/14/2021 03:55:00',
       '09/14/2021 04:00:00', '09/14/2021 04:05:00',
       '09/14/2021 04:10:00', '09/14/2021 04:15:00',
       '09/14/2021 04:20:00', '09/14/2021 04:25:00',
       '09/14/2021 04:30:00', '09/14/2021 04:35:00',
       '09/14/2021 04:40:00', '09/14/2021 04:45:00',
       '09/14/2021 04:50:00', '09/14/2021 04:55:00',
       '09/14/2021 05:00:00', '09/14/2021 05:05:00',
       '09/14/2021 05:10:00', '09/14/2021 05:15:00',
       '09/14/2021 05:20:00', '09/14/2021 05:25:00',
       '09/14/2021 05:30:00', '09/14/2021 05:35:00',
       '09/14/2021 05:40:00', '09/14/2021 05:45:00',
       '09/14/2021 05:50:00', '09/14/2021 05:55:00',
       '09/14/2021 06:00:00', '09/14/2021 06:05:00',
       '09/14/2021 06:10:00', '09/14/2021 06:15:00',
       '09/14/2021 06:20:00', '09/14/2021 06:25:00',
       '09/14/2021 06:30:00', '09/14/2021 06:35:00',
       '09/14/2021 06:40:00', '09/14/2021 06:45:00',
       '09/14/2021 06:50:00', '09/14/2021 06:55:00',
       '09/14/2021 07:00:00', '09/14/2021 07:05:00',
       '09/14/2021 07:10:00', '09/14/2021 07:15:00',
       '09/14/2021 07:20:00', '09/14/2021 07:25:00',
       '09/14/2021 07:30:00', '09/14/2021 07:35:00',
       '09/14/2021 07:40:00', '09/14/2021 07:45:00',
       '09/14/2021 07:50:00', '09/14/2021 07:55:00',
       '09/14/2021 08:00:00', '09/14/2021 08:05:00',
       '09/14/2021 08:10:00', '09/14/2021 08:15:00',
       '09/14/2021 08:20:00', '09/14/2021 08:25:00',
       '09/14/2021 08:30:00', '09/14/2021 08:35:00',
       '09/14/2021 08:40:00', '09/14/2021 08:45:00',
       '09/14/2021 08:50:00', '09/14/2021 08:55:00',
       '09/14/2021 09:00:00', '09/14/2021 09:05:00',
       '09/14/2021 09:10:00', '09/14/2021 09:15:00',
       '09/14/2021 09:20:00', '09/14/2021 09:25:00',
       '09/14/2021 09:30:00', '09/14/2021 09:35:00',
       '09/14/2021 09:40:00', '09/14/2021 09:45:00',
       '09/14/2021 09:50:00', '09/14/2021 09:55:00',
       '09/14/2021 10:00:00', '09/14/2021 10:05:00',
       '09/14/2021 10:10:00', '09/14/2021 10:15:00',
       '09/14/2021 10:20:00', '09/14/2021 10:25:00',
       '09/14/2021 10:30:00', '09/14/2021 10:35:00',
       '09/14/2021 10:40:00', '09/14/2021 10:45:00',
       '09/14/2021 10:50:00', '09/14/2021 10:55:00',
       '09/14/2021 11:00:00', '09/14/2021 11:05:00',
       '09/14/2021 11:10:00', '09/14/2021 11:15:00',
       '09/14/2021 11:20:00', '09/14/2021 11:25:00',
       '09/14/2021 11:30:00', '09/14/2021 11:35:00',
       '09/14/2021 11:40:00', '09/14/2021 11:45:00',
       '09/14/2021 11:50:00', '09/14/2021 11:55:00',
       '09/14/2021 12:00:00', '09/14/2021 12:05:00',
       '09/14/2021 12:10:00', '09/14/2021 12:15:00',
       '09/14/2021 12:20:00', '09/14/2021 12:25:00',
       '09/14/2021 12:30:00', '09/14/2021 12:35:00',
       '09/14/2021 12:40:00', '09/14/2021 12:45:00',
       '09/14/2021 12:50:00', '09/14/2021 12:55:00',
       '09/14/2021 13:00:00', '09/14/2021 13:05:00',
       '09/14/2021 13:10:00', '09/14/2021 13:15:00',
       '09/14/2021 13:20:00', '09/14/2021 13:25:00',
       '09/14/2021 13:30:00', '09/14/2021 13:35:00',
       '09/14/2021 13:40:00', '09/14/2021 13:45:00',
       '09/14/2021 13:50:00', '09/14/2021 13:55:00',
       '09/14/2021 14:00:00', '09/14/2021 14:05:00',
       '09/14/2021 14:10:00', '09/14/2021 14:15:00',
       '09/14/2021 14:20:00', '09/14/2021 14:25:00',
       '09/14/2021 14:30:00', '09/14/2021 14:35:00',
       '09/14/2021 14:40:00', '09/14/2021 14:45:00',
       '09/14/2021 14:50:00', '09/14/2021 14:55:00',
       '09/14/2021 15:00:00', '09/14/2021 15:05:00',
       '09/14/2021 15:10:00', '09/14/2021 15:15:00',
       '09/14/2021 15:20:00', '09/14/2021 15:25:00',
       '09/14/2021 15:30:00', '09/14/2021 15:35:00',
       '09/14/2021 15:40:00', '09/14/2021 15:45:00',
       '09/14/2021 15:50:00', '09/14/2021 15:55:00',
       '09/14/2021 16:00:00', '09/14/2021 16:05:00',
       '09/14/2021 16:10:00', '09/14/2021 16:15:00',
       '09/14/2021 16:20:00', '09/14/2021 16:25:00',
       '09/14/2021 16:30:00', '09/14/2021 16:35:00',
       '09/14/2021 16:40:00', '09/14/2021 16:45:00',
       '09/14/2021 16:50:00', '09/14/2021 16:55:00',
       '09/14/2021 17:00:00', '09/14/2021 17:05:00',
       '09/14/2021 17:10:00', '09/14/2021 17:15:00',
       '09/14/2021 17:20:00', '09/14/2021 17:25:00',
       '09/14/2021 17:30:00', '09/14/2021 17:35:00',
       '09/14/2021 17:40:00', '09/14/2021 17:45:00',
       '09/14/2021 17:50:00', '09/14/2021 17:55:00',
       '09/14/2021 18:00:00', '09/14/2021 18:05:00',
       '09/14/2021 18:10:00', '09/14/2021 18:15:00',
       '09/14/2021 18:20:00', '09/14/2021 18:25:00',
       '09/14/2021 18:30:00', '09/14/2021 18:35:00',
       '09/14/2021 18:40:00', '09/14/2021 18:45:00',
       '09/14/2021 18:50:00', '09/14/2021 18:55:00',
       '09/14/2021 19:00:00', '09/14/2021 19:05:00',
       '09/14/2021 19:10:00', '09/14/2021 19:15:00',
       '09/14/2021 19:20:00', '09/14/2021 19:25:00',
       '09/14/2021 19:30:00', '09/14/2021 19:35:00',
       '09/14/2021 19:40:00', '09/14/2021 19:45:00',
       '09/14/2021 19:50:00', '09/14/2021 19:55:00',
       '09/14/2021 20:00:00', '09/14/2021 20:05:00',
       '09/14/2021 20:10:00', '09/14/2021 20:15:00',
       '09/14/2021 20:20:00', '09/14/2021 20:25:00',
       '09/14/2021 20:30:00', '09/14/2021 20:35:00',
       '09/14/2021 20:40:00', '09/14/2021 20:45:00',
       '09/14/2021 20:50:00', '09/14/2021 20:55:00',
       '09/14/2021 21:00:00', '09/14/2021 21:05:00',
       '09/14/2021 21:10:00', '09/14/2021 21:15:00',
       '09/14/2021 21:20:00', '09/14/2021 21:25:00',
       '09/14/2021 21:30:00', '09/14/2021 21:35:00',
       '09/14/2021 21:40:00', '09/14/2021 21:45:00',
       '09/14/2021 21:50:00', '09/14/2021 21:55:00',
       '09/14/2021 22:00:00', '09/14/2021 22:05:00',
       '09/14/2021 22:10:00', '09/14/2021 22:15:00',
       '09/14/2021 22:20:00', '09/14/2021 22:25:00',
       '09/14/2021 22:30:00', '09/14/2021 22:35:00',
       '09/14/2021 22:40:00', '09/14/2021 22:45:00',
       '09/14/2021 22:50:00', '09/14/2021 22:55:00',
       '09/14/2021 23:00:00', '09/14/2021 23:05:00',
       '09/14/2021 23:10:00', '09/14/2021 23:15:00',
       '09/14/2021 23:20:00', '09/14/2021 23:25:00',
       '09/14/2021 23:30:00', '09/14/2021 23:35:00',
       '09/14/2021 23:40:00', '09/14/2021 23:45:00',
       '09/14/2021 23:50:00', '09/14/2021 23:55:00',
       '09/15/2021 00:00:00', '09/15/2021 00:05:00',
       '09/15/2021 00:10:00', '09/15/2021 00:15:00',
       '09/15/2021 00:20:00', '09/15/2021 00:25:00',
       '09/15/2021 00:30:00', '09/15/2021 00:35:00',
       '09/15/2021 00:40:00', '09/15/2021 00:45:00',
       '09/15/2021 00:50:00', '09/15/2021 00:55:00',
       '09/15/2021 01:00:00', '09/15/2021 01:05:00',
       '09/15/2021 01:10:00', '09/15/2021 01:15:00',
       '09/15/2021 01:20:00', '09/15/2021 01:25:00',
       '09/15/2021 01:30:00', '09/15/2021 01:35:00',
       '09/15/2021 01:40:00', '09/15/2021 01:45:00',
       '09/15/2021 01:50:00', '09/15/2021 01:55:00',
       '09/15/2021 02:00:00', '09/15/2021 02:05:00',
       '09/15/2021 02:10:00', '09/15/2021 02:15:00',
       '09/15/2021 02:20:00', '09/15/2021 02:25:00',
       '09/15/2021 02:30:00', '09/15/2021 02:35:00',
       '09/15/2021 02:40:00', '09/15/2021 02:45:00',
       '09/15/2021 02:50:00', '09/15/2021 02:55:00',
       '09/15/2021 03:00:00', '09/15/2021 03:05:00',
       '09/15/2021 03:10:00', '09/15/2021 03:15:00',
       '09/15/2021 03:20:00', '09/15/2021 03:25:00',
       '09/15/2021 03:30:00', '09/15/2021 03:35:00',
       '09/15/2021 03:40:00', '09/15/2021 03:45:00',
       '09/15/2021 03:50:00', '09/15/2021 03:55:00',
       '09/15/2021 04:00:00', '09/15/2021 04:05:00',
       '09/15/2021 04:10:00', '09/15/2021 04:15:00',
       '09/15/2021 04:20:00', '09/15/2021 04:25:00',
       '09/15/2021 04:30:00', '09/15/2021 04:35:00',
       '09/15/2021 04:40:00', '09/15/2021 04:45:00'], dtype=object)

In [187]:
time = filedata["Timestamp"].unique().tolist()
time[:288]

['09/14/2021 00:00:00',
 '09/14/2021 00:05:00',
 '09/14/2021 00:10:00',
 '09/14/2021 00:15:00',
 '09/14/2021 00:20:00',
 '09/14/2021 00:25:00',
 '09/14/2021 00:30:00',
 '09/14/2021 00:35:00',
 '09/14/2021 00:40:00',
 '09/14/2021 00:45:00',
 '09/14/2021 00:50:00',
 '09/14/2021 00:55:00',
 '09/14/2021 01:00:00',
 '09/14/2021 01:05:00',
 '09/14/2021 01:10:00',
 '09/14/2021 01:15:00',
 '09/14/2021 01:20:00',
 '09/14/2021 01:25:00',
 '09/14/2021 01:30:00',
 '09/14/2021 01:35:00',
 '09/14/2021 01:40:00',
 '09/14/2021 01:45:00',
 '09/14/2021 01:50:00',
 '09/14/2021 01:55:00',
 '09/14/2021 02:00:00',
 '09/14/2021 02:05:00',
 '09/14/2021 02:10:00',
 '09/14/2021 02:15:00',
 '09/14/2021 02:20:00',
 '09/14/2021 02:25:00',
 '09/14/2021 02:30:00',
 '09/14/2021 02:35:00',
 '09/14/2021 02:40:00',
 '09/14/2021 02:45:00',
 '09/14/2021 02:50:00',
 '09/14/2021 02:55:00',
 '09/14/2021 03:00:00',
 '09/14/2021 03:05:00',
 '09/14/2021 03:10:00',
 '09/14/2021 03:15:00',
 '09/14/2021 03:20:00',
 '09/14/2021 03:25:00',
 '09/14/2021 03:30:00',
 '09/14/2021 03:35:00',
 '09/14/2021 03:40:00',
 '09/14/2021 03:45:00',
 '09/14/2021 03:50:00',
 '09/14/2021 03:55:00',
 '09/14/2021 04:00:00',
 '09/14/2021 04:05:00',
 '09/14/2021 04:10:00',
 '09/14/2021 04:15:00',
 '09/14/2021 04:20:00',
 '09/14/2021 04:25:00',
 '09/14/2021 04:30:00',
 '09/14/2021 04:35:00',
 '09/14/2021 04:40:00',
 '09/14/2021 04:45:00',
 '09/14/2021 04:50:00',
 '09/14/2021 04:55:00',
 '09/14/2021 05:00:00',
 '09/14/2021 05:05:00',
 '09/14/2021 05:10:00',
 '09/14/2021 05:15:00',
 '09/14/2021 05:20:00',
 '09/14/2021 05:25:00',
 '09/14/2021 05:30:00',
 '09/14/2021 05:35:00',
 '09/14/2021 05:40:00',
 '09/14/2021 05:45:00',
 '09/14/2021 05:50:00',
 '09/14/2021 05:55:00',
 '09/14/2021 06:00:00',
 '09/14/2021 06:05:00',
 '09/14/2021 06:10:00',
 '09/14/2021 06:15:00',
 '09/14/2021 06:20:00',
 '09/14/2021 06:25:00',
 '09/14/2021 06:30:00',
 '09/14/2021 06:35:00',
 '09/14/2021 06:40:00',
 '09/14/2021 06:45:00',
 '09/14/2021 06:50:00',
 '09/14/2021 06:55:00',
 '09/14/2021 07:00:00',
 '09/14/2021 07:05:00',
 '09/14/2021 07:10:00',
 '09/14/2021 07:15:00',
 '09/14/2021 07:20:00',
 '09/14/2021 07:25:00',
 '09/14/2021 07:30:00',
 '09/14/2021 07:35:00',
 '09/14/2021 07:40:00',
 '09/14/2021 07:45:00',
 '09/14/2021 07:50:00',
 '09/14/2021 07:55:00',
 '09/14/2021 08:00:00',
 '09/14/2021 08:05:00',
 '09/14/2021 08:10:00',
 '09/14/2021 08:15:00',
 '09/14/2021 08:20:00',
 '09/14/2021 08:25:00',
 '09/14/2021 08:30:00',
 '09/14/2021 08:35:00',
 '09/14/2021 08:40:00',
 '09/14/2021 08:45:00',
 '09/14/2021 08:50:00',
 '09/14/2021 08:55:00',
 '09/14/2021 09:00:00',
 '09/14/2021 09:05:00',
 '09/14/2021 09:10:00',
 '09/14/2021 09:15:00',
 '09/14/2021 09:20:00',
 '09/14/2021 09:25:00',
 '09/14/2021 09:30:00',
 '09/14/2021 09:35:00',
 '09/14/2021 09:40:00',
 '09/14/2021 09:45:00',
 '09/14/2021 09:50:00',
 '09/14/2021 09:55:00',
 '09/14/2021 10:00:00',
 '09/14/2021 10:05:00',
 '09/14/2021 10:10:00',
 '09/14/2021 10:15:00',
 '09/14/2021 10:20:00',
 '09/14/2021 10:25:00',
 '09/14/2021 10:30:00',
 '09/14/2021 10:35:00',
 '09/14/2021 10:40:00',
 '09/14/2021 10:45:00',
 '09/14/2021 10:50:00',
 '09/14/2021 10:55:00',
 '09/14/2021 11:00:00',
 '09/14/2021 11:05:00',
 '09/14/2021 11:10:00',
 '09/14/2021 11:15:00',
 '09/14/2021 11:20:00',
 '09/14/2021 11:25:00',
 '09/14/2021 11:30:00',
 '09/14/2021 11:35:00',
 '09/14/2021 11:40:00',
 '09/14/2021 11:45:00',
 '09/14/2021 11:50:00',
 '09/14/2021 11:55:00',
 '09/14/2021 12:00:00',
 '09/14/2021 12:05:00',
 '09/14/2021 12:10:00',
 '09/14/2021 12:15:00',
 '09/14/2021 12:20:00',
 '09/14/2021 12:25:00',
 '09/14/2021 12:30:00',
 '09/14/2021 12:35:00',
 '09/14/2021 12:40:00',
 '09/14/2021 12:45:00',
 '09/14/2021 12:50:00',
 '09/14/2021 12:55:00',
 '09/14/2021 13:00:00',
 '09/14/2021 13:05:00',
 '09/14/2021 13:10:00',
 '09/14/2021 13:15:00',
 '09/14/2021 13:20:00',
 '09/14/2021 13:25:00',
 '09/14/2021 13:30:00',
 '09/14/2021 13:35:00',
 '09/14/2021 13:40:00',
 '09/14/2021 13:45:00',
 '09/14/2021 13:50:00',
 '09/14/2021 13:55:00',
 '09/14/2021 14:00:00',
 '09/14/2021 14:05:00',
 '09/14/2021 14:10:00',
 '09/14/2021 14:15:00',
 '09/14/2021 14:20:00',
 '09/14/2021 14:25:00',
 '09/14/2021 14:30:00',
 '09/14/2021 14:35:00',
 '09/14/2021 14:40:00',
 '09/14/2021 14:45:00',
 '09/14/2021 14:50:00',
 '09/14/2021 14:55:00',
 '09/14/2021 15:00:00',
 '09/14/2021 15:05:00',
 '09/14/2021 15:10:00',
 '09/14/2021 15:15:00',
 '09/14/2021 15:20:00',
 '09/14/2021 15:25:00',
 '09/14/2021 15:30:00',
 '09/14/2021 15:35:00',
 '09/14/2021 15:40:00',
 '09/14/2021 15:45:00',
 '09/14/2021 15:50:00',
 '09/14/2021 15:55:00',
 '09/14/2021 16:00:00',
 '09/14/2021 16:05:00',
 '09/14/2021 16:10:00',
 '09/14/2021 16:15:00',
 '09/14/2021 16:20:00',
 '09/14/2021 16:25:00',
 '09/14/2021 16:30:00',
 '09/14/2021 16:35:00',
 '09/14/2021 16:40:00',
 '09/14/2021 16:45:00',
 '09/14/2021 16:50:00',
 '09/14/2021 16:55:00',
 '09/14/2021 17:00:00',
 '09/14/2021 17:05:00',
 '09/14/2021 17:10:00',
 '09/14/2021 17:15:00',
 '09/14/2021 17:20:00',
 '09/14/2021 17:25:00',
 '09/14/2021 17:30:00',
 '09/14/2021 17:35:00',
 '09/14/2021 17:40:00',
 '09/14/2021 17:45:00',
 '09/14/2021 17:50:00',
 '09/14/2021 17:55:00',
 '09/14/2021 18:00:00',
 '09/14/2021 18:05:00',
 '09/14/2021 18:10:00',
 '09/14/2021 18:15:00',
 '09/14/2021 18:20:00',
 '09/14/2021 18:25:00',
 '09/14/2021 18:30:00',
 '09/14/2021 18:35:00',
 '09/14/2021 18:40:00',
 '09/14/2021 18:45:00',
 '09/14/2021 18:50:00',
 '09/14/2021 18:55:00',
 '09/14/2021 19:00:00',
 '09/14/2021 19:05:00',
 '09/14/2021 19:10:00',
 '09/14/2021 19:15:00',
 '09/14/2021 19:20:00',
 '09/14/2021 19:25:00',
 '09/14/2021 19:30:00',
 '09/14/2021 19:35:00',
 '09/14/2021 19:40:00',
 '09/14/2021 19:45:00',
 '09/14/2021 19:50:00',
 '09/14/2021 19:55:00',
 '09/14/2021 20:00:00',
 '09/14/2021 20:05:00',
 '09/14/2021 20:10:00',
 '09/14/2021 20:15:00',
 '09/14/2021 20:20:00',
 '09/14/2021 20:25:00',
 '09/14/2021 20:30:00',
 '09/14/2021 20:35:00',
 '09/14/2021 20:40:00',
 '09/14/2021 20:45:00',
 '09/14/2021 20:50:00',
 '09/14/2021 20:55:00',
 '09/14/2021 21:00:00',
 '09/14/2021 21:05:00',
 '09/14/2021 21:10:00',
 '09/14/2021 21:15:00',
 '09/14/2021 21:20:00',
 '09/14/2021 21:25:00',
 '09/14/2021 21:30:00',
 '09/14/2021 21:35:00',
 '09/14/2021 21:40:00',
 '09/14/2021 21:45:00',
 '09/14/2021 21:50:00',
 '09/14/2021 21:55:00',
 '09/14/2021 22:00:00',
 '09/14/2021 22:05:00',
 '09/14/2021 22:10:00',
 '09/14/2021 22:15:00',
 '09/14/2021 22:20:00',
 '09/14/2021 22:25:00',
 '09/14/2021 22:30:00',
 '09/14/2021 22:35:00',
 '09/14/2021 22:40:00',
 '09/14/2021 22:45:00',
 '09/14/2021 22:50:00',
 '09/14/2021 22:55:00',
 '09/14/2021 23:00:00',
 '09/14/2021 23:05:00',
 '09/14/2021 23:10:00',
 '09/14/2021 23:15:00',
 '09/14/2021 23:20:00',
 '09/14/2021 23:25:00',
 '09/14/2021 23:30:00',
 '09/14/2021 23:35:00',
 '09/14/2021 23:40:00',
 '09/14/2021 23:45:00',
 '09/14/2021 23:50:00',
 '09/14/2021 23:55:00']

In [154]:
len(time)

288

In [106]:
time

['02/10/2021 00:00:00',
 '02/10/2021 00:05:00',
 '02/10/2021 00:10:00',
 '02/10/2021 00:15:00',
 '02/10/2021 00:20:00',
 '02/10/2021 00:25:00',
 '02/10/2021 00:30:00',
 '02/10/2021 00:35:00',
 '02/10/2021 00:40:00',
 '02/10/2021 00:45:00',
 '02/10/2021 00:50:00',
 '02/10/2021 00:55:00',
 '02/10/2021 01:00:00',
 '02/10/2021 01:05:00',
 '02/10/2021 01:10:00',
 '02/10/2021 01:15:00',
 '02/10/2021 01:20:00',
 '02/10/2021 01:25:00',
 '02/10/2021 01:30:00',
 '02/10/2021 01:35:00',
 '02/10/2021 01:40:00',
 '02/10/2021 01:45:00',
 '02/10/2021 01:50:00',
 '02/10/2021 01:55:00',
 '02/10/2021 02:00:00',
 '02/10/2021 02:05:00',
 '02/10/2021 02:10:00',
 '02/10/2021 02:15:00',
 '02/10/2021 02:20:00',
 '02/10/2021 02:25:00',
 '02/10/2021 02:30:00',
 '02/10/2021 02:35:00',
 '02/10/2021 02:40:00',
 '02/10/2021 02:45:00',
 '02/10/2021 02:50:00',
 '02/10/2021 02:55:00',
 '02/10/2021 03:00:00',
 '02/10/2021 03:05:00',
 '02/10/2021 03:10:00',
 '02/10/2021 03:15:00',
 '02/10/2021 03:20:00',
 '02/10/2021 03:25:00',
 '02/10/2021 03:30:00',
 '02/10/2021 03:35:00',
 '02/10/2021 03:40:00',
 '02/10/2021 03:45:00',
 '02/10/2021 03:50:00',
 '02/10/2021 03:55:00',
 '02/10/2021 04:00:00',
 '02/10/2021 04:05:00',
 '02/10/2021 04:10:00',
 '02/10/2021 04:15:00',
 '02/10/2021 04:20:00',
 '02/10/2021 04:25:00',
 '02/10/2021 04:30:00',
 '02/10/2021 04:35:00',
 '02/10/2021 04:40:00',
 '02/10/2021 04:45:00',
 '02/10/2021 04:50:00',
 '02/10/2021 04:55:00',
 '02/10/2021 05:00:00',
 '02/10/2021 05:05:00',
 '02/10/2021 05:10:00',
 '02/10/2021 05:15:00',
 '02/10/2021 05:20:00',
 '02/10/2021 05:25:00',
 '02/10/2021 05:30:00',
 '02/10/2021 05:35:00',
 '02/10/2021 05:40:00',
 '02/10/2021 05:45:00',
 '02/10/2021 05:50:00',
 '02/10/2021 05:55:00',
 '02/10/2021 06:00:00',
 '02/10/2021 06:05:00',
 '02/10/2021 06:10:00',
 '02/10/2021 06:15:00',
 '02/10/2021 06:20:00',
 '02/10/2021 06:25:00',
 '02/10/2021 06:30:00',
 '02/10/2021 06:35:00',
 '02/10/2021 06:40:00',
 '02/10/2021 06:45:00',
 '02/10/2021 06:50:00',
 '02/10/2021 06:55:00',
 '02/10/2021 07:00:00',
 '02/10/2021 07:05:00',
 '02/10/2021 07:10:00',
 '02/10/2021 07:15:00',
 '02/10/2021 07:20:00',
 '02/10/2021 07:25:00',
 '02/10/2021 07:30:00',
 '02/10/2021 07:35:00',
 '02/10/2021 07:40:00',
 '02/10/2021 07:45:00',
 '02/10/2021 07:50:00',
 '02/10/2021 07:55:00',
 '02/10/2021 08:00:00',
 '02/10/2021 08:05:00',
 '02/10/2021 08:10:00',
 '02/10/2021 08:15:00',
 '02/10/2021 08:20:00',
 '02/10/2021 08:25:00',
 '02/10/2021 08:30:00',
 '02/10/2021 08:35:00',
 '02/10/2021 08:40:00',
 '02/10/2021 08:45:00',
 '02/10/2021 08:50:00',
 '02/10/2021 08:55:00',
 '02/10/2021 09:00:00',
 '02/10/2021 09:05:00',
 '02/10/2021 09:10:00',
 '02/10/2021 09:15:00',
 '02/10/2021 09:20:00',
 '02/10/2021 09:25:00',
 '02/10/2021 09:30:00',
 '02/10/2021 09:35:00',
 '02/10/2021 09:40:00',
 '02/10/2021 09:45:00',
 '02/10/2021 09:50:00',
 '02/10/2021 09:55:00',
 '02/10/2021 10:00:00',
 '02/10/2021 10:05:00',
 '02/10/2021 10:10:00',
 '02/10/2021 10:15:00',
 '02/10/2021 10:20:00',
 '02/10/2021 10:25:00',
 '02/10/2021 10:30:00',
 '02/10/2021 10:35:00',
 '02/10/2021 10:40:00',
 '02/10/2021 10:45:00',
 '02/10/2021 10:50:00',
 '02/10/2021 10:55:00',
 '02/10/2021 11:00:00',
 '02/10/2021 11:05:00',
 '02/10/2021 11:10:00',
 '02/10/2021 11:15:00',
 '02/10/2021 11:20:00',
 '02/10/2021 11:25:00',
 '02/10/2021 11:30:00',
 '02/10/2021 11:35:00',
 '02/10/2021 11:40:00',
 '02/10/2021 11:45:00',
 '02/10/2021 11:50:00',
 '02/10/2021 11:55:00',
 '02/10/2021 12:00:00',
 '02/10/2021 12:05:00',
 '02/10/2021 12:10:00',
 '02/10/2021 12:15:00',
 '02/10/2021 12:20:00',
 '02/10/2021 12:25:00',
 '02/10/2021 12:30:00',
 '02/10/2021 12:35:00',
 '02/10/2021 12:40:00',
 '02/10/2021 12:45:00',
 '02/10/2021 12:50:00',
 '02/10/2021 12:55:00',
 '02/10/2021 13:00:00',
 '02/10/2021 13:05:00',
 '02/10/2021 13:10:00',
 '02/10/2021 13:15:00',
 '02/10/2021 13:20:00',
 '02/10/2021 13:25:00',
 '02/10/2021 13:30:00',
 '02/10/2021 13:35:00',
 '02/10/2021 13:40:00',
 '02/10/2021 13:45:00',
 '02/10/2021 13:50:00',
 '02/10/2021 13:55:00',
 '02/10/2021 14:00:00',
 '02/10/2021 14:05:00',
 '02/10/2021 14:10:00',
 '02/10/2021 14:15:00',
 '02/10/2021 14:20:00',
 '02/10/2021 14:25:00',
 '02/10/2021 14:30:00',
 '02/10/2021 14:35:00',
 '02/10/2021 14:40:00',
 '02/10/2021 14:45:00',
 '02/10/2021 14:50:00',
 '02/10/2021 14:55:00',
 '02/10/2021 15:00:00',
 '02/10/2021 15:05:00',
 '02/10/2021 15:10:00',
 '02/10/2021 15:15:00',
 '02/10/2021 15:20:00',
 '02/10/2021 15:25:00',
 '02/10/2021 15:30:00',
 '02/10/2021 15:35:00',
 '02/10/2021 15:40:00',
 '02/10/2021 15:45:00',
 '02/10/2021 15:50:00',
 '02/10/2021 15:55:00',
 '02/10/2021 16:00:00',
 '02/10/2021 16:05:00',
 '02/10/2021 16:10:00',
 '02/10/2021 16:15:00',
 '02/10/2021 16:20:00',
 '02/10/2021 16:25:00',
 '02/10/2021 16:30:00',
 '02/10/2021 16:35:00',
 '02/10/2021 16:40:00',
 '02/10/2021 16:45:00',
 '02/10/2021 16:50:00',
 '02/10/2021 16:55:00',
 '02/10/2021 17:00:00',
 '02/10/2021 17:05:00',
 '02/10/2021 17:10:00',
 '02/10/2021 17:15:00',
 '02/10/2021 17:20:00',
 '02/10/2021 17:25:00',
 '02/10/2021 17:30:00',
 '02/10/2021 17:35:00',
 '02/10/2021 17:40:00',
 '02/10/2021 17:45:00',
 '02/10/2021 17:50:00',
 '02/10/2021 17:55:00',
 '02/10/2021 18:00:00',
 '02/10/2021 18:05:00',
 '02/10/2021 18:10:00',
 '02/10/2021 18:15:00',
 '02/10/2021 18:20:00',
 '02/10/2021 18:25:00',
 '02/10/2021 18:30:00',
 '02/10/2021 18:35:00',
 '02/10/2021 18:40:00',
 '02/10/2021 18:45:00',
 '02/10/2021 18:50:00',
 '02/10/2021 18:55:00',
 '02/10/2021 19:00:00',
 '02/10/2021 19:05:00',
 '02/10/2021 19:10:00',
 '02/10/2021 19:15:00',
 '02/10/2021 19:20:00',
 '02/10/2021 19:25:00',
 '02/10/2021 19:30:00',
 '02/10/2021 19:35:00',
 '02/10/2021 19:40:00',
 '02/10/2021 19:45:00',
 '02/10/2021 19:50:00',
 '02/10/2021 19:55:00',
 '02/10/2021 20:00:00',
 '02/10/2021 20:05:00',
 '02/10/2021 20:10:00',
 '02/10/2021 20:15:00',
 '02/10/2021 20:20:00',
 '02/10/2021 20:25:00',
 '02/10/2021 20:30:00',
 '02/10/2021 20:35:00',
 '02/10/2021 20:40:00',
 '02/10/2021 20:45:00',
 '02/10/2021 20:50:00',
 '02/10/2021 20:55:00',
 '02/10/2021 21:00:00',
 '02/10/2021 21:05:00',
 '02/10/2021 21:10:00',
 '02/10/2021 21:15:00',
 '02/10/2021 21:20:00',
 '02/10/2021 21:25:00',
 '02/10/2021 21:30:00',
 '02/10/2021 21:35:00',
 '02/10/2021 21:40:00',
 '02/10/2021 21:45:00',
 '02/10/2021 21:50:00',
 '02/10/2021 21:55:00',
 '02/10/2021 22:00:00',
 '02/10/2021 22:05:00',
 '02/10/2021 22:10:00',
 '02/10/2021 22:15:00',
 '02/10/2021 22:20:00',
 '02/10/2021 22:25:00',
 '02/10/2021 22:30:00',
 '02/10/2021 22:35:00',
 '02/10/2021 22:40:00',
 '02/10/2021 22:45:00',
 '02/10/2021 22:50:00',
 '02/10/2021 22:55:00',
 '02/10/2021 23:00:00',
 '02/10/2021 23:05:00',
 '02/10/2021 23:10:00',
 '02/10/2021 23:15:00',
 '02/10/2021 23:20:00',
 '02/10/2021 23:25:00',
 '02/10/2021 23:30:00',
 '02/10/2021 23:35:00',
 '02/10/2021 23:40:00',
 '02/10/2021 23:45:00',
 '02/10/2021 23:50:00',
 '02/10/2021 23:55:00']

In [60]:
import itertools 
pair = list(itertools.product(time, sorted_sensors))

In [61]:
filedata["Station"] = filedata["Station"].astype("category")
filedata["Timestamp"] = filedata["Timestamp"].astype("category")
filedata["Station"].cat.set_categories(sorted_sensors, inplace=True)
filedata["Timestamp"].cat.set_categories(time, inplace=True)

C:\Users\Stephen Ma\anaconda3\envs\env_pytorch\lib\site-packages\pandas\core\arrays\categorical.py:2630: FutureWarning: The `inplace` parameter in pandas.Categorical.set_categories is deprecated and will be removed in a future version. Removing unused categories will always return a new Categorical object.
  res = method(*args, **kwargs)

In [62]:
filedata = filedata.sort_values(["Station"])

In [63]:
filedata

,Timestamp,Station,District,Freeway,Direction,Type,Length,Sample,Observed Percentage,Flow,Avg Occupancy,Avg Speed
244607,01/01/2021 14:45:00,1114228,11,5,S,ML,0.681,60,100,129.0,0.0355,71.5
68223,01/01/2021 04:05:00,1114228,11,5,S,ML,0.681,54,100,7.0,0.0022,72.0
152281,01/01/2021 09:10:00,1114228,11,5,S,ML,0.681,60,100,49.0,0.0137,71.3
94405,01/01/2021 05:40:00,1114228,11,5,S,ML,0.681,60,100,14.0,0.0030,67.5
106807,01/01/2021 06:25:00,1114228,11,5,S,ML,0.681,60,100,19.0,0.0050,70.3
...,...,...,...,...,...,...,...,...,...,...,...,...
335924,01/01/2021 20:15:00,1121734,11,5,S,ML,3.822,0,0,168.0,0.0389,64.4
301474,01/01/2021 18:10:00,1121734,11,5,S,ML,3.822,0,0,242.0,0.0517,64.6
184344,01/01/2021 11:05:00,1121734,11,5,S,ML,3.822,40,0,259.0,0.0525,65.3
236708,01/01/2021 14:15:00,1121734,11,5,S,ML,3.822,40,0,289.0,0.0614,65.4
249110,01/01/2021 15:00:00,1121734,11,5,S,ML,3.822,40,0,341.0,0.0708,65.7

In [74]:
for i in range(1, 79): 
    filedata.iloc[288 * (i - 1) : 288 * i] = filedata.iloc[288 * (i - 1) : 288 * i].sort_values(["Timestamp"])

In [73]:
filedata

,Timestamp,Station,District,Freeway,Direction,Type,Length,Sample,Observed Percentage,Flow,Avg Occupancy,Avg Speed
345570,09/16/2021 00:00:00,1121734,11,5,S,ML,3.822,0,0,125.0,0.0278,65.1
104420,09/16/2021 00:05:00,1121734,11,5,S,ML,3.822,0,0,122.0,0.0270,65.0
276670,09/16/2021 00:10:00,1121734,11,5,S,ML,3.822,0,0,139.0,0.0307,65.0
67214,09/16/2021 00:15:00,1121734,11,5,S,ML,3.822,0,0,139.0,0.0291,65.3
366240,09/16/2021 00:20:00,1121734,11,5,S,ML,3.822,0,0,153.0,0.0335,64.4
...,...,...,...,...,...,...,...,...,...,...,...,...
241851,09/16/2021 23:35:00,1114228,11,5,S,ML,0.681,60,67,82.0,0.0286,68.2
58577,09/16/2021 23:40:00,1114228,11,5,S,ML,0.681,60,67,71.0,0.0252,68.4
368627,09/16/2021 23:45:00,1114228,11,5,S,ML,0.681,60,67,62.0,0.0367,69.4
214291,09/16/2021 23:50:00,1114228,11,5,S,ML,0.681,60,67,67.0,0.0272,69.3
101295,09/16/2021 23:55:00,1114228,11,5,S,ML,0.681,60,67,61.0,0.0254,68.2

In [70]:
npfile = filedata[["Flow", "Avg Speed"]].to_numpy()
npfile

array([[125. ,  65.1],
       [122. ,  65. ],
       [139. ,  65. ],
       ...,
       [ 62. ,  69.4],
       [ 67. ,  69.3],
       [ 61. ,  68.2]])

In [72]:
npfile[0]

array([125. ,  65.1])

In [67]:
temp = npfile[:288]
temp

array([[ 33. ,  71.8],
       [ 13. ,  72.5],
       [ 16. ,  70. ],
       [ 22. ,  69.3],
       [ 24. ,  68.8],
       [ 23. ,  71.3],
       [ 23. ,  73.1],
       [ 20. ,  72.1],
       [ 28. ,  71.9],
       [ 30. ,  71. ],
       [ 24. ,  71.2],
       [ 34. ,  71.5],
       [ 19. ,  71.5],
       [ 18. ,  73.1],
       [ 19. ,  72.5],
       [ 21. ,  70.9],
       [ 16. ,  71.3],
       [ 20. ,  71.7],
       [ 20. ,  71.1],
       [ 11. ,  71.3],
       [  8. ,  71.2],
       [ 16. ,  71.2],
       [ 17. ,  71.7],
       [ 12. ,  71.1],
       [ 15. ,  69.6],
       [ 11. ,  69.1],
       [  7. ,  73.1],
       [ 10. ,  73.2],
       [ 11. ,  71.8],
       [  9. ,  71.9],
       [  9. ,  73.5],
       [  7. ,  71.9],
       [ 10. ,  70. ],
       [  5. ,  69.7],
       [  5. ,  67.2],
       [  3. ,  70.2],
       [ 10. ,  69.9],
       [ 10. ,  71.2],
       [  9. ,  72.1],
       [  6. ,  72. ],
       [  6. ,  71.7],
       [  9. ,  69.8],
       [  6. ,  70.1],
       [  3. ,  71.6],
       [  9. ,  73.1],
       [  7. ,  72.1],
       [  7. ,  73.4],
       [  6. ,  74.9],
       [  3. ,  71.2],
       [  7. ,  72. ],
       [  7. ,  72.3],
       [ 10. ,  72.3],
       [  5. ,  71.3],
       [  4. ,  72.9],
       [  1. ,  74.1],
       [  2. ,  69.5],
       [  4. ,  71.1],
       [  5. ,  75.5],
       [  9. ,  70.6],
       [  7. ,  69.9],
       [  7. ,  73. ],
       [  5. ,  64.4],
       [  1. ,  69.4],
       [  5. ,  70.3],
       [  7. ,  72.3],
       [ 14. ,  68.7],
       [ 11. ,  69.1],
       [ 14. ,  69. ],
       [ 14. ,  67.5],
       [  7. ,  67.5],
       [ 10. ,  68. ],
       [  9. ,  67.1],
       [ 10. ,  70.5],
       [  7. ,  69.9],
       [ 19. ,  71.1],
       [ 12. ,  70.9],
       [ 21. ,  71.6],
       [ 19. ,  70.3],
       [ 16. ,  71.4],
       [ 16. ,  72. ],
       [ 10. ,  71.7],
       [ 12. ,  71.6],
       [ 14. ,  69.3],
       [ 19. ,  70.7],
       [ 10. ,  72. ],
       [ 24. ,  70.6],
       [ 13. ,  71.9],
       [ 25. ,  72.1],
       [ 23. ,  71.5],
       [ 21. ,  72.1],
       [ 25. ,  71.8],
       [ 25. ,  69.8],
       [ 29. ,  71.6],
       [ 31. ,  72.5],
       [ 29. ,  72.2],
       [ 32. ,  71.8],
       [ 37. ,  71.4],
       [ 36. ,  72.1],
       [ 38. ,  71.9],
       [ 36. ,  71. ],
       [ 32. ,  71.7],
       [ 38. ,  71.6],
       [ 44. ,  71.4],
       [ 25. ,  72.1],
       [ 42. ,  71.5],
       [ 61. ,  71.8],
       [ 54. ,  70.2],
       [ 49. ,  72. ],
       [ 49. ,  72. ],
       [ 51. ,  71.4],
       [ 49. ,  71.3],
       [ 65. ,  71.8],
       [ 53. ,  72.1],
       [ 52. ,  70.5],
       [ 59. ,  71.7],
       [ 80. ,  70.7],
       [ 68. ,  71.1],
       [ 74. ,  71.2],
       [ 89. ,  69.6],
       [ 68. ,  68.7],
       [ 73. ,  69.7],
       [105. ,  70.2],
       [ 80. ,  70.3],
       [ 78. ,  69.9],
       [ 87. ,  69.6],
       [ 69. ,  69.5],
       [ 81. ,  70.9],
       [ 88. ,  71.1],
       [ 87. ,  70.2],
       [ 95. ,  70.2],
       [ 92. ,  71.1],
       [106. ,  71.5],
       [ 92. ,  69.2],
       [109. ,  69. ],
       [114. ,  68.4],
       [120. ,  69.3],
       [106. ,  69.6],
       [110. ,  69.4],
       [ 86. ,  69.8],
       [123. ,  69.1],
       [111. ,  69.7],
       [112. ,  68.9],
       [109. ,  69.1],
       [118. ,  71.1],
       [118. ,  69.4],
       [101. ,  69.3],
       [125. ,  70.3],
       [ 98. ,  70.6],
       [126. ,  70.5],
       [113. ,  70.6],
       [117. ,  70.3],
       [133. ,  69.7],
       [111. ,  70.1],
       [115. ,  71.3],
       [126. ,  71. ],
       [128. ,  71.7],
       [107. ,  69.7],
       [134. ,  69.1],
       [148. ,  69.5],
       [127. ,  69.3],
       [120. ,  69.8],
       [140. ,  69.7],
       [119. ,  70. ],
       [149. ,  70.2],
       [134. ,  69.5],
       [138. ,  69.7],
       [138. ,  70.8],
       [128. ,  70.3],
       [148. ,  71.5],
       [129. ,  70.7],
       [136. ,  70.9],
       [132. ,  71.5],
       [141. ,  70.2],
       [127. ,  70.1],
       [132. ,  71.4],
       [154. ,  70.9],
       [129. ,  71.7],
       [129. ,  71.5],
       [115. ,  70. ],
       [138. ,  70.5],
       [137. ,  70.6],
       [144. ,  71.2],
       [132. ,  70.8],
       [137. ,  70.3],
       [121. ,  71.6],
       [123. ,  70.8],
       [120. ,  70. ],
       [127. ,  71. ],
       [155. ,  70.5],
       [117. ,  69.9],
       [130. ,  69.9],
       [101. ,  70.4],
       [124. ,  70.5],
       [106. ,  72.4],
       [111. ,  71.7],
       [135. ,  70.9],
       [139. ,  70.6],
       [113. ,  71.3],
       [119. ,  70.2],
       [116. ,  71.4],
       [122. ,  69.6],
       [110. ,  70.3],
       [142. ,  71.2],
       [ 96. ,  72. ],
       [101. ,  72.4],
       [101. ,  72.1],
       [100. ,  72.8],
       [112. ,  72. ],
       [105. ,  72. ],
       [107. ,  70. ],
       [105. ,  69.6],
       [120. ,  69.9],
       [ 92. ,  69. ],
       [110. ,  70. ],
       [123. ,  69.3],
       [ 92. ,  70. ],
       [ 86. ,  71.4],
       [ 89. ,  69.2],
       [ 96. ,  69.4],
       [112. ,  69.8],
       [101. ,  69.2],
       [112. ,  69.8],
       [ 91. ,  70.2],
       [ 85. ,  70.7],
       [ 98. ,  69.9],
       [110. ,  70.5],
       [ 87. ,  68.9],
       [ 91. ,  69. ],
       [ 79. ,  71. ],
       [ 79. ,  70.3],
       [ 85. ,  70.9],
       [ 74. ,  71.7],
       [ 81. ,  71.1],
       [ 76. ,  70.7],
       [ 81. ,  71. ],
       [ 84. ,  71.8],
       [ 77. ,  72.1],
       [ 71. ,  70.9],
       [ 68. ,  71. ],
       [ 67. ,  70.7],
       [ 77. ,  70.8],
       [ 64. ,  70.5],
       [ 62. ,  70.3],
       [ 70. ,  70.7],
       [ 63. ,  71.3],
       [ 56. ,  70.3],
       [ 58. ,  69.4],
       [ 56. ,  69.9],
       [ 53. ,  70.3],
       [ 66. ,  70.5],
       [ 53. ,  70.4],
       [ 41. ,  72.4],
       [ 57. ,  70. ],
       [ 54. ,  69.5],
       [ 64. ,  69.3],
       [ 53. ,  70.1],
       [ 55. ,  70.4],
       [ 46. ,  70.2],
       [ 41. ,  68.9],
       [ 45. ,  70.7],
       [ 62. ,  71.4],
       [ 55. ,  69.9],
       [ 43. ,  69.7],
       [ 47. ,  70.7],
       [ 47. ,  70.2],
       [ 38. ,  71.2],
       [ 49. ,  71.8],
       [ 46. ,  70.7],
       [ 43. ,  69.7],
       [ 46. ,  71. ],
       [ 38. ,  69.8],
       [ 36. ,  72.5],
       [ 27. ,  70. ],
       [ 31. ,  71.7],
       [ 24. ,  69.7],
       [ 31. ,  69.4],
       [ 34. ,  70.8],
       [ 37. ,  69.7],
       [ 24. ,  71.1],
       [ 35. ,  69.9],
       [ 23. ,  72.6],
       [ 30. ,  69.7],
       [ 22. ,  72.6],
       [ 35. ,  69.6],
       [ 15. ,  72.9],
       [ 17. ,  70.6],
       [ 30. ,  70.8],
       [ 20. ,  72.7]])

In [69]:
aa = npfile.reshape(85, -1)

In [70]:
aa[0]

array([ 33. ,  71.8,  13. ,  72.5,  16. ,  70. ,  22. ,  69.3,  24. ,
        68.8,  23. ,  71.3,  23. ,  73.1,  20. ,  72.1,  28. ,  71.9,
        30. ,  71. ,  24. ,  71.2,  34. ,  71.5,  19. ,  71.5,  18. ,
        73.1,  19. ,  72.5,  21. ,  70.9,  16. ,  71.3,  20. ,  71.7,
        20. ,  71.1,  11. ,  71.3,   8. ,  71.2,  16. ,  71.2,  17. ,
        71.7,  12. ,  71.1,  15. ,  69.6,  11. ,  69.1,   7. ,  73.1,
        10. ,  73.2,  11. ,  71.8,   9. ,  71.9,   9. ,  73.5,   7. ,
        71.9,  10. ,  70. ,   5. ,  69.7,   5. ,  67.2,   3. ,  70.2,
        10. ,  69.9,  10. ,  71.2,   9. ,  72.1,   6. ,  72. ,   6. ,
        71.7,   9. ,  69.8,   6. ,  70.1,   3. ,  71.6,   9. ,  73.1,
         7. ,  72.1,   7. ,  73.4,   6. ,  74.9,   3. ,  71.2,   7. ,
        72. ,   7. ,  72.3,  10. ,  72.3,   5. ,  71.3,   4. ,  72.9,
         1. ,  74.1,   2. ,  69.5,   4. ,  71.1,   5. ,  75.5,   9. ,
        70.6,   7. ,  69.9,   7. ,  73. ,   5. ,  64.4,   1. ,  69.4,
         5. ,  70.3,   7. ,  72.3,  14. ,  68.7,  11. ,  69.1,  14. ,
        69. ,  14. ,  67.5,   7. ,  67.5,  10. ,  68. ,   9. ,  67.1,
        10. ,  70.5,   7. ,  69.9,  19. ,  71.1,  12. ,  70.9,  21. ,
        71.6,  19. ,  70.3,  16. ,  71.4,  16. ,  72. ,  10. ,  71.7,
        12. ,  71.6,  14. ,  69.3,  19. ,  70.7,  10. ,  72. ,  24. ,
        70.6,  13. ,  71.9,  25. ,  72.1,  23. ,  71.5,  21. ,  72.1,
        25. ,  71.8,  25. ,  69.8,  29. ,  71.6,  31. ,  72.5,  29. ,
        72.2,  32. ,  71.8,  37. ,  71.4,  36. ,  72.1,  38. ,  71.9,
        36. ,  71. ,  32. ,  71.7,  38. ,  71.6,  44. ,  71.4,  25. ,
        72.1,  42. ,  71.5,  61. ,  71.8,  54. ,  70.2,  49. ,  72. ,
        49. ,  72. ,  51. ,  71.4,  49. ,  71.3,  65. ,  71.8,  53. ,
        72.1,  52. ,  70.5,  59. ,  71.7,  80. ,  70.7,  68. ,  71.1,
        74. ,  71.2,  89. ,  69.6,  68. ,  68.7,  73. ,  69.7, 105. ,
        70.2,  80. ,  70.3,  78. ,  69.9,  87. ,  69.6,  69. ,  69.5,
        81. ,  70.9,  88. ,  71.1,  87. ,  70.2,  95. ,  70.2,  92. ,
        71.1, 106. ,  71.5,  92. ,  69.2, 109. ,  69. , 114. ,  68.4,
       120. ,  69.3, 106. ,  69.6, 110. ,  69.4,  86. ,  69.8, 123. ,
        69.1, 111. ,  69.7, 112. ,  68.9, 109. ,  69.1, 118. ,  71.1,
       118. ,  69.4, 101. ,  69.3, 125. ,  70.3,  98. ,  70.6, 126. ,
        70.5, 113. ,  70.6, 117. ,  70.3, 133. ,  69.7, 111. ,  70.1,
       115. ,  71.3, 126. ,  71. , 128. ,  71.7, 107. ,  69.7, 134. ,
        69.1, 148. ,  69.5, 127. ,  69.3, 120. ,  69.8, 140. ,  69.7,
       119. ,  70. , 149. ,  70.2, 134. ,  69.5, 138. ,  69.7, 138. ,
        70.8, 128. ,  70.3, 148. ,  71.5, 129. ,  70.7, 136. ,  70.9,
       132. ,  71.5, 141. ,  70.2, 127. ,  70.1, 132. ,  71.4, 154. ,
        70.9, 129. ,  71.7, 129. ,  71.5, 115. ,  70. , 138. ,  70.5,
       137. ,  70.6, 144. ,  71.2, 132. ,  70.8, 137. ,  70.3, 121. ,
        71.6, 123. ,  70.8, 120. ,  70. , 127. ,  71. , 155. ,  70.5,
       117. ,  69.9, 130. ,  69.9, 101. ,  70.4, 124. ,  70.5, 106. ,
        72.4, 111. ,  71.7, 135. ,  70.9, 139. ,  70.6, 113. ,  71.3,
       119. ,  70.2, 116. ,  71.4, 122. ,  69.6, 110. ,  70.3, 142. ,
        71.2,  96. ,  72. , 101. ,  72.4, 101. ,  72.1, 100. ,  72.8,
       112. ,  72. , 105. ,  72. , 107. ,  70. , 105. ,  69.6, 120. ,
        69.9,  92. ,  69. , 110. ,  70. , 123. ,  69.3,  92. ,  70. ,
        86. ,  71.4,  89. ,  69.2,  96. ,  69.4, 112. ,  69.8, 101. ,
        69.2, 112. ,  69.8,  91. ,  70.2,  85. ,  70.7,  98. ,  69.9,
       110. ,  70.5,  87. ,  68.9,  91. ,  69. ,  79. ,  71. ,  79. ,
        70.3,  85. ,  70.9,  74. ,  71.7,  81. ,  71.1,  76. ,  70.7,
        81. ,  71. ,  84. ,  71.8,  77. ,  72.1,  71. ,  70.9,  68. ,
        71. ,  67. ,  70.7,  77. ,  70.8,  64. ,  70.5,  62. ,  70.3,
        70. ,  70.7,  63. ,  71.3,  56. ,  70.3,  58. ,  69.4,  56. ,
        69.9,  53. ,  70.3,  66. ,  70.5,  53. ,  70.4,  41. ,  72.4,
        57. ,  70. ,  54. ,  69.5,  64. ,  69.3,  53. ,  70.1,  55. ,
        70.4,  46. ,  70.2,  41. ,  68.9,  45. ,  70.7,  62. ,  71.4,
        55. ,  69.9,  43. ,  69.7,  47. ,  70.7,  47. ,  70.2,  38. ,
        71.2,  49. ,  71.8,  46. ,  70.7,  43. ,  69.7,  46. ,  71. ,
        38. ,  69.8,  36. ,  72.5,  27. ,  70. ,  31. ,  71.7,  24. ,
        69.7,  31. ,  69.4,  34. ,  70.8,  37. ,  69.7,  24. ,  71.1,
        35. ,  69.9,  23. ,  72.6,  30. ,  69.7,  22. ,  72.6,  35. ,
        69.6,  15. ,  72.9,  17. ,  70.6,  30. ,  70.8,  20. ,  72.7])

In [71]:
aaa = aa.reshape(85, 288, 2)

In [72]:
import torch 

b = torch.tensor(aaa).permute(2, 1, 0)

In [77]:
b[0]

tensor([[33.,  8., 11.,  ..., 88., 22., 61.],
        [13.,  7.,  7.,  ..., 67., 23., 54.],
        [16., 12., 19.,  ..., 76., 30., 74.],
        ...,
        [17., 10., 15.,  ..., 67., 38., 68.],
        [30., 18., 19.,  ..., 56., 32., 74.],
        [20.,  7.,  9.,  ..., 55., 43., 74.]], dtype=torch.float64)

In [75]:
b.shape

torch.Size([2, 288, 85])

In [30]:
file2 = file2[(file2["Fwy"] == 5) & (file2["Type"] == "ML")]

In [65]:
file2

,ID,Fwy,Dir,District,County,City,State_PM,Abs_PM,Latitude,Longitude,Length,Type,Lanes,Name,User_ID_1,User_ID_2,User_ID_3,User_ID_4
0,1100313,5,N,11,73,66000.0,R22.324,22.215,32.791540,-117.207160,NaN,FR,1,CLAIREMONT DR,151,NaN,NaN,NaN
1,1100323,5,N,11,73,66000.0,R34.142,34.033,32.950106,-117.243571,NaN,FR,2,DEL MAR HTS RD,129,NaN,NaN,NaN
2,1100326,5,N,11,73,66000.0,R36.232,36.123,32.979357,-117.252719,NaN,FR,2,VIA DE LA VALLE,130,NaN,NaN,NaN
3,1100330,5,N,11,73,66000.0,R37.37,37.261,32.995494,-117.256350,NaN,FR,2,LOMAS SANTA FE,341,NaN,NaN,NaN
4,1100333,5,N,11,73,22678.0,R38.54,38.431,33.010364,-117.264530,NaN,FR,1,MANCHESTER AVE,133,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1513,1126631,15,S,11,73,66000.0,R11.079,11.250,32.848370,-117.117157,3.232,HV,2,S/O HOV LANES,21511,NaN,NaN,NaN
1514,1126633,15,N,11,73,66000.0,R11.081,11.262,32.848425,-117.116631,3.230,HV,1,S/O HOV LANES,21512,NaN,NaN,NaN
1515,1126639,5,S,11,73,66000.0,R30.921,30.812,32.907588,-117.226265,0.301,ML,3,5 SB @ I-805,4046,NaN,NaN,NaN
1516,1126645,805,S,11,73,13392.0,8.442,8.293,32.653505,-117.070333,NaN,OR,2,54 WB 805 SB,16801,NaN,NaN,NaN
1517,1126648,805,S,11,73,13392.0,8.526,8.377,32.654470,-117.071228,NaN,FR,2,805 SB Fr 54 WB,46801,NaN,NaN,NaN

In [35]:
y = file3["ID"].unique()

In [38]:
z = file2["ID"].unique()

In [15]:
y, y.shape

(array([1100313, 1100323, 1100326, ..., 1126639, 1126645, 1126648],
       dtype=int64),
 (1518,))

In [32]:
file3 = file3[(file3["Fwy"] == 5) & (file3["Type"] == "ML")]

In [33]:
file3

,ID,Fwy,Dir,District,County,City,State_PM,Abs_PM,Latitude,Longitude,Length,Type,Lanes,Name,User_ID_1,User_ID_2,User_ID_3,User_ID_4
201,1108417,5,S,11,73,66000.0,R16.11,16.001,32.723898,-117.156068,0.484,ML,5,5th Ave,10512,NaN,NaN,NaN
217,1108434,5,S,11,73,66000.0,R32.805,32.663,32.930855,-117.241058,0.607,ML,4,CARMEL VALLEY RD,12211,NaN,NaN,NaN
220,1108437,5,N,11,73,66000.0,R32.902,32.793,32.932244,-117.241031,0.219,ML,4,CARMEL VALLEY RD,12212,NaN,NaN,NaN
234,1108452,5,S,11,73,66000.0,R27.903,27.794,32.864527,-117.230028,0.867,ML,4,Nobel Dr,16307,NaN,NaN,NaN
237,1108459,5,S,11,73,53322.0,R52.408,52.266,33.191277,-117.363281,0.932,ML,4,Oceanside Blvd,15003,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1462,1126385,5,N,11,73,66000.0,R20.057,19.948,32.759167,-117.203716,0.458,ML,6,5 NB N/O 8,16212,NaN,NaN,NaN
1463,1126392,5,S,11,73,66000.0,R20.056,19.947,32.759108,-117.203975,0.467,ML,5,5 SB N/O 8,16211,NaN,NaN,NaN
1466,1126411,5,N,11,73,66000.0,R20.867,20.758,32.770668,-117.206677,0.387,ML,4,Sea World Dr to 5 NB,16210,NaN,NaN,NaN
1468,1126426,5,S,11,73,66000.0,R20.72,20.611,32.768531,-117.206423,0.710,ML,5,Seawrold Dr to 5SB,16201,NaN,NaN,NaN
1510,1126639,5,S,11,73,66000.0,R30.921,30.812,32.907588,-117.226265,0.301,ML,3,5 SB @ I-805,4046,NaN,NaN,NaN

In [36]:
list(set(x) - set(y))

[1114660]

In [37]:
list(set(y) - set(x))

[1126639]

In [42]:
len(list(set(x).intersection(y).intersection(z)))

211

In [44]:
a = list(set(x).intersection(y))
len(list(set(a).intersection(z)))

211